### ISSUE TITLE
TUĞBA YILDIZ [mobile]["uzaktan", "yüz yüze"][zorunlu]14 hafta]

### ISSUE THREAD

**Issue by tugbayldz8** [VB10/staj_2024#100]
### Kişisel:

- **Ad Soyad:** Tuğba Yıldız
- **Okul:** Manisa Celal Bayar Üniversitesi
- **Sınıf:** 4. sınıf
- **CV:** [https://drive.google.com/file/d/1I8tPhnkARMlIN2zF-72rc_psUgk4uuKd/view?usp=sharing](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendin Hakkında (kendini anlatmak istersen): 
Merhaba. Bahar dönemi zorunlu 70 iş günü (19 Şubat 2024 - 27 Mayıs 2024) stajım için Mobil Uygulama Geliştirme alanında şirket arayışındayım. Kuruluşunuza katkıda bulunmayı ve uygulamalı deneyim kazanmayı çok istiyorum. 

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları) https://github.com/tugbayldz8

- **İlgilendiklerim (diller, frameworkler vs):** Flutter, Dart

**Comment by VB10** [comment]
Merhaba @tugbayldz8, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @tugbayldz8, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @tugbayldz8, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
