### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by ahmettunahanbekdas** [VB10/staj_2024#104]
### Kişisel Bilgilerim:
- **Ad Soyad:** AHMET TUNAHAN BEKDAŞ
- **Okul:** BEYKENT ÜNİVERSİTESİ
- **Sınıf:** 4.Sınıf
- **CV:**[Ahmet Tunahan Bekdas Resume.pdf](https://github.com/VB10/staj_2024/files/14099230/Ahmet.Tunahan.Bekdas.Resume.pdf)(#)
- **Sigorta Okul Karşılıyor:** Evet  

### Teknik:
[Linkedin](https://github.com/ahmettunahanbekdas)
[GitHub](https://github.com/ahmettunahanbekdas)
[Medium](https://medium.com/@tunahanbekdas)

AHMET TUNAHAN BEKDAŞ [mobile][uzaktan, yüzyüze][zorunlu, gönüllü][4hafta, 6hafta]

**Comment by VB10** [comment]
Merhaba @ahmettunahanbekdas, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ahmettunahanbekdas, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ahmettunahanbekdas, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ahmettunahanbekdas, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
