### ISSUE TITLE
Abdullah Akkoloğlu [frontend,blockchain,backend][uzaktan,yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by akkologlu** [VB10/staj_2024#106]
# Kişisel:

- **Ad Soyad:** Abdullah Akkoloğlu
- **Okul:** Muğla Sıtkı Koçman Üniversitesi
- **Sınıf:** 4
- **CV:** [Akkologlu_CV](https://drive.google.com/file/d/17cDyQc90Uew_SuGP47CVCSAydr1ep8Ez/view?usp=sharing)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet
- **Web Sitesi**: [akkologlu.com](https://akkologlu.com)
- **E-posta**: [E-posta](mailto:abdullahakkol@gmail.com)

#  Socials:
[![LinkedIn](https://img.shields.io/badge/LinkedIn-%230077B5.svg?logo=linkedin&logoColor=white)](https://linkedin.com/in/akkologlu) [![Medium](https://img.shields.io/badge/Medium-12100E?logo=medium&logoColor=white)](https://medium.com/@akkologlu) [![X](https://img.shields.io/badge/X-black.svg?logo=X&logoColor=white)](https://x.com/akkologluu)

# Deneyim: 

### HAVELSAN Web Developer Intern
*Ağustos 2023 - Eylül 2023*

### TURKCELL Student Traniee
*Mart 2024 - Devam Ediyor*

# Hakkımda:

Merhaba, ben Abdullah. Bilgisayar Mühendisliği son sınıf öğrencisiyim ve ikinci zorunlu stajım için yeni bir fırsat arayışındayım. İlk staj deneyimimi Havelsan'da web geliştirici stajyeri olarak geçirdim ve bu süreçte teknik anlamda önemli kazanımlar elde ettim. Ayrıca, kurumsal bir ortamda çalışma deneyimi edinmek benim için oldukça değerli oldu.

Şu an MERN Stack projeleri üzerinde çalışıyorum ve Frontend Developer veya Backend Developer rollerinde yer almayı istiyorum. Ayrıca, blockchain teknolojilerine olan ilgim ve bu alandaki yeteneklerimi geliştirme çabalarım devam ediyor. Solidity dilini öğreniyorum ve web3.js kütüphanesi ile projeler geliştiriyorum. Bitirme projem, MERN Stack ile birlikte blockchain teknolojilerini kullanarak geliştirdiğim bir proje üzerine odaklanıyor.

Yeni bir staj fırsatıyla birlikte hem teknik becerilerimi artırmak hem de kurumsal ortamda daha fazla deneyim kazanmak istiyorum. İlginiz için teşekkür eder, olumlu bir geri dönüş almayı umarım.

# Projeler:

- ### Euro 2024 Guess Game
Bu uygulama, kullanıcıların giriş yaptıktan sonra grup aşamalarından Euro 2024 finaline kadar olan yolculukta tahminler yapmalarına ve bu tahminleri turnuva bittikten sonra kaydedip kontrol etmelerine olanak sağlayan bir tahmin oyunudur. Kullanıcılar tahminlerini paylaşabilir ve diğer kullanıcıların tahminlerine bakabilirler.
[CODE](https://github.com/akkologlu/euro-2024-predict)

- ### Decentralized Auth System
Bu sistem, kullanıcıları merkezi bir doğrulama sisteminden kurtarıyor ve kripto cüzdanlarıyla giriş yapmalarına olanak tanıyor. Ayrıca oturum açarken ilgili akıllı sözleşmeden rol kontrolü gerçekleştirir ve rol bazlı olarak routelara erişimi kontrol eder.
[CODE](https://github.com/akkologlu/decentralized-auth-system)

- ### Digital Vehicle License
Dijital Araç Ruhsatı, araç kayıtlarının yönetilme ve erişilme biçiminde devrim yaratmayı amaçlayan bir projedir. Blok zinciri teknolojisini kullanarak güvenli, şeffaf ve değiştirilemez kayıt tutmayı mümkün kılmaktadır. Özellikler arasında kaza kayıtları, bakım ve muayene kayıtları, geçmiş sahiplik bilgileri ve araç parçalarının durumunun izlenmesi yer almaktadır.
[DEMO](https://digitalvehiclelicense.netlify.app/) [CODE](https://github.com/akkologlu/DigitalVehicleLicense)

- ### Intership Task
Havelsan'daki stajım sırasında bir dijital dönüşüm projesine katkıda bulundum. Bir şirketin personel ve proje verilerini bir yönetim paneli üzerinden görüntülemesini ve düzenlemesini sağlayan bir sistem geliştirdim. Bu yönetim panelinde, projelerin detaylarını listeleyen bir arayüz tasarladım ve veri erişimini iyileştirmek için sıralama, filtreleme ve dosya yükleme özellikleri ekledim. Ayrıca yeni projeler eklemek için çok adımlı bir form oluşturdum. Projede karşılaştığım zorluklar arasında FormData fonksiyonunu kullanarak dosya yükleme ve profil fotoğrafı yükleme işlemleri vardı. Giriş sayfasını ve kimlik doğrulama sürecini projeye entegre etmek de kendi zorluklarıyla birlikte geldi, ancak bu adımları izleyerek başarıyla tamamladım. Bu projede edindiğim deneyimlerin gelecekteki profesyonel hayatımda önemli bir temel oluşturacağına inanıyorum.

- ### 2000 Words
2000Words, İngilizce dilindeki temel 2000 kelimeyi öğrenmek için pratik ve interaktif bir eğitim platformudur. Kullanıcılar akıllı flash kartlar ile bilmedikleri kelimeleri kolayca öğrenebilir ve pratik yapabilirler. Dil becerilerinizi zenginleştirin ve 2000 kelimenin gücü ile iletişiminizi daha etkili hale getirin.
[CODE](https://github.com/akkologlu/2000Words)

- ### Cover Letter Generator
Bu proje, kullanıcılara hızlı ve etkili bir şekilde önyazı oluşturma fırsatı sunan bir yazılım uygulaması geliştirmeyi amaçlamaktadır. Kullanıcılar, kişisel bilgilerini ve başvurdukları pozisyonla ilgili ayrıntıları girdikten sonra, yapay zeka tarafından oluşturulan profesyonelce hazırlanmış bir ön yazıya sahip olacaklar.
[DEMO](https://coverletteraigenerator.netlify.app/) [CODE](https://github.com/akkologlu/coverLetterAI)

- ### Watchlyst
TMDB API'sini kullanan Watchlyst, kullanıcıların kişiselleştirilmiş izleme listelerini kolayca oluşturmasına ve yönetmesine olanak tanıyan React tabanlı bir platformdur. En yeni ve popüler filmleri keşfedin, belirli başlıkları arayın ve tek tek film sayfalarında ayrıntılı bilgilere erişin.  İzledikten sonra filmleri izleme listenizden zahmetsizce kaldırın. Film keşfini ve kullanıcı kontrolünü kolaylaştıran Watchlyst, özlü ve kullanıcı dostu bir deneyim sunar.
[DEMO](https://watchlyst.netlify.app/) [CODE](https://github.com/akkologlu/watchlist)

- ### SkyHub
Bu projede, kullanıcıların konum bilgilerinin yanı sıra mevcut hava durumu sayfasını sorunsuz bir şekilde görüntülemelerine olanak tanıyan kullanıcı dostu bir web sitesi hazırlanmıştır. Arama sayfası, istenen herhangi bir konum için hava durumunun zahmetsizce kontrol edilmesini sağlar. Daha da önemlisi, şehirler favorilere eklenerek tercih edilen konumlar için hava durumu bilgilerinin takibi kolaylaştırılabilmektedir.
[DEMO](https://skyhub.netlify.app/) [CODE](https://github.com/akkologlu/SkyHub)

- ### FlyPqs
FlyPqs, kullanıcıların belirli tarihlerdeki ve havalimanlarındaki uçuşları aramasını ve listelemesini sağlayan dinamik bir web uygulamasıdır. İlk kullanımda sunulan sezgisel arayüzü ve görsel animasyonu ile öne çıkmaktadır. Uçuş bilgileri kolay sıralama ve filtreleme özellikleri ile kullanıcı deneyimini ön planda tutarak sergileniyor.
[DEMO](https://flypqs.netlify.app/) [CODE](https://github.com/akkologlu/FlightSearchApplication)

## Teknik:
- ## Frontend: ![HTML5](https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white) ![CSS3](https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white) ![JavaScript](https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E) ![MUI](https://img.shields.io/badge/MUI-%230081CB.svg?style=for-the-badge&logo=mui&logoColor=white) ![React](https://img.shields.io/badge/react-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB)  ![Redux](https://img.shields.io/badge/redux-%23593d88.svg?style=for-the-badge&logo=redux&logoColor=white)  ![TailwindCSS](https://img.shields.io/badge/tailwindcss-%2338B2AC.svg?style=for-the-badge&logo=tailwind-css&logoColor=white)
- ## Backend: ![NodeJS](https://img.shields.io/badge/node.js-6DA55F?style=for-the-badge&logo=node.js&logoColor=white) ![Express.js](https://img.shields.io/badge/express.js-%23404d59.svg?style=for-the-badge&logo=express&logoColor=%2361DAFB) ![JWT](https://img.shields.io/badge/JWT-black?style=for-the-badge&logo=JSON%20web%20tokens) ![Postman](https://img.shields.io/badge/Postman-FF6C37?style=for-the-badge&logo=postman&logoColor=white)
- ## Database: ![MongoDB](https://img.shields.io/badge/MongoDB-%234ea94b.svg?style=for-the-badge&logo=mongodb&logoColor=white) ![MySQL](https://img.shields.io/badge/mysql-%2300000f.svg?style=for-the-badge&logo=mysql&logoColor=white) 
- ## Blockchain: ![Solidity](https://img.shields.io/badge/Solidity-%23363636.svg?style=for-the-badge&logo=solidity&logoColor=white) ![Web3.js](https://img.shields.io/badge/web3.js-F16822?style=for-the-badge&logo=web3.js&logoColor=white) ![Remix](https://img.shields.io/badge/remix-%23000.svg?style=for-the-badge&logo=remix&logoColor=white)

**Comment by VB10** [comment]
Merhaba @akkologlu, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @akkologlu, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @akkologlu, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
