### ISSUE TITLE
Hakan YAVAŞ [backend,frontend,database][uzaktan,yüzyüze][zorunlu][2 hafta]

### ISSUE THREAD

**Issue by hakanyavaseng** [VB10/staj_2024#109]
### Kişisel:

- **Ad Soyad:** Hakan YAVAŞ
- **Okul:** Eskişehir Osmangazi Üniversitesi
- **Sınıf:** 3. Sınıf
- **CV:** (https://drive.google.com/file/d/1DTk4KLmAAF_vGGKF7Kl2iqlLAvmQ1nBg/view?usp=sharing)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Hakkımda

Merhaba, ben Hakan YAVAŞ. Eskişehir Osmangazi Üniversitesi, Bilgisayar Mühendisliği 3. sınıf öğrencisiyim. Halihazırda kendimi full stack alanında geliştiriyorum. Kullandığım teknolojiler .NET ve Angular. Halihazırda 8 Temmuz-19 Ağustos arasında 30 günlük stajım mevcut. Zorunlu stajımda eksik kalan 10 gün (2 hafta) için staj arayışındayım. Staj sonrası da uzun dönemli stajyer olarak çalışmak isterim.

### Sunucu Sağlığı İzleme Uygulaması: https://github.com/hakanyavaseng/HeartbeatApp

- **Öğrenmekte Olduğum Diller ve Teknolojiler:** C#,  .NET, Entity Framework, SignalR, RabbitMQ, Database Management Systems (SQL), TypeScript, JS, Angular

**Comment by VB10** [comment]
Merhaba @hakanyavaseng, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @hakanyavaseng, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @hakanyavaseng, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
