### ISSUE TITLE
Jerfi Ali Uçar [backend][Yüzyüze, uzaktan][Zorunlu][4hafta]

### ISSUE THREAD

**Issue by JerfiAliUcar** [VB10/staj_2024#11]
### Kişisel:

- **Ad Soyad:Jerfi Ali Uçar**
- **Okul:İstanbul Ticaret Üniversitesi**
- **Sınıf:2. Sınıf**
- **CV: https://drive.google.com/file/d/1ha7mLuf3lQjsJIpUSQDix27bvXi4kEB2/view?usp=drivesdk
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen): Bilgisayar mühendisliği 2. Sınıf öğrencisiyim zorunlu stajım için staj yeri arıyorum. İstanbul'da yaşıyorum

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları): https://github.com/JerfiAliUcar

- **İlgilendiklerim (diller, frameworkler vs): Asp . Net Core Mvc,Java,Springboot

**Comment by VB10** [comment]
Merhaba @JerfiAliUcar, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
