### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by fatosozolcar** [VB10/staj_2024#112]
### Kişisel:

- **Ad Soyad:FATOŞ ÖZOLCAR
- **Okul:Nişantaşı Üniversitesi
- **Sınıf:4
- **CV:
[FAtoş özolcar.pdf](https://github.com/VB10/staj_2024/files/14100604/FAtos.ozolcar.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Merhaba, ben Fatoş Özolcar. Nişantaşı Üniversitesi Bilgisayar Mühendisliği Bölümünde 4. sınıf öğrencisiyim. Eğitim hayatım boyunca,özellikle veri yapıları ve algoritmalar konularında derinlemesine çalıştım.Bilgisayar mühendisliği derslerinin yanı sıra, kendi başıma Java, C, C++ gibi programlama dillerini öğrendim ve orta seviye projeler geliştirdim. Bu projeler, yazılım geliştirme konusundaki yeteneklerimi artırmama ve teorik bilgilerimi pratik uygulamalara dönüştürmeme yardımcı oldu.
İngilizce becerilerim intermediate düzeydedir ve sürekli olarak geliştirmekteyim.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):Java, C/C++, Algoritmalar

**Comment by VB10** [comment]
Merhaba @fatosozolcar, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
