### ISSUE TITLE
Hamdi Eren Kuşcalı [mobile][yüzyüze,uzaktan][zorunlu][6hafta]

### ISSUE THREAD

**Issue by Kscl1** [VB10/staj_2024#117]
### Kişisel:

- **Ad Soyad:** Hamdi Eren Kuşcalı
- **Okul:** Karamanoğlu Mehmetbey Üniversitesi - Bilgisayar Mühendisliği
- **Sınıf:** 3. Sınıf
- **CV:** [CV'im](https://drive.google.com/file/d/1zkJRo2p21W3w26a1gKUUv7jHiuZwIyBp/view?usp=sharing)
- **Linkedin:** [Hamdi Eren Kuşcalı](https://www.linkedin.com/in/hamdi-eren-kuscali/)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Hakkımda:
Karamanoğlu Mehmetbey Üniversitesi Bilgisayar Mühendisliği bölümünde üçüncü sınıf öğrencisiyim. Android ve yapay zeka alanlarında deneyimli ve hevesli bir öğrenciyim.

Android uygulama geliştirme konusunda Kotlin dili ile çeşitli projeler yaptım ve GDSC Karamanoğlu Mehmetbey topluluğunda teknik ekip sorumlusu olarak görev yapıyorum. Yapay zeka alanında da Teknofest Serbest Görev İHA kategorisinde, tarım arazilerinin hassas ilaçlama, su ve gübre ihtiyacını tamamen otonom bir şekilde belirleyen ve bunları Telegram aracılığıyla bildiren bir projede ekip olarak çalıştım.

30 günlük zorunlu stajım sonunda yarı zamanlı olarak çalışabilirim.

### Teknik 

- **İlgilendiklerim:**  Mobil Uygulama Geliştirme, Android Uygulama Geliştirme, Kotlin, Kotlin Multiplatform

**Comment by VB10** [comment]
Merhaba @Kscl1, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
