### ISSUE TITLE
Taha Metin[game,qa,backend][yüzyüze,uzaktan][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by TahaMetin** [VB10/staj_2024#127]
### Kişisel:

- **Ad Soyad: Muhammed Taha Metin**
- **Okul: Kocaeli Üniversitesi bilgisayar mühendisliği**
- **Sınıf: tüm derslerimi verdim stajım kaldı sadece**
- **CV: Portfolyomu <a href="tahametin.com">tahametin.com</a>  üzerinden görebilirsiniz** 
- **Sigorta Okul Karşılıyor** (Evet): 

https://tahametin.com/
https://www.linkedin.com/in/taha-metin/
https://github.com/TahaMetin

**Comment by VB10** [comment]
Merhaba @TahaMetin, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @TahaMetin, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @TahaMetin
