### ISSUE TITLE
Onur Çetin [mobile,backend][uzaktan][zorunlu][6hafta]

### ISSUE THREAD

**Issue by onurcetindev** [VB10/staj_2024#134]
### Kişisel:

- **Ad Soyad: Onur Çetin
- **Okul: Akdeniz Üniversitesi
- **Sınıf: 3. Sınıf
- **CV: https://drive.google.com/file/d/1TCn2PIYSMqa7mKTZt-FSwaO4net7lrLM/view?usp=sharing
- **Sigorta Okul Karşılıyor: Evet

### Teknik (Örnek projeler, linkleri ve detayları)
-İlk stajımda Antalya'da kullanılan bir scooter uygulaması olan GEZ uygulamasında bazı katkılarım oldu. (Flutter)
-Serbest çalıştığım bir şirkette Nova Wood- Hiker App adında bir Dağ Yürüyüşü uygulamasının haritalama kısmını ben yaptım.(Flutter)
-Kendim ise bazı ufak uygulamalarımı github sayfamdan bulabilirsiniz.

- **İlgilendiklerim (diller, frameworkler vs):
-Microsoft Azure
-Java
-Flutter
-Linux

**Comment by VB10** [comment]
Merhaba @10urcetin, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
