### ISSUE TITLE
Haktan Can Taşkıran [Mobile][Uzaktan veya İstanbul][Gönüllü][6 hafta]

### ISSUE THREAD

**Issue by hctaskiran** [VB10/staj_2024#137]
### Kişisel:

- **Ad Soyad: Haktan Can Taşkıran**
- **Okul: Erciyes Üniversitesi**
- **Sınıf: 4 (Son)**
- **CV:**  https://drive.google.com/file/d/1ELPMOBJhXxVqM5JzRJ7L3GRdhQ6hiPdN/view?usp=sharing 
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Hayır

### Kendin Hakkında (kendini anlatmak istersen):

Erciyes Üniversitesi Rus Dili ve Edebiyatı bölümü son sınıf öğrencisiyim. Daha önceden Unity kullanarak C# ile oyun geliştirmeyle ve yazılıma başlangıç olarak Python ile giriş yaparak ilk adımlarımı attım. Yazılım hayatımda kırılma noktam ise geçtiğimiz sene mobil uygulama geliştirme dünyasına Flutter ile iOS uygulama geliştirmeye giriş yaparak başladı. Mobil uygulama geliştirme alanında Swift ve Flutter için bootcamplere seçildim ve başarıyla bitirdim. Güncel olarak 1 adet bootcamp bitirme projem ve yakın zamanda App Store'a yayınlamış 'Apex Status' isimli bir uygulamam var. Flutter'da kendini geliştirmek istediğim için gönüllü olarak staj yapmak istiyorum. Şu an üniversitem gereği Kayseri'de ikamet etmekteyim fakat staj/iş için İstanbul'da ikamet edebilirim. Ek olarak yabancı dil öğrenmeyi severim. Anadilim dışında İngilizce ve Rusça'yı akıcı konuşabiliyorum.

https://www.linkedin.com/in/haktancantaskiran/

### Teknik (Örnek projeler, linkleri ve detayları)

**Bootcamp Bitirme Projesi**: https://github.com/hctaskiran/bootcamp_project
**Apex Status**: https://apps.apple.com/jo/app/apex-legends-status-mobile/id6475164467

- **İlgilendiklerim (diller, frameworkler vs):**
Flutter - Dart (Staj ve İş aradığım alan)
Swift

**Comment by VB10** [comment]
Merhaba @hctaskiran, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @hctaskiran, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @hctaskiran, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
