### ISSUE TITLE
Emre Can Erol [cyber-security][uzaktan, yüzyüze][gönüllü][4 hafta, 6 hafta]

### ISSUE THREAD

**Issue by emrerol** [VB10/staj_2024#138]
### Kişisel:

- **Ad Soyad: Emre Can Erol** 
- **Okul: Yalova Üniversitesi**
- **Sınıf: 4**
- **CV: https://drive.google.com/file/d/18zU-ZcBN8ntUNOiSUb_Fm4qfLH8Jbgau/view?usp=share_link** 

### Kişisel Bilgiler

Bilgisayar mühendisliği son sınıf öğrencisiyim. Dönem içi zorunlu staj yapma şansım olmadığı için gönüllü staj arayışındayım. Bir süredir siber güvenlik ile ilgili çalışmalar yaparak kendimi mavi takım için geliştiriyorum. Letsdefend üzerinden alarm incelemeleri, log analizleri yaptım. Splunk ile çalıştım. İstanbul ve Yalova içerisinde yüz yüze stajlara da gelebilirim.

### Teknik (Örnek projeler, linkleri ve detayları)

- **Javascript, Python, Wireshark, Splunk**

**Comment by VB10** [comment]
Merhaba @emrerol, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emrerol, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emrerol, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emrerol, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @emrerol
