### ISSUE TITLE
Ömer Öztürk [backend,frontend][uzaktan,yüzyüze][zorunlu][4hafta, 6hafta]

### ISSUE THREAD

**Issue by 1omerozturk** [VB10/staj_2024#143]
### Kişisel:

- **Ad Soyad:** **Ömer Öztürk**
- **Okul:** **Fırat Üniversitesi**
- **Sınıf:** **4**
- **CV:** [CV Gör](https://omerozturk.epizy.com/images/CV_last.pdf)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): **Evet**

### Kendin Hakkında (kendini anlatmak istersen):
Ben Fırat Üniversitesi Teknoloji Fakültesi Yazılım Mühendisliği bölümünde 4. sınıf öğrencisi Ömer Öztürk. **_Bahar dönemi zorunlu ve sigortam okulum tarafından karşılanacak 16 haftalık işyeri eğitimim_** bulunmaktadır. Bu dönem stajyer olarak ekibinizde yer alarak hem tecrübe kazanmayı hem de sizinle iş hayatına adım atmaya büyük bir istek ve heves duyuyorum.

Özgeçmişimi ekte bulabilirsiniz. Backend geliştirme konusunda kendimi sürekli olarak geliştiriyorum (Projelerime ve Çalışmalarıma ekte bulunan [CV](https://omerozturk.epizy.com/images/CV_last.pdf) 'mden ulaşabilirsiniz) ve bu alandaki bilgi ve becerilerimi pratikte uygulama fırsatı bulmak istiyorum. Sizinle çalışarak, sektördeki en iyi uygulamaları öğrenmek ve deneyimlemek istiyorum.

Sizinle çalışmak, benim için bir fırsat olacaktır. Şirketinizin yenilikçi ve başarılı projelerinde yer almak, hem kişisel hem de mesleki olarak gelişimime katkı sağlayacaktır. Amacım, staj sürecinin ardından şirketinizde kariyerime devam etmek ve uzun vadeli bir iş ilişkisi kurmaktır.

Başvurumu dikkate alacağınızı umarak, olumlu bir yanıtınızı bekliyorum. İlgilendiğiniz konuları veya gereksinimleri paylaşmanız durumunda, bunlara uygun olarak kendimi hazırlamak için istekliyim.

Saygılarımla,

### Teknik (Örnek projeler, linkleri ve detayları)
[Kişisel Web Sitem](https://omerozturk.epizy.com/)
[Github](https://github.com/1omerozturk)
[LinkedIn](https://www.linkedin.com/in/1omerozturk/)

- **İlgilendiklerim (diller, frameworkler vs):**
- **.Net**
- **NodeJS**
- **React**
- **Python**
- **MongoDB**
- **SQL**
- **Yapay Zeka**
- **Veri Bilimi**

**Comment by VB10** [comment]
Merhaba @1omerozturk, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @1omerozturk, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @1omerozturk, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @1omerozturk, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @1omerozturk, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
