### ISSUE TITLE
Emir Karaduran [FrontEnd][OFİS/REMOTE][Gönüllü][Uzun dönem]

### ISSUE THREAD

**Issue by emirkaraduran** [VB10/staj_2024#149]
### Kişisel:

- **Ad Soyad:** Emir Karaduran
- **Okul:** Istanbul Kültür üniversitesi
- **Sınıf:** Mezun
- **CV:** [Google Drive Linki veya pdf linki](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Hayır

### Kendin Hakkında (kendini anlatmak istersen):
Yıldız Teknik Üniversitesi Teknopark'ta FrontEnd Developer eğitimi alıyorum.Staj ile bilgimi ileri seviyeye taşımak istiyorum.
(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**
- React JavaScript

**Comment by VB10** [comment]
Merhaba @emirkaraduran, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emirkaraduran, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
