### ISSUE TITLE
MEHMET YAŞA [mobile, backend, frontend][yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by mehmetyasaa** [VB10/staj_2024#150]
### Kişisel:

- **Ad Soyad:** Mehmet Yaşa
- **Okul:** Kastamonu Üniversitesi
- **Sınıf:** 2.Sınıf 
- **CV:** [Mehmet Yaşa Cv](https://drive.google.com/file/d/13GwXpgKvXWH1-mKAduW5JVAMmTVT56uh/view?usp=sharing)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Yaz döneminde (1 Temmuz) zorunlu stajımı gerçekleştirmek amacıyla şirketinizde kendimi geliştirebileceğim bir fırsat arıyorum. Şirketinizin faaliyet gösterdiği alanda yaz dönemine kadar kendimi geliştirip projelerde aktif rol almak istiyorum. Şirketin konumu benim için önemli değil; ön planda olan, kendimi geliştirerek şirketinize katkı sağlayabileceğim bir ortam arayışındayım.

- **İlgilendiklerim (diller, frameworkler vs):**  Dart(Flutter), C# (MVC, Windows Forms, Console Applications)

**Comment by VB10** [comment]
Merhaba @mehmetyasaa, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
@mehmetyasaa okul ismi sanirim yanlis kalmis

**Comment by VB10** [comment]
Merhaba @mehmetyasaa, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
