### ISSUE TITLE
EMİR-KARADURAN ["FrontEnd"]["yüzyüze"]["Gönüllü"][ "4hafta", "6hafta"]

### ISSUE THREAD

**Issue by emirkaraduran** [VB10/staj_2024#151]
### Kişisel:

- **Ad Soyad:**Emir Karaduran
- **Okul:**İstanbul Kültür Üniversitesi
- **Sınıf:**Mezun
- **CV:** [Google Drive Linki veya pdf linki](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): - 

### Kendin Hakkında (kendini anlatmak istersen):
Yıldız Teknik Üniversitesi Teknopark'ta FrontEnd eğitimi alıyorum.Haftaiçi her gün staj için müsaitim.Kendimi geliştirmeye ve öğrenmeye açığım.
(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)
https://www.linkedin.com/in/emirkaraduran/
- **İlgilendiklerim (diller, frameworkler vs):**
React JavaScript

**Comment by VB10** [comment]
Merhaba @emirkaraduran, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emirkaraduran, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
