### ISSUE TITLE
AYŞE-AYDIN [FRONTEND-BACKEND][YÜZYÜZE][ZORUNLU][3 AY]

### ISSUE THREAD

**Issue by aysdny** [VB10/staj_2024#154]
### Kişisel:

- **Ad Soyad: Ayşe Aydın
- **Okul: Bolu Abant İzzet Baysal Üniversitesi
- **Sınıf:2
- **CV: https://www.canva.com/design/DAF7Z5UcoKI/7-ydr11eD_9ntQVBXDU3pg/view?utm_content=DAF7Z5UcoKI&utm_campaign=designshare&utm_medium=link&utm_source=editor
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet 

### Kendin Hakkında (kendini anlatmak istersen):
Ben Ayşe Aydın. Bilgisayar Programcılığı 2.  sınıf öğrencisiyim. Dönemlik stajım var ve bunu 2. dönem yapacağım.
Orta seviye ingilizceye sahibim. Cv'mde de bahsettiğim gibi çoğu yazılım dilini gördüm ve hakimim. ASP.NET ile internet sitesine ilgiliyim.
Staj yaptığım zaman diliminde de kendime birçok şey katmayı ve geliştirmeyi umuyorum.

### Teknik (Örnek projeler, linkleri ve detayları): phpMyAdmin, VSCode ve XAMPP kullanarak oluşturulan bir güzellik salonu web sitesi oluşturdum .
https://documentcloud.adobe.com/gsuiteintegration/index.html?state=%7B%22ids%22%3A%5B%221edHc1DYlvB638PkWj2m6_QvdFaYl2IZC%22%5D%2C%22action%22%3A%22open%22%2C%22userId%22%3A%22116432243165346691653%22%2C%22resourceKeys%22%3A%7B%7D%7D 

- **İlgilendiklerim (diller, frameworkler vs):**
SQL, C , C# , Java , Database-SQL Development , HTML , CSS , Python , JavaScript, ASP.NET , C++, Python, PHP

**Comment by VB10** [comment]
Merhaba @aysdny, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @aysdny, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @aysdny, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @aysdny, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
