### ISSUE TITLE
OSMAN EMRE ÖMÜRLÜ [mobile][uzaktan, yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by oemurlu** [VB10/staj_2024#165]
### Kişisel:

- **Ad Soyad: Osman Emre Ömürlü**
- **Okul: Pamukkale Üniversitesi**
- **Sınıf: 3. Sınıf (Bilgisayar Mühendisliği)**
- **CV:** [https://oemurlu.dev/assets/oemurlu-cv.pdf](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

1.5 yıldır iOS geliştirme alanında Swift ve UIKit ile ilgileniyorum. Algoritma çözme, OOP, SOLID ve clean code prensiplerinde bilgiliyim. Akıcı şekilde İngilizce konuşabiliyorum, teknik ve soft yeteneklerimi her geçen gün geliştirmeye devam ediyorum. Yaptıklarımı Github hesabımda düzenli olarak paylaşıyorum. 30 günlük zorunlu stajım sonunda yarı veya tam zamanlı olarak çalışmak istiyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

5 adet projem var. 1 tanesi App Store'da. Resimleriyle birlikte [web sitemde](https://oemurlu.dev) aşağıda görebilir ve Github hesabımda Readme dosyasında detaylıca yaptığım açıklamalara bakabilirsiniz. Yine de kronolojik olarak tek tek kısaca açıklayacak olursam;

[Video Games (Github)](https://github.com/oemurlu/Video-Games-App-MVVM-ProgrammaticUI) : MVVM, programmatic UI, CoreData, memory management, URLSession, general network layer
[Dergice (App Store)](https://oemurlu.dev/assets/oemurlu-cv.pdf) : OneSignal, StoreKit, WKWebView
[Food Order (Github)](https://github.com/oemurlu/Food-Order-App-MVVM-Repository-Firebase) : MVVM, repository pattern, Firebase (Firestore, Authentication, Storage), Alamofire, generic network layer, KingFisher, Cocoapods
[Movie World (Github)](https://github.com/oemurlu/Movie-World-MVVM-MovieAPP) : MVVM, Firebase, Alamofire, generic network layer, PanModal
[Bazaar Bundle (Github)](https://github.com/oemurlu/BazaarBundle_E-Commerce-Shopping-App) : MVC, Firebase (FirebaseAuth, FirestoreDatabase, FirebaseStorage), Alamofire, SPM

- **İlgilendiklerim (diller, frameworkler vs):**

Swift, UIKit, MVC, MVVM, Programmatic UI, Firebase, Reactive Programming, SQL, CoreData, SwiftData, Generic network layer, URLSession, Alamofire, StoreKit, OneSignal, Cocoapods, SPM, Kingfisher ve SDWebImage tarzı 3. parti kütüphaneler.

**Comment by VB10** [comment]
Merhaba @oemurlu, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @oemurlu, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
