### ISSUE TITLE
Sinem Kadakal [Game][yüzyüze][zorunlu][4 hafta]

### ISSUE THREAD

**Issue by sinemkadakall** [VB10/staj_2024#166]
### Kişisel:

- **Ad Soyad:** Sinem Kadakal
- **Okul:**  Erciyes Üniversitesi
- **Sınıf:** 3.Sınıf
- **CV:** [CV Sinem Kadakal .pdf](https://github.com/VB10/staj_2024/files/14110784/CV.Sinem.Kadakal.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendin Hakkında (kendini anlatmak istersen):

Erciyes Üniversitesi Bilgisayar mühendisliği 3.sınıf öğrencisiyim.
Teknolojinin önemi oldukça büyük ve her geçen gün artmaya devam ediyor. Bir bilgisayar mühendisi adayı olarak bu alana büyük bir ilgim var. Kendimi tanıdıkça ilgi alanlarımı ve yeteneklerimi keşfediyorum ve bilgisayar alanına olan ilgim artıyor. Bu nedenle sürekli eğitimlere katılarak ve etkinliklere katılarak kendimi geliştirmeye çalışıyorum.

Hem bireysel hem de ekip içinde uyumlu çalışabilen biriyim. Kendimi sosyal, meraklı ve yaratıcı olarak tanımlayabilirim.

Şu anda kariyerimin oyun geliştirme üzerine olması gerektiğine karar verdim ve yaklaşık bir yıldır bu alanla ilgileniyorum. Kendim ve ekip arkadaşlarımla birlikte oyun projeleri geliştiriyoruz. Projelerimle çeşitli yarışmalara ve Bootcamp'lere katılıyorum. Yaptığım oyun Teknofest'te oyun teknolojileri kategorisinde birinci seçildi ve en iyi girişim olarak değerlendirildi. Bu başarıdan dolayı çok gururluyum.

Yaz ayında yapacağım stajımı bu alanda yapmak istiyorum. 

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**
-Unity Engine ,C#, SQL, Java, OOP

**Comment by VB10** [comment]
Merhaba @sinemkadakall, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @sinemkadakall, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @sinemkadakall, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @sinemkadakall, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @sinemkadakall, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
