### ISSUE TITLE
Musa-ÖZALP [mobile,backend,fronted][yüzyüze][zorunlu][14hafta]

### ISSUE THREAD

**Issue by musaozlpp** [VB10/staj_2024#173]
### Kişisel:

- **Ad Soyad:** Musa ÖZALP
- **Okul:** Bolu Abant İzzet Baysal Üniversitesi
- **Sınıf:**2.Sınıf
- **CV:** [Google Drive Linki veya pdf linki](#)
[CV Musa Özalp (1).pdf](https://github.com/VB10/staj_2024/files/14111956/CV.Musa.Ozalp.1.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendin Hakkında (kendini anlatmak istersen):
Merhaba ben Musa. Bolu Abant İzzet Baysal Üniversitesi Bilgisayar Programcılığı son sınıf öğrencisiyim. Zorunlu dönem stajı için staj yeri aramaktayım. Kendimi geliştirebilceğim, yeni bilgiler öğrenebileceğim, iş hayatımın sağlam bir basamağı olabilecek bir yer aramaktayım.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @musaozlpp, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @musaozlpp, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @musaozlpp, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
