### ISSUE TITLE
Furkan Melik Demiray [mobile][yüzyüze,uzaktan][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by FurkanMDemiray** [VB10/staj_2024#178]
### Kişisel:

- **Furkan Melik Demiray:**
- **Eskişehir Osmangazi Üniversitesi:**
- **Bilgisayar Mühendisliği 4. Sınıf:**
- **CV:** [https://drive.google.com/drive/folders/1Rx6m_5qB0lm4VxivEKbjfTLLSKTltWBm?usp=sharing](#)
- Sigorta Okul Karşılıyor:   Evet

### Kendin Hakkında (kendini anlatmak istersen):

2023 yılının yazından itibaren iOS developer olma yolunda ilerliyorum. Takip ettiğim bir eğitim kursu ile bu süreci gerçekleştiriyorum. Eğitim boyunca öğrendiklerimi uygulamalar yaparak github repoma yükledim. Swfit diline ve design patternlere yoğunlaşarak kendimi geliştirmeye çalışıyorum. iOS developer alanında bir staj arıyorum. Zorunlu staj sonrasında firma ile uzun dönem staj da yapmak isterim.
 
### Teknik (Örnek projeler, linkleri ve detayları)

- **Projelerim https://github.com/FurkanMDemiray?tab=repositories**
- **İlgilendiklerim : MVVM,Viper,Swift,Firebase,SwiftUI,Alamofire**

**Comment by VB10** [comment]
Merhaba @FurkanMDemiray, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @FurkanMDemiray, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @FurkanMDemiray, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @FurkanMDemiray, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
