### ISSUE TITLE
ÖmerFarukİlhan ["android"]["ankara"]["zorunlu"]["4hafta"]

### ISSUE THREAD

**Issue by omerilhNN** [VB10/staj_2024#179]
### Kişisel:

- **Ad Soyad** Ömer Faruk İlhan
- **Okul:** Gazi Üniversitesi
- **Sınıf:** 2.sınıf
- **CV:** 
[Ömer-Faruk-İlhan-FlowCV.pdf](https://github.com/VB10/staj_2024/files/14112294/Omer-Faruk-Ilhan-FlowCV.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
Ben Ömer Faruk İlhan, Gazi Üniversitesi Bilgisayar Mühendisliği bölümü 2.sınıf öğrencisiyim. Android uygulama geliştirmeyle alakalı MVVM mimarisi ve Retrofit, Firebase, Jetpack Compose, Dependency Injection gibi teknolojiler ile deneyimlerim oldu. Bu yaz stajımı sizin şirketinizin Ankara ofisinde, Android mobil geliştiricilik üzerine yapmak ve bu alanda kendimi geliştirmek istiyorum. Staj sonrasında da sizinle çalışmaya devam etmek ve yeni tecrübeler edinmeyi çok isterim.

### Teknik (Örnek projeler, linkleri ve detayları)
github sayfamdan ve CV'den projelerim hakkında detaylı bilgi edinebilirsiniz.

https://github.com/omerilhNN

file:///C:/Users/karak/OneDrive/Masaüstü/Ömer-Faruk-İlhan-FlowCV.pdf
- **İlgilendiklerim (diller, frameworkler vs):
Kotlin-AndroidStudio- Java- C# - C - Unity

**Comment by VB10** [comment]
Merhaba @omerilhNN, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
