### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by remolg** [VB10/staj_2024#183]
### Kişisel:

- **Ad Soyad: Sadık Ahmet Özdemir**
- **Okul: Açık Öğretim Fakültesi Web Tasarım**
- **Sınıf: 2. Sınıf**
- **CV:**  [sadikahmetozdemirCV.pdf](https://github.com/VB10/staj_2024/files/14113920/sadikahmetozdemirCV.pdf)
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Hayır

### Kendim Hakkımda:

Selamlar ben Sadık Ahmet Özdemir 21 yaşındayım Acunmedya Akademide front-end eğitimi aldım ve şu anda evde aktif olarak kendimi geliştirmekteyim anlaştığım 2 farkli firmaya ufak çaplı 2 tane web sitesi hazırlıyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

[Projeler](https://remolg-portfolio.netlify.app/)

- **İlgilendiklerim (diller, frameworkler vs):**
- HTML, CSS, JavaScript, React.js, Node.js, MySQL, Material UI, tailwinds

**Comment by VB10** [comment]
Merhaba @remolg, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @remolg, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @remolg, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
