### ISSUE TITLE
METEHAN AVCI [MOBİL] [UZAKTAN] [ZORUNLU] [6 HAFTA]

### ISSUE THREAD

**Issue by Dw1ed** [VB10/staj_2024#185]
### Kişisel:

- **Ad Soyad:Metehan Avcı
- **Okul:Bandırma Ünivesitesi bilgisayar programcılığı uzaktan eğitim
- **Sınıf:2
- **CV:** [Google Drive Linki veya pdf linki](https://docs.google.com/document/d/1k33b6vyjZlnKACCB32tiIA328LjSScFr/edit?usp=drive_link&ouid=104159080566967346673&rtpof=true&sd=true)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): 

### Kendin Hakkında (kendini anlatmak istersen):
Bilgisayar programcılığı 2.sınıf öğrencisi yaşadığı yerden dolayı yüzyüze şirketlere gidip başvuramadığım için burdan başvurmak istedim.
Mobil programlama tarafına merak salmış meraklı birisiyim.20 yaşındayım.
(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (Mobil tarafı ile alakalıyım Javascript,React-native ile ilgileniyorum.):**

**Comment by VB10** [comment]
Merhaba @Dw1ed, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
