### ISSUE TITLE
Serhat Şimşek [mobile][yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by srhtsimsek** [VB10/staj_2024#19]
deleted

**Comment by VB10** [comment]
Merhaba @srhtsimsek, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @srhtsimsek, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
