### ISSUE TITLE
Rifat Metehan GOKTAS [mobile,backend][yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by rmgoktas** [VB10/staj_2024#200]
Kişisel: 
Ad Soyad: Rifat Metehan GOKTAS
Okul: Selçuk Üniversitesi 
Sınıf: 3.Sınıf 
CV: https://drive.google.com/file/d/1naew9Angi8IGOfsv5NEXgNWidIIwx96n/view?usp=sharing
Sigorta Okul Karşılıyor: Evet 

Selçuk Üniversitesi Bilgisayar Mühendisliği 3.sınıf öğrencisiyim. Kendimi iOS alanında geliştirmekteyim. Yeni teknolojiler öğrenmeyi seviyorum. Yaptığım projeleri GitHub hesabımdan görebilirsiniz. Zorunlu 20 iş günü stajım mevcuttur. Ücret beklentim yok ve sigortamı okul karşılıyor.

**Comment by VB10** [comment]
Merhaba @rmgoktas, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @rmgoktas, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @rmgoktas, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
