### ISSUE TITLE
KERİM ŞENTRÜK [backend][yüzyüze][zorunlu, gönüllü][4hafta, 6hafta]

### ISSUE THREAD

**Issue by kerimsenturk5734** [VB10/staj_2024#202]
### Kişisel:

- **Ad Soyad:** Kerim Şentürk
- **Okul:** Kastamonu Üniversitesi Bilgisayar Mühendisliği
- **Sınıf:** 4
- **CV:** [CV](https://drive.google.com/file/d/1uDzpYeh5R3pkuGwJWS89qyRSJP9Tp5ew/view)
- **Sigorta Okul Karşılıyor** : Evet

### Kendin Hakkında (kendini anlatmak istersen):

Merhaba adım Kerim. Kastamonu Üniversites Bilgisayar Mühendisliği 4. sınıf öğrencisiyim.  22 yaşındayım ve İstanbul'da yaşıyorum.  Ana alanım olarak backend web developing üzerine ilerledim. Bu alanda java, spring boot ve mysql teknolojileri ile sık çalışıyorum. Yaptıklarımı bir nebze daha kullanışlı hale getirmek için az çok react.js ile ui tasarımı yapıyorum. Aynı zamanda Java SE'nin API'ı üzerine egzersizler yapıp dile daha çok hakim olmayı çalışıyor ve bu konuları medium hesabımda notlarımla açıklamaya çalışıyorum. İngilizce seviyem speaking olarak B1 listening olarak B2 düzeyde. Polonya'da bu dönem(2023-2024 güz dönemi) içinde yaptığım Erasmus hareketliliğimin de buna katkısı oldu. Geçtiğimiz yıllarda yaz stajlarım için birçok yere başvuru yapmama rağmen kabul alamadım bu nedenle 20'şer günlük iki yaz stajımı yapamadım. Önümüzdeki dönem de bulunan uzun stajımı da bu yaz stajlarımı yapamadığımdan üniversite müfredatı açısından mümkün değil. Bu yüzden mümkünse 2024 yılı boyunca gönüllü de dahil olmak üzere iki yaz stajımı + bir uzun dönem stajımı yapmak istiyorum. Aksi takdirde bölümümden mezun olmam tüm derslerimi tamamlamama rağmen stajlarım nedeniyle uzayacak.  (<i>Mümkünse İstanbul içi önceliğimdir</i>)

### Teknik (Örnek projeler, linkleri ve detayları)
-  [**Visual-Data-Struct**](https://github.com/kerimsenturk5734/visual-data-structure)
Veri yapılarını öğretmek ve görselleştirerek uygulanmasını sağlamak amacıyla yapılmış bir web uygulaması. Java , spring boot, react, docker, mysql, d3.js teknolojileri kulanılmıştır. Üniversite 3. sınıf projesi olarak yapılmıştır.
- [**Lab-Report**](https://github.com/kerimsenturk5734/lab-report)
Bir hastanede doktor, hasta ve laborant üçlüsü arasında bir bilgi yönetim sistemi kuran bu uygulama doktorların hastalarını takip etmesine, laborantların test sonuçlarını takip etmesine ve hastaların kendi hastalıklarını,bunlar hakkındaki teşhis ve patoloji raporlarını takip edebilmesini sağlayan bir web uygulamasıdır. Java, spring boot, react, mysql, docker teknolojileri kullanılmıştır Üniversite 4.sınıf projesi olarak yapılmıştır.
- [**Image-Proccessing-Tool**](https://github.com/kerimsenturk5734/Image-Processing-Tool)
Yine isminde de anlaşılabildiği gibi bu uygulama resim işlemek için Java ile herhangi bir Image Processing kütüphanesi kullanılmadan masaüstü uygulamas olarak geliştirilmiştir. 3. sınıf Görüntü İşleme dersi için geliştirilmiştir.
- [**Library-Management**](https://github.com/kerimsenturk5734/Library-Management)
Her yazılım geliştircisi için başlangıç projesi olan kütüphane yönetim sistemi benim de 2. sınıfta yapmış olduğum bir projeydi. Bu projede C#, MsSQL, Windows Form teknolojilerine kullanarak bir kütüphanede kitap envanterinin takip edilmesi ve öğrencilere belirli  sürelerle ödünç kitap verilmesi gibi işlemler yapılarak masaüstü uygulaması geliştirilmiştir
- [**Bookorrow**](https://github.com/kerimsenturk5734/Bookorrow)
Bu proje kitaplar için bir takas uygulaması olup kitaba karşılık sadece kitap alıp satabildiğiniz bir mobil uygulamadır.  2. sınıf mobil programlama dersi projesi olarak Java, Firebase teknolojileri ile geliştirilmiştir.
- [**App-Live-Currency**](https://github.com/kerimsenturk5734/App-Live-Currency)
İsminden de anlaşılacağı gibi güncel olarak döviz kurlarını api yardımı ile gösterebildiğimiz ve bu dövizlerden istediğimizi kaydedebildiğimiz bir mobil uygulamadır. Kotlin, RoomDB, Retrofit teknolojileri kullanarak geliştirilmiştir. 4. sınıf proje dersi için geliştirilmiştir. Derslerimden dolayı henüz README oluşturamadım en kısa sürede ekleyeceğim.

- **İlgilendiklerim (diller, frameworkler vs):**
Java, Spring Boot, MySQL, Git-Github-Gitflow, Go, Docker, Operating Systems, Software Architecture

**Comment by VB10** [comment]
Merhaba @kerimsenturk5734, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @kerimsenturk5734, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @kerimsenturk5734, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
