### ISSUE TITLE
Alper Demir [fullstack][uzaktan,yüzyüze][zorunlu][3ay]

### ISSUE THREAD

**Issue by alperdemr** [VB10/staj_2024#228]
### Kişisel:

- **Ad Soyad: Alper Demir
- **Okul: Karadeniz Teknik Üniversitesi
- **Sınıf: 4
- **CV: [Google Drive Linki veya pdf linki](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Karadeniz Teknik Üniversitesi Bilgisayar Mühendisliği 4. sınıf öğrencisiyim. Next.js ile fullstack web uygulamaları geliştiriyorum. 3-6 ay arası staj tekliflerine açığım.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):Typescript, Tailwindcss, Postgres, Next.js

**Comment by VB10** [comment]
Merhaba @alperdemr, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
