### ISSUE TITLE
AD-SOYAD ["back-end","front-end","data-science"]["uzaktan", "yüzyüze"]["zorunlu"]["4hafta", "6hafta"]

### ISSUE THREAD

**Issue by ezgiaydin** [VB10/staj_2024#230]
### Kişisel:

- **Ad Soyad:Ezgi Aydın**
- **Okul: İstanbul Arel Üniversitesi**
- **Sınıf:4**
- **CV:** [Google Drive Linki veya pdf linki](https://drive.google.com/file/d/1OeEldTh1ie-mMLWfcVNULwgKcl7IuHYm/view?usp=sharing)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): EVET

### Kendin Hakkında (kendini anlatmak istersen):

Merhaba, ben Ezgi, Arel Üniversitesi'nin Bilgisayar Mühendisliği bölümünde 4. sınıf öğrencisiyim. Eğitimim boyunca edindiğim dil becerilerini, front-end ve back-end geliştirme alanlarında derinleştirmek ve eğer mümkünse data-science üzerine kariyer yapmak istiyorum. İlgili kurslar ve projelerle bu alanlardaki yeteneklerimi geliştirmiş bulunmaktayım. Öğrenmeye ve yeni projelere katılmaya her zaman istekliyim. 

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs): Javascript, HTML, CSS, Bootstrap, Figma, Angular, MS SQL, Python ve Java **

**Comment by VB10** [comment]
Merhaba @ezgiaydin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ezgiaydin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
