### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by ezgiaydin** [VB10/staj_2024#233]
### Kişisel:

- **Ad Soyad:**
- **Okul:**
- **Sınıf:**
- **CV:** [Google Drive Linki veya pdf linki](#https://drive.google.com/file/d/1OeEldTh1ie-mMLWfcVNULwgKcl7IuHYm/view?usp=drive_link)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): 

### Kendin Hakkında (kendini anlatmak istersen):

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @ezgiaydin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
