### ISSUE TITLE
Enes Ceylan [frontend, backend][yüzyüze, uzaktan][gönüllü][6hafta, 4hafta]

### ISSUE THREAD

**Issue by MedusaCollins** [VB10/staj_2024#235]
### Kişisel Bilgiler:

- **Ad Soyad:** Enes Ceylan
- **Okul:** Atlas Üniversitesi(_İstanbul_)
- **Sınıf:** 1. Sınıf(_Bilgisayar Programcılığı_)
- **CV:** [CV](https://docs.google.com/document/d/1E8zWQYrq0hiRmaWFu03SC-4N0A_-qQL-7ckbO0hGX0k/edit?usp=sharing)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Hayır

### Ben Kimim:

**Full Stack Web Developer** olma yolunda bilgi ve becerilerimi artırmak için sürekli çaba sarf eden biriyim. Bu sebepten neredeyse her gün kendime zaman yaratıp bir şeyler geliştirmeye çalışıyorum.

### Örnek Projeler:
**[secondChanges](https://github.com/MedusaCollins/secondChanges)** : "secondChances", MERN stack kullanarak kendimi test etmek amacıyla oluşturduğum ikinci el alım ve satım platformunun bir demosudur; kullanıcıların istediği gibi hesap oluşturabilmesi, ürün ekleyebilmesi ve her ne kadar demo olsada gerçek bir ürüne yaklaşması için eklediğim iyzico servisi sayesinde kredi kartı(Tabi ki demo olduğu için bunu iyziconun test kartları ile sınırlandırdım) ile alışveriş yapabilme gibi özelliklere sahip.

**[Discord Clone](https://github.com/MedusaCollins/discord-clone)**: Adındanda anlaşılabileceği gibi bir discord klonudur, kullanıcıların google ile giriş yapabilirler, kendi sunucularını oluşturabilir, arkadaşlarını davet edebilir, sunucuyu özelleştirebilir/silebilir, birbirleri ile anlık olarak sohbet alanı üzerinden iletişim kurabilir/fotoğraf gönderebilirler.

**[AlgoRiddle](https://github.com/MedusaCollins/AlgoRiddle)**: Daha yeni başladığım bir proje olan algoRiddle her gün çözülmesi için algoritma sorusu veren açık kaynaklı bir projedir. Sorular görsel olarak verildiği için yazılım bilgisi gerektirmez ve bu sayede yeni başlayan kişiler için birebirdir.(Projeye yeni başladığım için readme kısmı şu anda yok)

### **💻 Tech Stack:**
- Frontend: ![HTML5](https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white) ![CSS3](https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white) ![TailwindCSS](https://img.shields.io/badge/tailwindcss-%2338B2AC.svg?style=for-the-badge&logo=tailwind-css&logoColor=white) ![Bootstrap](https://img.shields.io/badge/bootstrap-%238511FA.svg?style=for-the-badge&logo=bootstrap&logoColor=white) ![JavaScript](https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E) ![React](https://img.shields.io/badge/react-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB)
- Backend: ![NodeJS](https://img.shields.io/badge/node.js-6DA55F?style=for-the-badge&logo=node.js&logoColor=white) ![Express.js](https://img.shields.io/badge/express.js-%23404d59.svg?style=for-the-badge&logo=express&logoColor=%2361DAFB) ![Python](https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54)
- Databases: ![MongoDB](https://img.shields.io/badge/MongoDB-%234ea94b.svg?style=for-the-badge&logo=mongodb&logoColor=white)
- Other Tools: ![Git](https://img.shields.io/badge/git-%23F05033.svg?style=for-the-badge&logo=git&logoColor=white) ![GitHub](https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white) ![Socket.io](https://img.shields.io/badge/Socket.io-black?style=for-the-badge&logo=socket.io&badgeColor=010101) ![Linux](https://img.shields.io/badge/Linux-FCC624?style=for-the-badge&logo=linux&logoColor=black)

**Comment by VB10** [comment]
Merhaba @MedusaCollins, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @MedusaCollins, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
