### ISSUE TITLE
YUSUF AKYÜZ [mobile,backend][yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by YusufAkyuz** [VB10/staj_2024#240]
### Kişisel:

- Yusuf Akyüz
- Ankara Yıldırım Beyazıt Üniveristesi
- 2.sınıf
- [CV](https://drive.google.com/file/d/1TIEqKXDXJtGriLfeETDHJ6i56F52Viex/view?usp=drive_link)
- Sigorta Okul Karşılıyor:Evet 

Merhaba,

Ben, Yusuf, şu anda Bilgisayar Mühendisliği 2. sınıf öğrencisiyim. Özellikle Java ve C++ dillerinde Nesne Yönelimli Programlama (OOP) konularında deneyim sahibiyim. Ayrıca, Flutter frameworkü ile uygulamalar geliştirme konusunda da aktif bir şekilde çalışmaktayım. Temel düzeyde SQL bilgisine hakimim. Firebase daha önce uygulamalarıma entegrasyonu için kullandım.

Daha önce Java ile geliştirdiğim uygulamalarımı GitHub adresimde inceleyebilirsiniz. Bu projeler, hem dil bilgim hem de problem çözme yeteneklerim konusundaki becerilerimi sergilemektedir.

Stajyer olarak sizinle çalışmak, bu alandaki bilgi ve becerilerimi geliştirmek, gerçek dünya projelerine katkıda bulunmak ve ekibinizle birlikte yeni şeyler öğrenmek istiyorum. Sizlerle bir araya gelerek bu alandaki yeteneklerimi daha da ilerletmek ve katkı sağlamak için heyecanlıyım.

İlginiz için teşekkür eder, başvurumun olumlu bir şekilde değerlendirilmesini umarım.

Saygılarımla,
Yusuf

[Social Media App ](https://github.com/YusufAkyuz/CShareApp)
[Note Recorder App](https://github.com/YusufAkyuz/NoteRecorder)
[Flappy Bird Game](https://github.com/YusufAkyuz/SurvivorBird)
[Bus Ticket System](https://github.com/YusufAkyuz/BusTicketSystem)

- İlgilendiklerim : Flutter, Java, C++, Python

**Comment by VB10** [comment]
Merhaba @YusufAkyuz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @YusufAkyuz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @YusufAkyuz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @YusufAkyuz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @YusufAkyuz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @YusufAkyuz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
