### ISSUE TITLE
Doğa SAÇIKARA [mobile, frontend][yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by dogasac** [VB10/staj_2024#247]
### Kişisel:

- **Ad Soyad:Doğa SAÇIKARA
- **Okul: Yaşar Üniversitesi
- **Sınıf: 3 
- **CV:
[CV-Doğa Saçıkara.pdf](https://github.com/VB10/staj_2024/files/14152678/CV-Doga.Sacikara.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @dogasac, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
