### ISSUE TITLE
Koray Özgür [backend,data-science][yüzyüze,uzaktan][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by koozgur** [VB10/staj_2024#249]
## Kişisel:

- Ad soyad: Koray Özgür
- Okul: Orta Doğu Teknik Üniversitesi
- Sınıf: 3
- CV: https://drive.google.com/file/d/1QefTsspKYKt4j_fdZcmya9SbvstIG4AR/view?usp=sharing
- Sigorta Okul Karşılıyor: Evet

## Kendin Hakkında (kendini anlatmak istersen):

ODTÜ Bilgisayar Mühendisliği 3. sınıf öğrencisiyim.  Dönem not ortalamam 3.88.  Yazın yapacağım zorunlu staj için kendimi geliştirebileceğim ve katkı sağlayabileceğim tercihen backend veya data science alanında bir staj arıyorum.  Deeplearning AI'ın Machine Learning Specialization ve Neural Networks kurslarını tamamladım ve TUBİTAK BİLGEM Java Bootcampine katıldım. C++, Java ve Python ile projeler yaptım.

## Teknik (Örnek projeler, linkleri ve detayları)
projelerin linki: github.com/koozgur

### UDP ile veri aktarımı soket uygulaması
- UDP kullanarak TCP'den daha hızlı ve güvenilir, paketlerin daha az bozularak, daha az kayıpla ve daha az gecikmeyle doğru sırayla ileten güvenilir ve pipelined  veri aktarım servisi oluşturdum.
- Docker ile konteynırlaştırıp bazı performans testleri ile test ettim.
 ### Java tabanlı MySQL Veritabanı Yönetim Sistemi
- Java ve JDBC kullanarak bir MySQL veritabanıyla etkileşimde bulunmak üzere bir veritabanı sistemi tasarladım ve uyguladım.
- Veritabanı tablolarını oluşturdum, ilgili veriyle doldurdum ve değerli içgörüler elde etmek için karmaşık sorguları gerçekleştirdim.
- Veritabanı bağlantısı, sorgu optimizasyonu ve Java arayüzü uygulama konusunda pratik deneyim kazandım.

### Java  B+ Tree
- Verimli sıralama, ekleme, silme ve veri çekme operasyonları ile bilinen bir öz dengeli (self-balancing) ağaç olan B+ ağacını uyguladım.
- Verimli veri ekleme, B+ ağacının dengesini koruma ve arama işlemini optimizasyon algoritması uyguladım, bu sayede B+ tree, sıralı verilere hızlı erişim gerektiren uygulamalar için uygun hale geldi.

### Tıbbi Maliyet Analizi - Kaggle
- Çeşitli grafiklerle veri görselleştirmesi uyguladım, outlier değerleri Interquartile Range kullanarak kaldırdım, etiket kodlaması (label encoding) ve özellik ölçeklendirmesi (feature scaling) yaptım.
- Birden fazla regresyon modelini denedim ve cross validation kullanarak en iyi modeli seçtim.
- En iyi performans gösteren algoritmayı (Random Forest) hiperparametre ayarlama ile geliştirdim ve ayarlanmış modeli R2 puanı ile test veri setinde 0.84 doğrulukla ölçtüm.

**Comment by VB10** [comment]
Merhaba @koozgur, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @koozgur
