### ISSUE TITLE
Merve Çelik [][][zorunlu][30gün]

### ISSUE THREAD

**Issue by mc00mgk** [VB10/staj_2024#25]
### Kişisel:

- **Ad Soyad:*merve Çelik*
- **Okul:*düzce üniversitesi
- **Sınıf:*4. Sınıf *
- 
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):

Merve Çelik. Düzce üniversitesi bilgisayar mühendisliği son sınıf öğrencisiyim. 

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @mc00mgk, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
