### ISSUE TITLE
Meryem Merve YILDIZ [data-science][yüzyüze , uzaktan][zorunlu][6hafta]

### ISSUE THREAD

**Issue by meryemerveyildiz** [VB10/staj_2024#251]
- Meryem Merve YILDIZ
- Okul: Celal Bayar Üniversitesi
- Sınıf: 4
- CV: https://drive.google.com/file/d/1PWXaebizYK-1a18AkI4lv-x2ReAi6W6o/view?usp=sharing
- Sigorta Okul Karşılıyor: Evet

**Kendim Hakkında:**

Yazılım Mühendisliği 4. sınıf öğrencisiyim. 4. sınıfın ikinci dönemi tamamlamam gereken 75 iş günü İş Yeri ve Uygulama Eğitimim var. Yapay zeka ve veri bilimi alanında staj aramaktayım. Tez çalışmamı da yapay zeka alanında yaptım ve kendimi bu alanda geliştirmek istiyorum. Sadece staj değil aynı zamanda kariyerimin sağlam temelini oluşturacağım uzun soluklu bir iş arıyorum. 

Linkedln hesabım: www.linkedin.com/in/meryem-merve-yildiz

**Teknik (Örnek projeler, linkleri ve detayları):**

Yapay Zeka İle Maaş Tahmini Modeli =>  https://github.com/meryemerveyildiz/Salary-Estimation-With-DL-Model

**İlgilendiklerim (diller, frameworkler vs):**

-Python
-TensorFlow
-Yapay Zeka
-Veri Bilimi

**Comment by VB10** [comment]
Merhaba @meryemerveyildiz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @meryemerveyildiz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @meryemerveyildiz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @meryemerveyildiz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @meryemerveyildiz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @meryemerveyildiz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
