### ISSUE TITLE
MELEK-TAŞ  [BACKEND,DATABASE][YÜZYÜZE ][ZORUNLU ][6 HAFTA ]

### ISSUE THREAD

**Issue by MelekTas** [VB10/staj_2024#258]
### Kişisel:

- **Ad Soyad: MELEK TAŞ**
- **Okul: NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ**
- **Sınıf: 2. SINIF**
- **CV: https://drive.google.com/file/d/1vAEHrjY05jKUkpliBSJjmMsbdE7qB786/view?usp=sharing**
- **Sigorta Okul Karşılıyor : Evet**

### Kendin Hakkında (kendini anlatmak istersen):
Backend tarafına ilgim var, öğrenmeye açık ve takım çalışmasına yatkın biriyim. Google Oyun ve Uygulama Akademisi mezunuyum, mobil uygulama geliştirme konusunda deneyime sahibim. 

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim:  Java, Spring Boot , C#, C, Python , Flutter, SQL **

**Comment by VB10** [comment]
Merhaba @MelekTas, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @MelekTas, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @MelekTas, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
