### ISSUE TITLE
Merve Çelik [mobile][uzaktan][zorunlu][30 gün]

### ISSUE THREAD

**Issue by mc00mgk** [VB10/staj_2024#26]
### Kişisel:

- **Ad Soyad:*merve Çelik*
- **Okul:*düzce üniversitesi
- **Sınıf:*4. Sınıf *
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):
- C#, c++ Java
- OOP 
- unity 
- Arduino
-

**Comment by VB10** [comment]
Merhaba @mc00mgk, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
