### ISSUE TITLE
Berkay Çelikdemir [Mobil][Uzaktan][Zorunlu][6 Hafta]

### ISSUE THREAD

**Issue by celikdemirrberkay** [VB10/staj_2024#268]
### Kişisel:

- **Ad Soyad: Berkay Çelikdemir**
- **Okul: Marmara Üniversitesi**
- **Sınıf: 3. Sınıf**
- **CV:**https://drive.google.com/file/d/1P-oWgz5y3MogNM8TH3zKvgL9e4e3mIFi/view?usp=drive_link(#)
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):

Merhabalar ben Berkay Çelikdemir,

Marmara Üniversitesi elektrik elektronik mühendisliği üçüncü sınıf öğrencisiyim.

- Bundan öncesinde Marmara Teknopark'ta bulunan bir startup firmada (Pnaps) 1.5 ay tam zamanlı + 7.5 ay yarı zamanlı çalışma şeklinde Flutter ile mobil uygulamalarını geliştirdim. Geliştirirken Firebase, Firebase Auth, Cloud Storage, Firestore Git, Test Lab, SQFLite vs.. gibi teknolojileri kullandım.

- Bilişim vadisinde bir firmanın demo mobil uygulamasını da responsive şekilde Flutter ile geliştirdim.

Cross platform Flutter dışında Android'de Jetpack Compose ve Clean architecture üzerine çalışıyorum. Güncel teknolojileri de hem Twitter hem Linkedin hem de Stackoverflow gibi sitelerden takip etmeye devam ediyorum. 

Kısaca ;
-Dart
-Flutter
-Kotlin 
-Firebase
gibi teknolojilere hakimim.

Kendi yaptığım ve Playstore'da yayınladığım uygulamam var. Mobil uygulama geliştirme ağırlıklı deneyimim.

Şimdiden teşekkürler.

Saygılarımla.

- Linkedin : https://www.linkedin.com/in/berkaycelikdemir/

- GitHub : https://github.com/celikdemirrberkay

- Stackoverflow : https://stackoverflow.com/users/15014492/berkaycelikdemir

- Medium : https://medium.com/@berkaycelikdemirr

- Uygulamalarımın linki : https://play.google.com/store/apps/dev?id=4773555454512847371

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs): Flutter, Dart, Kotlin, Android**

**Comment by VB10** [comment]
Merhaba @celikdemirrberkay, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @celikdemirrberkay, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
