### ISSUE TITLE
MELİH TOSUN [frontend][uzaktan, yüzyüze][gönüllü][4hafta, 6hafta]

### ISSUE THREAD

**Issue by melihtosun** [VB10/staj_2024#271]
### Kişisel:

- **Ad Soyad: Melih Tosun**
- **Okul: Hacettepe Üniversitesi**
- **Sınıf: 4. Sınıf**
- **CV:** [Google Drive Linki veya pdf linki](https://drive.google.com/file/d/1MhWOQS1pUSU_q8tp2ChlilES8UgN0vgZ/view?usp=sharing)(#)
- **Sigorta Okul Karşılıyor: Evet**

### Kendin Hakkında (kendini anlatmak istersen):

Results‐driven Software Developer with hands‐on experience in React, Next.js, MongoDB, Node.js, xpress.js and Tailwind, showcasingstrong Front‐End skills. Currently pursuing a BSc in Mathematics, complemented by an Associate Degree in Computer Programming. Adept at or‐ ganizing and executing successful events, demonstrating strong leadership and communication skills. Specializing in crafting engaging and responsive user interfaces. Well‐versed in Agile methodologies, ensuring collaborative and efficient project development. Detail‐oriented and passionate about contributing to innovative projects and dynamic development teams.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs): React, Next.js, Microsoft Azure, Node.js, MongoDB, HTML, CSS, JavaScript, Python, GIT, Bootstrap, Tailwind**

**Comment by VB10** [comment]
Merhaba @melihtosun, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
