### ISSUE TITLE
[Büşra Yılmaz] [Backend-Database-Front end][Yüz yüze-Uzaktan][Zorunlu][4-6 hafta]

### ISSUE THREAD

**Issue by bsraayilmz** [VB10/staj_2024#272]
### Kişisel:

- **Ad Soyad: Büşra Yılmaz
- **Okul: İzmir Ekonomi Üniversitesi- Bilgisayar Mühendisliği
- **Sınıf: 3.sınıf
- **CV:** 
  [busra_yilmaz_cv (1) - Kopya.pdf](https://github.com/VB10/staj_2024/files/14166048/busra_yilmaz_cv.1.-.Kopya.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendin Hakkında (kendini anlatmak istersen):
Merhaba, Ben İzmir Ekonomi Üniversitesi Bilgisayar Mühendisliği üçüncü sınıf öğrencisi [Adınız]. Sekiz yıl süren voleybol kariyerim, takım olmanın değerini derinlemesine kavramama katkı sağladı; son beş yıl ise bu alanda profesyonel olarak geçti. Günümüz teknolojisinin hızla ilerlediği bu dönemde, bu alana olan hayranlığım ve heyecanım beni sürekli olarak gelişmeye teşvik ediyor. İnandığım bir ilke var: donanımlı bir mühendis olmak için sadece kendi alanımda değil, aynı zamanda girişimcilik ve inovasyon gibi diğer alanlarda da kendimi geliştirmeliyim. Bu nedenle, Aygaz A.Ş.'de gerçekleştirdiğim gönüllü stajım, inovasyon ve fikri haklar departmanında edindiğim deneyimle teknolojiye daha inovatif ve profesyonel bir bakış açısı kazanmamı sağladı. Bu stajımın ile birlikte yaz ayı içerisinde toplamda 2 staj yapmış olmam, ve 3.sınıf güz döneminde de bir tane uzun dönem stajını gerçekleştirmiş olmam bu mücadelemenin ve öğrenme hevesimin en büyük kanıtı. Ayrıca, okulumuzun IEEE'nin Computer Society komitesinde bir yıldır başkan yardımcılığı görevini sürdürüyorum. Almış olduğum üç buçuk yıllık mühendislik eğitimim boyunca çeşitli projeler geliştirdim, örneğin, OOP kapsamında Cannon Folder adlı atak ve defans temalı oyun, Python dilini kullanarak A* ve Uniform Cost en kısa yolu hesaplama algoritmalarını içeren yapay zeka robotu, JavaFx, Gradle teknolojilerini kullanarak çevrimdışı sözlük masaüstü uygulaması ve Java dilinde SQLite veritabanını, Maven teknolojisini kullanarak üniversite ders düzenleme masaüstü uygulaması gibi. Bu projeler, mühendislik yeteneklerimi geliştirmemin yanı sıra çeşitli teknolojilere hakimiyetimi gösterme fırsatı sundu. 

### Teknik (Örnek projeler, linkleri ve detayları)

**Course Syllabus Masaüstü Uygulaması:** https://github.com/bsraayilmz/SE-302-Project-Team4
Ders koordinatörünün erişimine izin veren proje, İzmir Ekonomi Üniversitesi'nde önceki olarak
gönderilen dersleri eklemeyi, düzenlemeyi ve görüntülemeyi amaçlar. Bu, ders koordinatörü için
ders sürüm takibini büyük ölçüde kolaylaştırır. SQLite, Maven ve JavaFX teknolojileri kullanılmıştır

**Çevrimdışı Sözlük Masaüstü Uygulaması (DictOff):**  https://github.com/bsraayilmz/ce216Project
Önceden belirlenmiş olan sözlük dosyaları kullanılarak, çevrimdışı çeviri, eş anlamlı bulma, kelimeanlam çiftleri ve kelime-eş anlamlı çiftleri ekleme uygulaması oluşturuldu. Bu işlemler, Java programlama dili, JavaFx GUI yapısı, Gradle derleme aracı ve test aşaması için JUnit çerçevesi kullanıldı.

**Yapay Zeka En Kısa Yolu Hesaplama Robotu (BlinkPath):** 
[SE_420_project_busra_yilmaz_20200602055.pdf](https://github.com/VB10/staj_2024/files/14165910/SE_420_project_busra_yilmaz_20200602055.pdf)
[SE420_Project_BlinkPath_busra_yilmaz_20200602055.zip](https://github.com/VB10/staj_2024/files/14165911/SE420_Project_BlinkPath_busra_yilmaz_20200602055.zip)

Proje, Python dilinde geliştirilmiş bir oyun uygulamasını içermekteydi. Robotun başlangıç odasından hedef odaya en kısa yolu takip ederek taşınması hedeflendi. İlerlemenin görsel olarak takip edilebilmesi amacıyla bir Grafiksel Kullanıcı Arayüzü (GUI) ekledim. Oyunun temel mantığı, robotun belirlenmiş odalar arasında hareket etmesini sağlamak ve kullanıcının bu süreci takip edebilmesini sağlamaktı. Python'un esnek ve anlaşılır yapısı, bu projede tercih etmemi ve projeyi başarıyla hayata geçirmeme yardımcı oldu.

**Cannon Folder**: https://github.com/bsraayilmz/cannonFolderGame
Cannon Folder oyunu atak ve defans mantalitesine sahip üç farklı karakteri içeren ve her karakterin kendine has özel bir gücü olduğu projedir. Proje Java programlama dili ile hazırlanmıştır ve GUI sahip değildir.

**İlgilendiklerim (diller, frameworkler vs):**
- Java, JUnit, JavaFx
- MySQL, SQLite
- HTML, CSS, Bootstrap, JavaScript, JSON
- Artifical Intelligence

**Comment by VB10** [comment]
Merhaba @bsraayilmz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
