### ISSUE TITLE
NURSENA-ZENGİN [backend][uzaktan, yüzyüze][zorunlu][4 hafta]

### ISSUE THREAD

**Issue by nursenazengin** [VB10/staj_2024#275]
Kişisel:

- Ad Soyad: Nursena Zengin
- Okul: Manisa Celal Bayar Üniversitesi
- Sınıf: Bilgisayar Mühendisliği (İngilizce) 3.Sınıf
- CV: https://drive.google.com/file/d/16Gdz5QEMwqLtIEFIG398xqHL3K-vsRjK/view?usp=sharing
- Sigorta Okul Karşılıyor: Evet

Kendin Hakkında (kendini anlatmak istersen):
Yapay Zeka ve Yazılım Geliştirme alanlarına büyük ilgi duyan biriyim. Öğrenmeye ve kendimi geliştirmeye hevesliyim. Bunun için kariyer fırsatları arıyorum.

- İlgilendiklerim (diller, frameworkler vs): 
Java, C, Python
.Net, SQL

**Comment by VB10** [comment]
Merhaba @nursenazengin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nursenazengin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nursenazengin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nursenazengin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
