### ISSUE TITLE
Ömürcan Kaya [backend,mobile,data-science][uzaktan, yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by omurcankaya** [VB10/staj_2024#28]
### Kişisel:

- **Ad Soyad:** Ömürcan Kaya
- **Okul:** Çanakkale Onsekiz Mart Üniversitesi | Bilgisayar Mühendisliği 
- **Sınıf:** 2. Sınıf
- **CV:** [OMURCAN_KAYA_RESUME.pdf](https://drive.proton.me/urls/55AZ7SA8T8#wuVbhkFIVKtI) 
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendin Hakkında:
Bilgisayar Mühendisliği 2. Sınıf öğrencisiyim nodejs ve backend alanında ilgiliyim. Orta seviyede JavaScript biliyorum. OOP modeline hakimim. Aynı zamanda Tersine mühendislikle hobi olarak ilgilendiğim için Assembly dilini temel seviyede biliyorum. .NET tarafında da analizler yaptığım için ise C# diline hakimim ve algoritma analizi yapabilecek kapasiteye sahibim. Aynı zamanda üniversite bünyemizde yeni kurduğumuz yapay zeka kulübünün kurucu başkan yardımcısıyım. Atılgan birisiyim diyebilirim. Doküman ve makale okuyabilecek seviyede İngilizce bilgim var.

### Teknik
Okul bünyesinde İHA takımında yer alıyorum ve iha'nın otonom sistemini yazıyorum. Kendimizin tasarladığı şarj istasyonuna uygun şekilde iniş yapılmasını ve görevini tamamen otonom şekilde yerine getirmesi üzerine çalışıyorum. Python dilini kullanarak geliştiriyorum. Temel seviyede elektronik bilgim de var.
### **İlgilendiklerim (diller, frameworkler vs):**
- Nodejs, React Native
- .NET, JavaScript
- Reverse Engineering, Assembly

**Comment by VB10** [comment]
Merhaba @omurcankaya, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @omurcankaya, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @omurcankaya, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
