### ISSUE TITLE
Muhammet Sarıcan [frontend][uzaktan, yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by muhammetsarican** [VB10/staj_2024#282]
### Kişisel:

- **Ad Soyad:** Muhammet Sarıcan
- **Okul:** Karabük Üniversitesi
- **Sınıf:** Mezun Durumunda
- **CV:** [Google Drive Linki](https://drive.google.com/file/d/1_8chXSFBtg9ejAOcGekYfyi0BkWcM1UO/view?usp=sharing)
- **Sigorta Okul Karşılıyor:** Evet  

### Hakkımda:

Merhaba ben Muhammet Sarıcan, Karabük Üniversitesinde okuyorum ve mezun olabilmek için zorunlu staja ihtiyacım var. Biraz kendimden bahsetmem gerekirse Nisan 2022'den bu yana freelance olarak yerli bir platformda çalışıyorum, bu güne kadar 10'dan fazla iş yaptım/yer aldım. Bu işler farklı alanlardaydı frontend, backend, masaüstü uygulama ve yapay zeka gibi alanlarda hizmet verdim. Yaklaşık 1 yıla yakın frontend üzerine çalışıyorum.

### Teknik Detaylar:
Projelerimi [link](https://www.github.com/muhammetsarican) üzerinden inceleyebilirsiniz.

- **Diller:**
- JavaScript
- TypeScript
- Html
- Css
- Php
- C#
- Python
- **Frameworkler:**
- React Js
- Next Js
- Vue Js (Beginner)
- Laravel
- **Diğer:**
- Mongo DB
- Tailwind Css
- Bootstrap
- Redis
- Docker

**Comment by VB10** [comment]
Merhaba @muhammetsarican, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
