### ISSUE TITLE
ERSAN DENİZ [mobile, backend][yüzyüze][zorunlu][4hafta, 6 hafta]

### ISSUE THREAD

**Issue by Ersandeniz** [VB10/staj_2024#291]
Kişisel:

Ad Soyad : ERSAN DENİZ
Okul : Sivas Cumhuriyet Üniversitesi
Sınıf : 4.sınıf 
CV:
Sigorta Okul Karşılıyor: Evet 

Kendin hakkında:

 Bilgisayar mühendisliği öğrencisiyim. Şu an Üniversitesi son sınıfta uzmanlaşmak için uğraşıyorum. kotlin ile başladığım yazılım dünyasında pek çok dil öğrenerek kendimi geliştiriyorum. Yeni bir şeyler öğrenmeyi seviyorum . Takım çalışmasına kabiliyetim var . Kendimi daha da geliştirmek için staj yapmak ve sektörde deneyim kazanmak istiyorum.

Teknik (Örnek projeler, linkleri ve detayları): 
Şuan bitirme projesi olarak uygulamalar geliştiriyorum. Daha önce ekipçe pek çok uygulama geliştirdim  

İlgilendiklerim (diller, frameworkler vs):
İleri düzey flutter ve kotlin.
Orta düzey Java

**Comment by VB10** [comment]
Merhaba @Ersandeniz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ersandeniz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ersandeniz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ersandeniz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ersandeniz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
