### ISSUE TITLE
ESRANUR ALTINAY [pm][yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by esranuraltinay** [VB10/staj_2024#293]
### Kişisel:

- Ad Soyad: Esranur Altınay
- Okul: Fırat Üniversitesi
- Sınıf: 3.sınıf
- CV: https://drive.google.com/file/d/1t8MzYx9QyliT58XlRGpQEfsfeC6Zs-FX/view?usp=drive_link
- Sigorta Okul Karşılıyor*(Evet/Hayır): Evet

 Kendin Hakkında (kendini anlatmak istersen):

Merhaba, yazılım mühendisliği 3.sınıf öğrencisiyim bu yaz 40 iş günü zorunlu stajım var. Kendimi proje yönetimi alanlarında geliştiriyorum ve öğrendiğim bilgileri pratiğe döküp yaz döneminde kendimi daha da geliştirebileceğim bir staj arayışındayım. Yaz stajım sonrası 2024-2025 güz döneminde ise zorunlu iş yeri eğitimim bulunmaktadır. Eğer mümkünse staja başlayacağım şirkette tüm stajlarımı yapmayı çok isterim.

 Teknik (Örnek projeler, linkleri ve detayları)

- İlgilendiklerim (diller, frameworkler vs): Project Management, PO, Scrum Master, Java, Python

**Comment by VB10** [comment]
Merhaba @esranuraltinay, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @esranuraltinay, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @esranuraltinay, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @esranuraltinay, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @esranuraltinay, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @esranuraltinay, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by esranuraltinay** [comment]
> ### Kişisel:
> * Ad Soyad: Esranur Altınay
> * Okul: Fırat Üniversitesi
> * Sınıf: 3.sınıf
> * CV: https://drive.google.com/file/d/1t8MzYx9QyliT58XlRGpQEfsfeC6Zs-FX/view?usp=drive_link
> * Sigorta Okul Karşılıyor*(Evet/Hayır): Evet
> 
> Kendin Hakkında (kendini anlatmak istersen):
> 
> Merhaba, yazılım mühendisliği 3.sınıf öğrencisiyim bu yaz 40 iş günü zorunlu stajım var. Kendimi proje yönetimi alanlarında geliştiriyorum ve öğrendiğim bilgileri pratiğe döküp yaz döneminde kendimi daha da geliştirebileceğim bir staj arayışındayım. Yaz stajım sonrası 2024-2025 güz döneminde ise zorunlu iş yeri eğitimim bulunmaktadır. Eğer mümkünse staja başlayacağım şirkette tüm stajlarımı yapmayı çok isterim.
> 
> Teknik (Örnek projeler, linkleri ve detayları)
> 
> * İlgilendiklerim (diller, frameworkler vs): Project Management, PO, Scrum Master, Java, Python

**Comment by VB10** [comment]
Merhaba @esranuraltinay, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @esranuraltinay, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
