### ISSUE TITLE
ESRANUR ALTINAY [pm][yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by esranuraltinay** [VB10/staj_2024#294]
.

**Comment by VB10** [comment]
Merhaba @esranuraltinay, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @esranuraltinay, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
