### ISSUE TITLE
Berk Erdoğan [mobil][yüzyüze][gönüllü][6hafta]

### ISSUE THREAD

**Issue by BerkErdgn** [VB10/staj_2024#304]
### Kişisel:

- **Ad Soyad : Berk Erdoğan**
- **Okul : Çanakkale 18 Mart Üniversitesi**
- **Sınıf : Mezun**
- **CV:** [https://drive.google.com/file/d/1xCba9eM_7VtYunYNb0LOAMd-DJ0-T7l5/view](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Hayır

### Kendin Hakkında (kendini anlatmak istersen):

Merhaba, ben Berk Erdoğan. Yazılım alanında bir kariyer yapmaya istekli, bilgisayarlar uğraşmaktan büyük keyif alan biriyim. Önceki deneyimlerim arasında Çevre Mühendisliği alanında çalışmalarım bulunmakta olup, şu anda Android developer olarak kendimi geliştirmek ve bu alanda kariyerime devam etmek istemekteyim.

Kotlin dilinde orta seviyede deneyim sahibiyim ve Python'u da orta seviyede bilmekteyim. Projelerimi GitHub üzerinde paylaşmakta ve sürekli olarak yeni beceriler ve teknolojiler öğrenerek kendimi geliştirmeye devam etmekteyim. Yaratıcı düşünebilen, analitik ve yeniliklere açık bir yapıya sahip olarak, her projede en iyi sonuçları elde etmek için çabalarım.

Eğitimimi, Çanakkale Onsekiz Mart Üniversitesi'nde Mühendislik Fakültesi'nde İngilizce Çevre Mühendisliği alanında tamamladım. 

Motor sporlarına ilgi duymaktayım ve bilgisayar oyunlarıyla aktif olarak ilgilenmekteyim. Müzik dinlemek ve fitness ile ilgilenirken, antika eşyalara olan ilgim ve bisiklet sürmek gibi hobilerimle hayatımı dengeli bir şekilde yönlendirmekteyim

### Teknik (Örnek projeler, linkleri ve detayları)

- **Linkedln:** [https://www.linkedin.com/in/berk-erdgn/](#)
- **Github:** [https://github.com/BerkErdgn](#)

- **İlgilendiklerim (diller, frameworkler vs):** Kotlin, Python

**Comment by VB10** [comment]
Merhaba @BerkErdgn, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @BerkErdgn, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @BerkErdgn
