### ISSUE TITLE
FATİH ALTUNAŞ [backend, mobil, gömülü sistemler][YÜZYÜZE][ZORUNLU][20 GÜN]

### ISSUE THREAD

**Issue by Conquerorr0** [VB10/staj_2024#311]
### Kişisel:

- **Ad Soyad:**  Fatih Altuntaş
- **Okul:** Fırat Üniversitesi
- **Sınıf:** 3. Sınıf
- **CV:** [https://github.com/Conquerorr0/CV.git](#) 
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Hakkımda:
Merhaba, ben Fırat Üniversitesi Bilgisayar Mühendisliği öğrencisi Fatih. Yazılıma olan ilgim ve üniversite projelerimde kazandığım deneyimlerle kendimi geliştirdim. Şimdi, öğrendiklerimi kendi projelerimde kullanarak daha da ileri gitmek istiyorum. Takım çalışmasına önem veriyor, sürekli öğrenme ve gelişme amacıyla ilerliyorum. Gelecekte başarılı bir yazılım mühendisi olmak için azimle çalışıyorum.

## Basic Student Registration System with C:
https://github.com/Conquerorr0/Student-Registration-System.git
## Minesweeper Game with Java:
https://github.com/Conquerorr0/MinesweeperGame.git
## Sale-Stock  App with Java:
https://github.com/Conquerorr0/Sale-Stock-App-With-Java.git

- **İlgilendiklerim (diller, frameworkler vs):**
- Java (Swing, JavaFX), Temel Seviye Python,  C#, C, SQL.

**Comment by VB10** [comment]
Merhaba @Conquerorr0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by Conquerorr0** [comment]
Zorunlu stajım için staj yeri arıyorum. Mümkünse iki farklı departmanda toplam 40 iş günü olmak üzere staj yapmakta benim için uygundur.

**Comment by VB10** [comment]
Merhaba @Conquerorr0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Conquerorr0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Conquerorr0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Conquerorr0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Conquerorr0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Conquerorr0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Conquerorr0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
