### ISSUE TITLE
ANIL BERKAN TORUN [BACKEND,SİBER GÜVENLİK] [UZAKTAN] [ZORUNLU] [14 HAFTA]

### ISSUE THREAD

**Issue by AnilBerkanTorun** [VB10/staj_2024#317]
### Kişisel:

- **Ad Soyad:ANIL BERKAN TORUN
- **Okul:İNÖNÜ ÜNİVERSİTESİ
- **Sınıf:4
- **CV:
[ANIL BERKAN TORUN CV.pdf](https://github.com/VB10/staj_2024/files/14237637/ANIL.BERKAN.TORUN.CV.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır):EVET 

### Kendin Hakkında (kendini anlatmak istersen):

Merhabalar, İnönü Üniversitesi Bilgisayar Mühendisliği son sınıf öğrencisiyim.İşletmede mesleki eğitim kapsamında (IME-UME) staj yapmak istiyorum.

### [https://github.com/AnilBerkanTorun](url)

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @AnilBerkanTorun, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @AnilBerkanTorun, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @AnilBerkanTorun, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
