### ISSUE TITLE
Barış Gevher [uzaktan][mobile,backend,data-science,database][zorunlu][6hafta]

### ISSUE THREAD

**Issue by 19032001-afk** [VB10/staj_2024#319]
[Barış-Gevher-Yazılım-Mühendisi.pdf](https://github.com/VB10/staj_2024/files/14238962/Baris-Gevher-Yazilim-Muhendisi.pdf)

**Comment by VB10** [comment]
Merhaba @19032001-afk, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
