### ISSUE TITLE
Barış Gevher [mobile,backend,data-science,database][uzaktan][zorunlu][6hafta]

### ISSUE THREAD

**Issue by barisgevher** [VB10/staj_2024#321]
### Kişisel:

- **Ad Soyad:**   Barış Gevher
- **Okul:**     Bandırma Onyedi Eylül Üniversitesi
- **Sınıf:**     4
- **CV:** [Google Drive Linki veya pdf linki](#)  
[Barış-Gevher-Yazılım-Mühendisi.pdf](https://github.com/VB10/staj_2024/files/14239019/Baris-Gevher-Yazilim-Muhendisi.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır):  EVET

### Kendin Hakkında:
Yazılım sektöründe yeni kendini geliştirip ülkesinin gelişimini isteyen birisiyim

### Teknik (Örnek projeler, linkleri ve detayları)
Örnek olarak CV'mde bulunan kurslarda yapılan projeler verilebilir
- **İlgilendiklerim (diller, frameworkler vs):**
Java, Kotlin, Mssql, Python, Makine Öğrenmesi, C#

**Comment by VB10** [comment]
Merhaba @19032001-afk, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
