### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by AvniKahraman** [VB10/staj_2024#340]
### Kişisel:

- Ad Soyad: Avni Kahraman
- Okul: Yakın Doğu Üniversitesi
- Sınıf: 3. Sınıf
- CV: https://drive.google.com/file/d/1l79AuHgL71fSD2_yJqbau1Fa8m5kLp6y/view?usp=drive_link
- Sigorta Okul Karşılıyor (Evet/Hayır): Hayır

### Kendin Hakkında (kendini anlatmak istersen): Merhaba ben Avni Kahraman Yakındoğu Üniversitesi Bilişim Sistemleri ve Teknolojileri bölümü 3.Sınıf öğrencisiyim iş hayatı ve takım çalışması için gereken deneyimi kazanmak için staj yapmak istiyorum. Şimdiden teşekkürler

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)
https://github.com/AvniKahraman

- İlgilendiklerim (diller, frameworkler vs):
- Android Kotlin ile ilgileniyorum ve kotlin öğrenmeye çalışıyorum  ancak java ile de bir çok projem var.

**Comment by VB10** [comment]
Merhaba @AvniKahraman, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
