### ISSUE TITLE
Esabet Murat Yurtseven [mobile][uzaktan, yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by MuratYurtseven** [VB10/staj_2024#346]
### Kişisel:

- **Ad Soyad:** Esabet Murat Yurtseven
- **Okul:** Samsun Üniversitesi
- **Sınıf:** 2.Sınıf
- **CV:** https://drive.google.com/file/d/1zS6PvqlGKkW_zof2bCB694kgMaNdWocG/view?usp=sharing
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
Merhaba, Samsun Üniversitesi Yazılım Mühendisliği 2.sınıf öğrencisiyim. iOS development alanındaki kişisel ilgi ve özverimle gelişimimi sürdürmekteyim.Bu alanda edindiğim bilgilerle şirketinizde stajyer olarak katkı sağlamak ve aynı zamanda kendi gelişimime de ivme kazandırmak istiyorum.Saygılarımla.

### Teknik (Örnek projeler, linkleri ve detayları)
RickAndMorty = https://github.com/MuratYurtseven/RickAndMortyApp-MVVM-Swift
Which cat is best for you App   = https://github.com/MuratYurtseven/WhichCatIsBestForYouApp-VIPER-Swift
IMBdApp = https://github.com/MuratYurtseven/IMBdApp-Swift-VIPERPattern

- **İlgilendiklerim (diller, frameworkler vs):** Swift , SwiftUI

**Comment by VB10** [comment]
Merhaba @MuratYurtseven, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @MuratYurtseven, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @MuratYurtseven, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
