### ISSUE TITLE
Emirhan-Türkol [game][yüzyüze, hibrit, uzaktan][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by Ehan0022** [VB10/staj_2024#348]
[Emirhan_CV (2) (1).pdf](https://github.com/VB10/staj_2024/files/14359025/Emirhan_CV.2.1.pdf)
### Kişisel:

- **Emirhan Türkol** 
- **Marmara Üniversitesi - Bilgisayar Mühendisliği (İng)**
- **2. Sınıf**
- **CV:**
[Emirhan_CV (2) (1).pdf](https://github.com/VB10/staj_2024/files/14359028/Emirhan_CV.2.1.pdf)

- **Sigorta Okul Karşılıyor** Evet

### Kendin Hakkında (kendini anlatmak istersen):
   Ben Emirhan Türkol, Marmara Üniversitesi bilgisayar mühendisliği 2. sınıf öğrencisiyim. Okulumun ilk senesinde kendimi geliştirmek istediğim alan olan Oyun Geliştiriciliğinde kendimi geliştirmek adına Oyun Ve Uygulama Akademisi'ne başvurdum ve kabul aldım. 8 aylık eğitimin ardından da mezun oldum. 400+ saat Unity içeriği ile Unity ile oyun geliştirmeyi öğrendim. Aynı zamanda  Oyun ve Uygulama Akademisi kapsamında Google'ın Coursera üzerinden sunduğu proje yönetimi dersleri ile girişimcilik eğitimlerini tamamladım. Şu anda da üniversitemin Oyun Geliştirme Kulübü ile birlikte yeni projeler geliştirmeye hazırlanıyorum. Üniversitemin 2. sınıfında ise 42 İstanbul'a katıldım. Global ağı ve yöntemi ile ilgimi çeken 42'de havuz sürecimi başarıyla tamamladım. Temmuz ayında da 42'de ana eğitimime başlıyor olacağım. Okulda geçen 2 senemde ise Java ve C dilleri üzerine çalıştım ve kendimi bu dillerde geliştirdim.

## İlgilendiklerim:
- **Game Development with Unity**
- **Game Design**
 - **C#**
 - **C**
  - **Android Studio**
  - **Java**

**Comment by VB10** [comment]
Merhaba @Ehan0022, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ehan0022, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ehan0022, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ehan0022, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @Ehan0022, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @Ehan0022, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @Ehan0022
