### ISSUE TITLE
Mehmet Nur-Kavan [mobile, frontend, backend, blokchain][yüz-yüze][Zorulu][20 iş günü-dönem stajı]

### ISSUE THREAD

**Issue by MehmetNurKavan** [VB10/staj_2024#351]
### Kişisel:

- **Ad Soyad:Mehmet Nur Kavan**
- **Okul:Fırat Ünivresitesi**
- **Sınıf: 3. sınıf**
- **CV:** [cvMehmetNurKavan.pdf](https://github.com/VB10/staj_2024/files/14364628/cvMehmetNurKavan.pdf)(#)
- **Sigorta Okul Karşılıyor** (Evet): 
- **linkedin: https://www.linkedin.com/in/mehmet-nur-kavan-501608221/**
- **gitHub: https://github.com/MehmetNurKavan**
- **mail: [kavanmehmetnur@gmail.com](mailto:kavanmehmetnur@gmail.com)**

### Kendin Hakkında (kendini anlatmak istersen): 
Merhaba , Ben Mehmet Nur Kavan Fırat Üniveristesi 3. Sınıf öğrencisiyim. 20 iş günü zorunlu stajım bulunmaktadır. Ve 4. sınıf 2. dönemde dönem stajı arıyorum. Dart dili ile Flutter üzerinden Firebase işlemleri gerçekleştiriyorum. Java, C#, Python, .Net gibi dil ve frameworkler ile de bilgilerim mevcuttur. Oyun ve Uygulama akademisinden Flutter ile mobil app geliştirerek mezun oldum. Blokchain alanına merakım var ve Solidity eğitimleri alıyorum şu an. Bu alanlarda eğitimler , sertifikalar aldım ve kendimi geliştirmeye çalıştım. Öğrendiğim teorik bilgileri pratiğe dökmek istiyorum.
Staj arayışım İstanbuldadır.
### Teknik (Tarih istanbul App: https://github.com/MehmetNurKavan/Tarih-stanbul)

- **İlgilendiklerim (Flutter, Fiebase, Dart, Java, Solidity,  ...):**

**Comment by VB10** [comment]
Merhaba @MehmetNurKavan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
