### ISSUE TITLE
Batuhan Berk Ertekin [mobile][zorunlu,yüzyüze][4hafta]

### ISSUE THREAD

**Issue by ertekinbatuhan** [VB10/staj_2024#36]
### Kişisel:

- Ad Soyad: Batuhan Berk Ertekin
- Okul: Selçuk Üniversitesi
- Sınıf: 3.Sınıf
- CV: https://drive.google.com/file/d/1ze96aoxdQUM7No2A4zr-QwlnZUXgHYTR/view?usp=sharing
- Sigorta Okul Karşılıyor: Evet

### Kendin Hakkında (kendini anlatmak istersen):
Selçuk Üniversitesi Bilgisayar Mühendisliği 3.sınıf öğrencisiyim. Kendimi Ios alanında geliştirmekteyim. Yeni teknolojiler öğrenmeyi seviyorum. Yaptığım projeleri GitHub hesabımdan görebilirsiniz. Ankara içinde zorunlu 20 iş günü stajım mevcuttur. Eğer memnun kalırsanız tüm yaz boyuncada çalışabilirim. Ücret derdim yok ve sigortamı okul karşılıyor.

**Comment by VB10** [comment]
Merhaba @ertekinbatuhan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ertekinbatuhan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ertekinbatuhan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ertekinbatuhan, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @ertekinbatuhan
