### ISSUE TITLE
BURAK TANIŞ [data science, backend, mobile][uzaktan, yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by buraktanis** [VB10/staj_2024#360]
### Kişisel:

- **Ad Soyad:Burak Tanış**
- **Okul:Yeditepe Üniversitesi**
- **Sınıf:4**
- **CV: (https://drive.google.com/file/d/1odhZBaeZIer_5GIRZxVnm0qv8-NJ2m6H/view?usp=sharing)**
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):

Yeditepe Üniversitesi Yazılım Geliştirme bölümünde 4. sınıf öğrencisiyim. Geçmişte 2 kez staj ve 1 yıl part-time çalışma tecrübem var. .NET Java ve Spring Boot, Kotlin ile projeler geliştirdim. Bunlara ek olarak veri bilimiyle ile son zamanlarda ilgileniyorum. Bu alanlarda staj yapmayı hedefliyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

Sokak hayvanları için sahiplendirme uygulaması olan Stray isimli mobil uygulama geliştirdik geçtiğimiz dönem.
Ayrıca mikroservis tabanlı küçük bir otel rezervasyonu uygulaması yaptım.
Part-time çalışırken şirketi içi ERP'yi geliştirdim.

- **İlgilendiklerim (Java,Python,Kotlin,.NET,HTML,CSS,JavaScript,SQL,MSSQL):**

**Comment by VB10** [comment]
Merhaba @buraktanis, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
