### ISSUE TITLE
Umut Söbe [backend,frontend][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by umutsobe** [VB10/staj_2024#363]
### Kişisel:

- **Ad Soyad:** Umut Söbe
- **Okul:** Süleyman Demirel Üniversitesi
- **Sınıf:** 3
- **CV:** https://drive.google.com/file/d/19f3qHPzN3qqIEiABzBso_ha9DyiV_BHq/view
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
Yaptığım projeleri olabildiğince gerçek hayata benzer olacak şekilde yapmaya çalışırım. Backend, frontend bilgim orta üst, devops bilgim giriş seviyede. 

### Teknik (Örnek projeler, linkleri ve detayları)
Hobi olarak yaptığım E-ticaret sitesi backendi: https://github.com/umutsobe/E-Commerce-ASP.Net-Core-7
Youtube Altyazı Chrome Uzantısı: https://github.com/umutsobe/YouTube-Subtitle-Word-Translator-Chrome-Extension

- **İlgilendiklerim (diller, frameworkler vs):**
ASP.NET Core
Angular
React
C#
Entity Framework
Docker
Jenkins (Temel)
Rest API
Git
Typescript
Javascript
CSS
HTML

**Comment by VB10** [comment]
Merhaba @umutsobe, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
