### ISSUE TITLE
YUSUF ERKOC [MOBILE,FRONTEND][UZAKTAN,YÜZYÜZE][ZORUNLU][4 Hafta]

### ISSUE THREAD

**Issue by yusuferkoc** [VB10/staj_2024#37]
### Kişisel:

- **Ad Soyad:*Yusuf Erkoç*
- **Okul:*Konya Teknik Üniversitesi*
- **Sınıf:*4*
- **CV:** https://drive.google.com/file/d/1LO25M2ZOB5kMjAeM0PODr7hBLkR63zFF/view?usp=drive_link(#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Portfolyo 
### https://sufisland.vercel.app/

- **İlgilendiklerim (diller, frameworkler vs):*Swift ,Swift UI , Ui Kit*

**Comment by VB10** [comment]
Merhaba @yusuferkoc, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @yusuferkoc, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
