### ISSUE TITLE
Berk Mahim [cyber-security, backend][uzaktan,yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by berkmahim** [VB10/staj_2024#370]
### Kişisel:

- **Ad Soyad:** Berk Mahim
- **Okul:** Kocaeli Üniversitesi
- **Sınıf:** 4.
- **CV:** [https://drive.google.com/file/d/1U5-_dbG36Aq1vcp2NIb6dj2ZGe69hJ_z/view?usp=sharing](#)
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):

Yaklaşık 1.5 senedir siber güvenlik alanında çalışmalar yapan ve kendini geliştiren bir üniversite öğrencisiyim. TryHackMe, HackTheBox, Vulnhub gibi platformlarda birçok makine çözdüm ve çözmeye devam ediyorum. Bu sayede becerilerimi geliştiriyorum ancak bu becerilerimi gerçek hayat senaryolarında kullanmak, test etmek, yeni teknik-taktikler öğrenmek, deneyimler kazanmal üzere bir staj arayışım bulunmakta. Edindiğim sertifikaları aşağıda belirttim:
TryHackMe - Jr Pentester
Cisco - Intro to CyberSecurity
Turkish Technology - CyberSecurity GRC

### Teknik (Örnek projeler, linkleri ve detayları)

Linkedin Profilim: [https://www.linkedin.com/in/berk-mahim-7b121aa5/](#)

- **İlgilendiklerim (diller, frameworkler vs):**
Linux'a hakimim, nmap, metasploit gibi araçları ctflerde çokca kez kullandım, yetki yükseltme konusuna ilgim var, shodan.io, maltego, burpsuite, wireshark araçlarını kullanmayı biliyorum. Bunların yanında .NetCore, Java ve Nodejs ile web projeleri geliştirdim.

**Comment by VB10** [comment]
Merhaba @berkmahim, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @berkmahim, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @berkmahim, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
