### ISSUE TITLE
Mertcan KIRCI [mobil][İstanbul][zorunlu][4hafta]

### ISSUE THREAD

**Issue by mertcankirci** [VB10/staj_2024#377]
### Kişisel:

- **Mertcan KIRCI**
- **İstanbul Üniversitesi - Cerrahpaşa**
- **3**
- **CV:** https://drive.google.com/file/d/1HJc0aW6JbfvGnvX2aLwNyBzLBDLidaS0/view?usp=sharing
- **Sigorta Okul Karşılıyor** EVET 

### Kendin Hakkında (kendini anlatmak istersen):

Yüksek motivasyon ve tutku ile donanmış bir öğrenciyim. Müşteri hizmetleri, kamuya hitap etme ve sunum becerileri gibi geniş bir yelpazede yeteneklere sahibim. Detaylara önem veren bir gözle, güçlü organizasyon yeteneklerim sayesinde birden fazla proje üzerinde hassasiyetle çalışabilirim. Hızlı tempolu ortamlarda etkin bir şekilde çalışır, sıkı takvimler altında bile üstün sonuçlar elde ederim. iOS platformunda yetkinlik kazanmak ve profesyonel gelişimime katkı sağlamak için motive bir şekilde çalışıyorum.

### Teknik (Örnek projeler, linkleri ve detayları)
**MYRA**
MyraApp, yapay zeka destekli bir falcı uygulamasıdır. Kullanıcı, falcısının sağladığı geleceğe dayalı tavsiyelere göre falcısıyla sohbet edebilir. MyraApp, SwiftUI kullanılarak MVVM mimarisi, asenkron ağ çağrıları, push bildirimleri ve Google reklamları entegrasyonunu içermektedir. Myra şu anda beta aşamasındadır. Yakında AppStore'da yer alacak.
Henüz beta aşamasında olduğundan link paylaşamıyorum maalesef. Dilerseniz TestFlight linki gönderebilirim.
**QuantifyX**
QuantifyX, modern ölçü birimlerini (örneğin, gr, ml) geleneksel ölçü birimlerine (örneğin, 1 bardak) dönüştüren bir uygulamadır. QuantifyX, SwiftUI ile geliştirilmiş olup gelir kaynağı olarak Google AdMob'u kullanmaktadır.
link: https://github.com/mertcankirci/QuantifyX
**IMDB Fav Films**
Bu uygulama, UIKit kullanılarak geliştirilmiştir ve en güncel IMDB favori filmlerini gösterir.
Ekran kaydırma çubuğu ekranın %80'ine ulaştığında 20 hücre getirmek için pagination kullandım.
-Web Service için Singleton kullandım.
 -MVC
 link: https://github.com/mertcankirci/IMDB-Fav-Films
- **İlgilendiklerim (diller, frameworkler vs):**
Swift, SwiftUI, UIKit, XCTest, Python , Flutter

**Comment by VB10** [comment]
Merhaba @mertcankirci, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
