### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by Atkn0** [VB10/staj_2024#381]
### Kişisel:

- **Ad Soyad:** Arda Atakan Tosun
- **Okul:** Eskişehir Technical University
- **Sınıf:** 2
- **CV:** https://drive.google.com/file/d/107rqN8nw0AUDRT1TM8Ab5v7x00uK78ec/view?usp=sharing
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
Since the moment I started my Computer Engineering
education, I have focused on Dart/Flutter and then
Kotlin/Android in the mobile field. I follow different people's
open-source projects in the mobile field on Github and share
the projects I have developed individually. Afterwards, I want to learn how to work with Android and NodeJS and Web API and socket.io when I need it. I am someone
whose most important goal at the moment is to improve
himself, experience teamwork, and gain experience in the
industry. I am still at the beginning of the road and I am
confident that I will make good progress.

- **İlgilendiklerim (diller, frameworkler vs):**
- Kotlin / Android
- Nodejs Web Backend
- MVVM Mimarisi
- Daggr-Hilt ile Dependeny Injection
- Live Data and Coroutines
- Firebase Firestore and Auth

**Comment by VB10** [comment]
Merhaba @Atkn0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Atkn0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Atkn0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Atkn0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Atkn0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Atkn0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Atkn0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Atkn0, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @Atkn0, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @Atkn0
