### ISSUE TITLE
Ramazan YILDIRIM [data-science][uzaktan,yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by ramazanyildirim02** [VB10/staj_2024#382]
### Kişisel:

- **Ad Soyad: Ramazan Yıldırım
- **Okul: Manisa Celal Bayar Üniversitesi
- **Sınıf: 3. Sınıf
- **CV: https://drive.google.com/file/d/116QiuhUlRPvotr2MKz1gnQ5OjP2Scupm/view?usp=drive_link
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendin Hakkında (kendini anlatmak istersen):
 Kariyerimi sevdiğim alan olan veri biliminde geliştirirken bir yandan da yeni ortamlarla, insanlarla etkileşime girebilmeyi, kendi sınırlarımın dışına çıkabilmeyi ve  kendimi gerçekleştirmeyi istiyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs): python

**Comment by VB10** [comment]
Merhaba @ramazanyildirim02, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ramazanyildirim02, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
