### ISSUE TITLE
Edanur KURUOĞLU [data-science,database][yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by EdanurKuruoglu** [VB10/staj_2024#384]
### Kişisel:

- **Ad Soyad:** Edanur KURUOĞLU
- **Okul:** Kastamonu Üniversitesi 
- **Sınıf:** 3.
- **CV:** [https://drive.google.com/file/d/1DtABgC_eIc2i0PmE30bo-kD0GNDkibX5/view?usp=sharing](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Merhaba, ben Edanur Kuruoğlu ve Kastamonu Üniversitesi'nde Bilgisayar Mühendisliği 3. sınıf öğrencisiyim. Yazılım geliştirme alanında .NET platformunda çeşitli projeler üzerinde çalıştım ve ayrıca Makine Öğrenmesi'nin doğal dil işleme alanında projeler geliştirdim. Bu süreçlerde, hem yazılım becerilerimi geliştirdim hem de problem çözme yeteneklerimi artırdım.

Veri Bilimi'ne olan büyük ilgi ve merakım, bu alanda daha fazla bilgi edinme isteğiyle beni yönlendiriyor. Veri Bilimi'nin teknoloji dünyasında büyük bir etkisi olduğunun farkındayım ve geleceğin teknolojilerinin şekillenmesinde kritik bir rol oynadığını biliyorum. Bu alanda kendimi geliştirmek ve deneyim kazanmak için heyecanlıyım.

### Teknik (Örnek projeler, linkleri ve detayları)

Fake News Detection (https://github.com/EdanurKuruoglu/Fake_News_Detection):
Makine öğrenmesi modellerini kullanarak geliştirilen Sahte Haber Tespiti uygulamasında,
Random Forest, Naive Bayes, K-NN gibi çeşitli algoritmalar kullanılarak model eğitildi. Ayrıca,
Yapay Sinir Ağı (YSA) ile overfitting durumlarına detaylı bir şekilde göz atıldı. Temel amaç,
haber makalelerindeki yanıltıcı bilgileri tespit etmek ve güvenilir bir çözüm sunmaktır. ( Python )

Library Automation ( https://github.com/EdanurKuruoglu/Library_Automation):
Tasarlanılan kütüphane otomasyon sistemi, kullanıcıların ve yöneticilerin kolayca
kullanabileceği bir arayüzle girdileri verimli bir şekilde yönetmeyi amaçlar. Kullanıcı dostu bir
deneyim sunar. Ayrıca kullanıcıların kitapları aramasını, kütüphane istatistiklerine
ulaşabilmesini ve yöneticilerin kütüphaneyi etkili bir şekilde yönetmesini sağlar. ( C#, MySql, .Net )

- **İlgilendiklerim (diller, frameworkler vs):** Python , Java, C, C++, C#, Matlab

**Comment by VB10** [comment]
Merhaba @EdanurKuruoglu, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
