### ISSUE TITLE
Ceylin ÇALTEPE [frontend][uzaktan,yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by CeylinC** [VB10/staj_2024#385]
### Kişisel:

- **Ad Soyad: Ceylin Çaltepe**
- **Okul: Manisa Celal Bayar Üniversitesi**
- **Sınıf: 3. Sınıf**
- **CV: [Ceylin Çaltepe'nin CV'si - Google Drive](https://drive.google.com/file/d/1iAy4RRfIS4AnnxpDSwu4v3CLxWmKTbzw/view?usp=sharing)**
- **Sigorta Okul Karşılıyor: Evet**

### Kendin Hakkında (kendini anlatmak istersen):

Üniversitenin ilk yıllarından beri birçok alanla uğraştım: Oyun, arduino, mobil... Ama içlerinde kendimi en özgür hissettiğim alan front-end oldu. Bu yüzden dolayı kendimi bu alanda geliştirebilmek, sınırlarımı zorlamak, hatalarımı görmek ve bunları düzeltmek istiyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**
  -  HTML
  - CSS
  - SCSS
  - Bootstrap 5
  - Javascript
  - Typescript
  - JQuery
  - Angular
  - React
  - Flutter
  - React Native
  - Git
  - Photoshop
  - Figma
  - Responsive Tasarım

**Comment by VB10** [comment]
Merhaba @CeylinC, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @CeylinC, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
