### ISSUE TITLE
Ali Alcan [Gömülü Sistemler][uzaktan, yüzyüze][zorunlu, gönüllü][4 hafta, 6 hafta]

### ISSUE THREAD

**Issue by 20ali23** [VB10/staj_2024#387]
### Kişisel:

- **Ad Soyad: Ali Alcan**
- **Okul: İstanbul Yeni Yüzyıl Üniversitesi**
- **Sınıf: 3. sınıf **
- **CV:** [CV](https://drive.google.com/file/d/1JPb6p_xCIV1j4Z7N16aKfVcI0vNVMS_Y/view?usp=sharing)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Hakkımda:

Merhabalar ben Ali ALCAN. Lise öğrenimimi Halkalı Mehmet Akif Ersoy Meslek lisesinde Elektrik ve Elektronik Teknolojisi bölümünde alanımı da Güvenlik Sistemleri dalın da okuyarak bitirdim. Zorunlu lise sonu stajımı da elektronik alanında da 8 aylık bir süreçte üretim bölümün de çalışarak tamamladım. Güncel olarak da İstanbul Yeni Yüzyıl Üniversitesin de Elektrik ve Elektronik Mühendisliği bölümünde 3.sınıf öğrencisi olarak devam etmekteyim. 2023 yazında T3 Vakfı Bilim Güngören Merkezin de Bilim Türkiye Gönüllü Eğitmenlik Programı kapsamın da 1 aylık bir süreçte Teknoloji Tasarım atölyesin de gönüllü stajyerlik yaparak tamamladım. Şu an da aktif olarak ilgi duyup üzerinde çalıştığım alanlar Robotik, Donanım Tasarımı, Gömülü Sistemler, Yapay Zeka ve Python olmaktadır. Kendimi ilerleyen bilim sürecine ve gelişen teknolojiye ayak uydurarak araştırma ve proje çalışmaları yaparak geliştirmekteyim.

### Teknik : 
Örnek projelere profilimden ve linkedin profilimden ulaşabilirsiniz.
**LİNKEDİN:** [Linkedin profilim](https://www.linkedin.com/in/ali-alcan-19998122a/)

- **İlgilendiklerim :**
Python 
Donanım Tasarım 
Robotik 
Yapay Zeka 
Gömülü Sistemler

**Comment by VB10** [comment]
Merhaba @20ali23, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @20ali23, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @20ali23, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @20ali23, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @20ali23, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @20ali23, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @20ali23, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @20ali23
