### ISSUE TITLE
Meryem Nurlu [Mobile][Uzaktan][Zorunlu-Gönüllü][5 hafta]

### ISSUE THREAD

**Issue by nurlumeryem** [VB10/staj_2024#39]
Kişisel:
Ad Soyad: Meryem Nurlu
Okul: Erciyes Üniversitesi Bilgisayar Mühendisliği 
Sınıf: Mezun olmam  için son iki dersim kaldı
CV: [Link](https://drive.google.com/file/d/1PcPJFUwaVuMM5J-AS4Gw-6n_25DMRQWR/view?usp=sharing)
Sigorta Okul Karşılıyor : Evet
Merhaba, ben Meryem Nurlu,Erciyes Üniversitesi Bilgisayar Mühendisliği öğrencisiyim. Zorunlu olarak 24 iş günü staj yapmam gerekiyor.İlk zorunlu stajımı Cumhurbaşkanlığında Flutter üzerinden uygulama geliştirerek tamamlamış bulunmaktayım. 1 yıldır Flutter dilinde uygulamalar geliştirmekteyim. Sizi "Hatay'ı Yaşat"projesiyle tanıdım ve ben de depremzedeli bir Hataylı olarak ilgimi çekti ,mutlu oldum.Flutter alanında iş hayatına girmek istiyorum .Sizlerden alacağım fikirler/eğitimler eşliğinde kendimi iş hayatına taşımak istiyorum.Şimdiden ilgi ve alakanız için teşekkür ederim,iyi çalışmalar dilerim.

Geliştirmiş ve geliştirmekte olduğum uygulamalarda kullandığım teknikler

MVVM Structure
Provider Pattern

Tecrübe sahibi olduğum diller ve frameworkler
Flutter

HTML,CSS,Javascript
Firebase, MS SQL

**Comment by VB10** [comment]
Merhaba @nurlumeryem, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nurlumeryem, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nurlumeryem, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by nurlumeryem** [comment]
> Kişisel: Ad Soyad: Meryem Nurlu [mobile][uzaktan][zorunlu/gönüllü][5hafta] Okul: Erciyes Üniversitesi Bilgisayar Mühendisliği Sınıf: Mezun olmam için son iki dersim kaldı CV: [Link](https://drive.google.com/file/d/1PcPJFUwaVuMM5J-AS4Gw-6n_25DMRQWR/view?usp=sharing) Sigorta Okul Karşılıyor : Evet Merhaba, ben Meryem Nurlu,Erciyes Üniversitesi Bilgisayar Mühendisliği öğrencisiyim. Zorunlu olarak 24 iş günü staj yapmam gerekiyor.İlk zorunlu stajımı Cumhurbaşkanlığında Flutter üzerinden uygulama geliştirerek tamamlamış bulunmaktayım. 1 yıldır Flutter dilinde uygulamalar geliştirmekteyim. Sizi "Hatay'ı Yaşat"projesiyle tanıdım ve ben de depremzedeli bir Hataylı olarak ilgimi çekti ,mutlu oldum.Flutter alanında iş hayatına girmek istiyorum .Sizlerden alacağım fikirler/eğitimler eşliğinde kendimi iş hayatına taşımak istiyorum.Şimdiden ilgi ve alakanız için teşekkür ederim,iyi çalışmalar dilerim.
> 
> Geliştirmiş ve geliştirmekte olduğum uygulamalarda kullandığım teknikler
> 
> MVVM Structure Provider Pattern
> 
> Tecrübe sahibi olduğum diller ve frameworkler Flutter
> 
> HTML,CSS,Javascript Firebase, MS SQL

**Comment by VB10** [comment]
Merhaba @nurlumeryem, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nurlumeryem, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nurlumeryem, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nurlumeryem, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nurlumeryem, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nurlumeryem, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nurlumeryem, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @nurlumeryem
