### ISSUE TITLE
Ahmet Can Aytekin [Backend][Adana-Mersin][Zorunlu][4 Hafta]

### ISSUE THREAD

**Issue by aahmetcan01** [VB10/staj_2024#403]
### Kişisel:

- **Ad Soyad:Ahmet Can Aytekin**
- **Okul:Alparslan Türkeş Bilim ve Teknoloji Üniversitesi**
- **Sınıf:3.Sınıf**
- **CV:** [https://drive.google.com/file/d/15UxgEmAKcz64CDP94n4pa7CdHxTzNDdt/view?usp=drivesdk](#)
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):Backendle ilgiliyim Java Spring Boot ile Rest API rahatlıkla çalışabiliyorum.

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları):İlk dönem React projesi yapmıştım Backendle ilgili büyük bir projede bulunamadım eğitimlerim yeni bittiği için.

- **İlgilendiklerim (diller, frameworkler vs):Java Spring&Boot **

**Comment by VB10** [comment]
Merhaba @aahmetcan01, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @aahmetcan01, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @aahmetcan01, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @aahmetcan01, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
