### ISSUE TITLE
Ahmetcan-Aytekin [Backend][Yüzyüze][Zorunlu][4 Hafta]

### ISSUE THREAD

**Issue by aahmetcan01** [VB10/staj_2024#404]
### Kişisel:

- **Ad Soyad:Ahmet Can Aytekin**
- **Okul: Alparslan Türkeş Bilim ve Teknoloji Üniversitesi**
- **Sınıf:3.Sınıf**
-**CV:**[https://drive.google.com/file/d/15UxgEmAKcz64CDP94n4pa7CdHxTzNDdt/view?usp=drivesdk](#)
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):
(Spring& Boot ile Rest API üzerinden rahatlıkla çalışabilirim.
)

### Teknik (Örnek projeler, linkleri ve detayları)
(Geçen dönem React ile arkadaşımın yazdığı Backend kodunu Redux ile API leri bağlamıştım.Geçen dönemden beri Backend eğitimi alıyorum.)

- **İlgilendiklerim (diller, frameworkler vs):
Spring&Boot**

**Comment by VB10** [comment]
Merhaba @aahmetcan01, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @aahmetcan01, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @aahmetcan01, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
