### ISSUE TITLE
Ahmetcan Aytekin [Backend][Yüzyüze][Zorunlu][3-4 Hafta]

### ISSUE THREAD

**Issue by ahmetcan-aytekin** [VB10/staj_2024#407]
Ahmet Can Aytekin

Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi

3 . Sınıf

[https://drive.google.com/file/d/15UxgEmAKcz64CDP94n4pa7CdHxTzNDdt/view?usp=drive_link]

Sigorta Okul Karşılıyor: Evet

Merhaba ben Ahmet Can Aytekin. Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi Bilgisayar Mühendisliği 3. sınıf öğrencisiyim. Bu yaz yapmam gereken zorunlu stajım bulunmaktadır, 20 iş günü sürecektir. Aktif olarak Java, Spring&Boot ,Asp.net Backend ve React Frontend alanlarında projeler geliştirmekteyim.

Java Spring&Boot with Rest API
Asp.Net, EntityFramework, MVC
HTML, CSS, JavaScript, Bootstrap
Firebase, MsSQL, SQLite, Oracle, PL/SQL
C#, Java,

**Comment by VB10** [comment]
Merhaba @ahmetcan-aytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
