### ISSUE TITLE
Seda MALKOÇ [frontend,mobile][uzaktan,yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by Sedamalkocc** [VB10/staj_2024#408]
Ad Soyad: Seda MALKOÇ
Okul: Manisa Celal Bayar Üniversitesi
Sınıf: 3. Sınıf
CV: https://docs.google.com/document/d/1U08Kuyw97tTBkDbQN6G38-yUX9UoVBf-/edit?usp=sharing&ouid=107738799466508399170&rtpof=true&sd=true
Sigorta Okul Karşılıyor: Evet
Kendim Hakkında :
Hem React'ta front-end geliştirmeyle hem de React Native'te mobil uygulama geliştirmeyle ilgileniyorum. Bu alanlarda çalışmak, yaratıcılığımı ve becerilerimi geliştirmek için harika bir fırsat sunuyor. Hem web hem de mobil platformlarda kullanıcı deneyimini iyileştirmek için çaba sarf etmek, benim için gerçekten keyifli bir yolculuk.

Teknik (Örnek projeler, linkleri ve detayları)
İlgilendiklerim (diller, frameworkler vs):
HTML
CSS
SCSS
Bootstrap 5
Javascript
Typescript
JQuery
React
Redux 
React Native
Git
Responsive Tasarım

**Comment by VB10** [comment]
Merhaba @Sedamalkocc, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Sedamalkocc, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Sedamalkocc, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by Sedamalkocc** [comment]
Merhaba closed görünüyor open yapabilir misiniz

**Comment by VB10** [comment]
@Sedamalkocc formata uymamış duruyor kontrol edebilir misin diğer arkadaşların açtıklarıyla
