### ISSUE TITLE
OĞUZHAN ERBAŞ [mobile][yüz yüze][zorunlu][4 hafta]

### ISSUE THREAD

**Issue by erbasdev** [VB10/staj_2024#410]
### Kişisel:

-  Ad Soyad: Oğuzhan ERBAŞ
-  Okul: Karabük Üniversitesi
-  Sınıf: 2
- **CV: https://drive.google.com/file/d/1DUhh9S_7P4bBxEkhQZZJEyMmC_azb0lB/view?usp=sharing
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Hayır

### Kendin Hakkında (kendini anlatmak istersen):

Öncelikle  şimdiden teşekkür ederim değerlendirmeye vakit ayırdığınız için.Ben Yazılım Mühendisliği öğrencisi Oğuzhan Erbaş. Mobile alanına olan ilgim , yaptığım bir gönüllü staj sayesinde oldu. Flutter teknolojisine hayranlık duyuyorum lakin oluşan sisteme şirket içinde uyum sağlamak için elimden ne gelirse yapmaya hazır bir gencim. Şirket içindeki takım çalışması ruhunun bana çok şey katacağını ve kednimi geliştirmek için bulunmaz bir fırsat olduğunu düşündüğüm için yüz yüze staj yapmak istiyorum.Sosyal becerilerime çok fazla güveniyorum.

### Teknik (Örnek projeler, linkleri ve detayları):
Mamak Füzyon Ulaşım App:
Flutter Türkiye'nin desteğiyle düzenlenen Flutter Night etkinliğinde 1 gece boyunca çalışan bir programlama etkinliğinde tasarladığımız ve ekiple birlikte kodladığımız bir uygulama.

- **İlgilendiklerim (diller, frameworkler vs): Flutter,Dart

**Comment by VB10** [comment]
Merhaba @erbasdev, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
