### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by MehmetKucukOfficial** [VB10/staj_2024#419]
### Kişisel:

- **Ad Soyad:** Mehmet Küçük
- **Okul:** Celal Bayar Üniversitesi
- **Sınıf:** 3. Sınıf
- **CV:** [(https://drive.google.com/file/d/1wzYRYYGOfmklIsPyen__M_aFVAJ3HBDS/view)](https://drive.google.com/file/d/1wzYRYYGOfmklIsPyen__M_aFVAJ3HBDS/view)(#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Merhaba ben Mehmet Küçük. Yazın zorunlu stajım için staj yeri arayışındayım. İzmirde yaşıyorum. Web ve mobil alanlarında staj yeri arıyorum. İlk tercihim şirket kültürünü öğrenebilmek adına yüz yüze staj yapmak ama İzmir dışındaki şirketler ile uzaktan stajda yapabilirim. 

### Teknik (Örnek projeler, linkleri ve detayları)

Projelerime github hesabımdan ulaşabilirsiniz.

- **İlgilendiklerim (diller, frameworkler vs):**
- Python
- Sql
- Javascript
- Java
- C#
- Node.js
- Vue.js
- Html
- CSS
- Bootstrap
- Flutter
- Kotlin

**Comment by VB10** [comment]
Merhaba @MehmetKucukOfficial, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @MehmetKucukOfficial, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @MehmetKucukOfficial, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @MehmetKucukOfficial, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
