### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by ayukse1** [VB10/staj_2024#429]
Kişisel:
Ad Soyad: ['Muzaffer Arda Yüksel']
Okul: ['İzmir Yüksek Teknoloji Enstitüsü']
Sınıf: ['Yeni Mezun']
CV: ['https://drive.google.com/file/d/16UzwOgS4vmvX7IW4XBmTDioF3N0zvbZq/view?usp=sharing']
Sigorta Okul Karşılıyor (Evet/Hayır): ['Hayır']
Kendin Hakkında (kendini anlatmak istersen):
Sayın İlgililer,

Ben İzmir Yüksek Teknoloji Enstitüsü lisans ve yüksek lisans mezunlarından Muzaffer Arda Yüksel. Mimarlık Fakültesi, Şehir ve Bölge Planlama bölümü mezunuyum. Bölümüm kaynaklı tasarım konusunda farklı projelerde bulundum. Mezuniyetimden sonra UX/UI alanında çalışmalara devam ettim.

Kısaca kendimden bahsetmem gerekirse; takım çalışmasına yatkın, sorumluluk alabilen, çözüm odaklı, neşeli ve tutkulu biri olduğumu söyleyebilirim. Alanımda daha yeni olmama rağmen hedef odaklı biri olduğum için sizlere kısa sürede katkı sağlayacağıma inancım tamdır. Github linkimden (https://github.com/ayukse1) lokalde yapmış olduğum projeleri inceleyebilirsiniz.

İlerleyen dönemde en büyük arzum bir staj imkanıyla sektöre adım atmaktır.

İyi günler, iyi çalışmalar dilerim.
Saygılarımla,

Teknik (Örnek projeler, linkleri ve detayları)
İlgilendiklerim (diller, frameworkler vs): ['HTML', 'CSS', 'Bootstrap' 'JavaScript']

**Comment by VB10** [comment]
Merhaba @ayukse1, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ayukse1, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ayukse1, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ayukse1, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ayukse1, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ayukse1, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ayukse1, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ayukse1, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
