### ISSUE TITLE
Zeynep Bayram [backend,frontend,mobile][yüzyüze,uzaktan][zorunlu][4 hafta]

### ISSUE THREAD

**Issue by Zeynep-Bayram** [VB10/staj_2024#432]
### Kişisel:

- **Zeynep Bayram**
- **Okul: Manisa Celal Bayar Üniversitesi**
- **Sınıf: 2**
- **CV:** https://drive.google.com/file/d/1kncsMOPF9yVKkqro2PYLGtvbfNXzt3Gl/view?usp=sharing
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen): Şuanda web geliştirme alanında backend ile ilgilenmekteyim. Django ile web siteleri yapıyorum.

- **İlgilendiklerim (diller, frameworkler vs): Django , Python , Java

**Comment by VB10** [comment]
Merhaba @Zeynep-Bayram, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
