### ISSUE TITLE
Gökhan Üstünyer [backend,data-science,database][uzaktan,yüz-yüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by gokhanustunyer** [VB10/staj_2024#435]
### Kişisel:

- Gökhan Üstünyer
- İstinye Üniversitesi (100% Burslu)
- Yazılım Mühendisliği Üçüncü Sınıf
- CV: https://drive.google.com/file/d/1kBZedUE0I0o8yL42mxgRsbEGTgyBRjVr/view
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
Backend ve data ile ilgilenen bir yazılım mühendisliği öğrencisiyim.

### Teknik (Örnek projeler, linkleri ve detayları)
github ve özgeçmişimde projelerim detaylı bir şekilde mevcut.

- **İlgilendiklerim (diller, frameworkler vs):**
C, C++, C#, Python, Javascript, OOP, .NET Core, Asp.NET Core (MVC/Web API), SQL Server, MySQL, Ajax, Entity Framework Core, Angular, HTML, CSS

**Comment by VB10** [comment]
Merhaba @gokhanustunyer, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
