### ISSUE TITLE
NEŞE AKKOL [uzaktan][mobile,backend][gönüllü][6hafta]

### ISSUE THREAD

**Issue by NESE-AKKOL** [VB10/staj_2024#438]
### Kişisel:

neşe akkol
lefke avrupa üniversitesi
3,sınıf- 
**Sigorta Okul Karşılıyor** (Evet) tam burslu

**Comment by VB10** [comment]
Merhaba @NESE-AKKOL, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
