### ISSUE TITLE
Eda Nur Mutlu [backend,mobile][uzaktan,yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by edamuutlu** [VB10/staj_2024#44]
### Kişisel:

- **Ad Soyad:** Eda Nur Mutlu
- **Okul:** Marmara Üniversitesi Bilgisayar Mühendisliği
- **Sınıf:** 3. sınıf
- **CV:**  [Eda-Nur-Mutlu-CV.pdf](https://github.com/VB10/staj_2024/files/14087730/Eda-Nur-Mutlu-CV.pdf)
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendim Hakkında:
Merhaba, ben Eda Nur Mutlu. Marmara Üniversitesi Bilgisayar Mühendisliği 3. sınıf öğrencisiyim. 2. sınıf zorunlu yaz stajımı Sigorta Bilgi ve Gözetim Merkezi şirketinde yazılım stajyeri olarak tamamladım. Kendimi Java, Spring Boot, JUnit test, MySQL, Oracle, MsSQL gibi teknolojilerle geliştirmekteyim.

### Teknik
Sigorta Yönetim Sistemi
https://github.com/edamuutlu/Insurance-Management-Project
Sosyal Medya Otomasyonu
https://github.com/edamuutlu/Social-Media-Automation

- **İlgilendiklerim:** 
- Java, Spring Boot, JUnit Tests, Backend, Flutter, MySQL, Oracle, MSSQL.

**Comment by VB10** [comment]
Merhaba @edamuutlu, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @edamuutlu, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @edamuutlu, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @edamuutlu, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @edamuutlu, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @edamuutlu, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @edamuutlu, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
