### ISSUE TITLE
Neşe Akkol [uzaktan][mobile,backend][gönüllü][6hafta]

### ISSUE THREAD

**Issue by NESE-AKKOL** [VB10/staj_2024#440]
### Kişisel:
- **Ad Soyad:** neşe akkol
- **Okul:** lefke avrupa üniversitesi 
- **Sınıf:** 3
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  tam burslu

**Comment by VB10** [comment]
Merhaba @NESE-AKKOL, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
