### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by emirhanarslann** [VB10/staj_2024#446]
### Kişisel:

- **Ad Soyad:** EMİRHAN ARSLAN
- **Okul:** FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ 
- **Sınıf:** 3. SINIF
- **CV:** [Google Drive Linki veya pdf linki](#)  https://drive.google.com/file/d/1DqbUFvQUdoLtjW4aZTM_prLkuxPXPbvW/view
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  EVET

### Teknik (Örnek projeler, linkleri ve detayları) Mimari ve iç mimari projelerim, ; https://drive.google.com/file/d/1DqbUFvQUdoLtjW4aZTM_prLkuxPXPbvW/view

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @emirhanarslann, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emirhanarslann, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emirhanarslann, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
