### ISSUE TITLE
Mehmet Ali Çuhacı [backend][yüzyüze][uzaktan][zorunlu][4hafta]

### ISSUE THREAD

**Issue by mehmetcuhaci** [VB10/staj_2024#448]
### Kişisel:

- **Ad Soyad: Mehmet Ali Çuhacı
- **Okul: İstanbul Arel Üniversitesi
- **Sınıf: 2
- **CV:** [[Özgeçmişim](https://drive.google.com/file/d/1BDDDbOT4LGIwEpoVd8Bc-5sILd2AwJz3/view?usp=drive_link)](#)
- **Sigorta Okul Karşılıyor** :  Evet

### Kendin Hakkında ():

Gerekli her şeyi özgeçmişimde bulabilirsiniz.

### Teknik (Örnek projeler, linkleri ve detayları)
https://github.com/mehmetcuhaci
- **İlgilendiklerim : .NET C#

**Comment by VB10** [comment]
Merhaba @mehmetcuhaci, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
