### ISSUE TITLE
Abdulkadir Erbaş [backend, mobile][uzaktan, yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by KadirErbas** [VB10/staj_2024#450]
### Kişisel:

- Ad Soyad: Abdulkadir ERBAŞ
- Okul: Fırat Üniversitesi
- Sınıf: 3.Sınıf
- CV: [https://drive.google.com/file/d/1rOTxe2mRl1u07d_AAZNJBK2YuQ6J1Puh/view?usp=sharing](#)
- Sigorta Okul Karşılıyor: Evet

### Kendin Hakkında:
   
- Hızlı öğrenen ve çözüm odaklı bir yazılım mühendisliği öğrencisiyim. 
- Problem çözmeyi ve yeni teknolojileri keşfetmeyi seviyorum. 
- Ekip çalışmasına yatkınım ve farklı bakış açılarına açığım. insanlarla iyi geçinirim. 
- Problemlerle uğraşmayı severim. 
- Boş zamanlarımda enstrüman çalarım, yürüyüş yaparım ve film izlerim.

### Teknik (Örnek projeler, linkleri ve detayları)

- c#, java, python, django, html, css, microsoft SQL gibi teknolojilerle daha önceden uğraştım. 
- Django ile basit web sitesi geliştirdim. 
- C# ile masaüstü pansiyon otomasyonu uygulamsı geliştirdim. 
- Şuanda .net ve react native öğreniyorum.

**Comment by VB10** [comment]
Merhaba @KadirErbas, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @KadirErbas, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
