### ISSUE TITLE
BARAN ÇİÇEK [FRONTEND, BACKEND][BURSA][YÜZ YÜZE, UZAKTAN][fark etmez, uzun dönem staj olabilir]

### ISSUE THREAD

**Issue by Rainclover8** [VB10/staj_2024#452]
### Kişisel:

- **Baran çiçek:**
- **şüiaal(lise) mezun oldum
- **Sigorta Okul Karşılıyor** (Evet/Hayır): hayır

### Kendin Hakkında (kendini anlatmak istersen):
Merhaba ben Baran 19 yaşındayım full stack web developerim yazılıma cocukken baslamıştım ve ilerlettim belli bir süre kendimi geliştirdikten sonra özel bir eğitim kurumundan eğitim alıp ilerledim. Üniversite kazandım fakat gitmemeyi tercih ettim çünkü kendimi bu özel kurumda daha çok geliştirebileceğimi düşündüm şu ana kadar da pişman değilim.

Github'ımda örnek projelerimi görebilirsiniz 

- **İlgilendiklerim 
ileri düzey (html css javascript react python djnago bootstrap 

temel düzey(swift .core) ):**

**Comment by VB10** [comment]
Merhaba @Rainclover8, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
