### ISSUE TITLE
BARAN ARMUTLU ["mobile", "backend", "frontend", "game"]["yüzyüze"]["zorunlu"]["6hafta"]

### ISSUE THREAD

**Issue by Ephrow** [VB10/staj_2024#453]
### Kişisel:

- **Ad Soyad:*BARAN ARMUTLU*
- **Okul:*Ataşehir Adıgüzel MYO*
- **Sınıf:*2.sınıf*
- **CV:** [https://drive.google.com/file/d/1IUn_dBJ53NQPNbHZ2-hxCZwmWoqivDs1/view?usp=sharing](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Net bir bilgiye sahip değilim.

Mail yoluyla ulaşırsanız çok memnun olurum.

**Comment by VB10** [comment]
Merhaba @Ephrow, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ephrow, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by Ephrow** [comment]
> ### Kişisel:
> * **Ad Soyad:** _BARAN ARMUTLU_
> * **Okul**:** _Ataşehir Adıgüzel MYO_
> * **Sınıf:_2.sınıf_
> * **CV:** [https://drive.google.com/file/d/1IUn_dBJ53NQPNbHZ2-hxCZwmWoqivDs1/view?usp=sharing](#)
> * **Sigorta Okul Karşılıyor** (Evet/Hayır): Net bir bilgiye sahip değilim.
> 
> Mail yoluyla ulaşırsanız çok memnun olurum.



> ### Kişisel:
> * **Ad Soyad:_BARAN ARMUTLU_
> * **Okul:_Ataşehir Adıgüzel MYO_
> * **Sınıf:_2.sınıf_
> * **CV:** [https://drive.google.com/file/d/1IUn_dBJ53NQPNbHZ2-hxCZwmWoqivDs1/view?usp=sharing](#)
> * **Sigorta Okul Karşılıyor** (Evet/Hayır): Net bir bilgiye sahip değilim.
> 
> Mail yoluyla ulaşırsanız çok memnun olurum.

**Comment by VB10** [comment]
Merhaba @Ephrow, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ephrow, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ephrow, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Ephrow, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
