### ISSUE TITLE
Baran Armutlu ["mobile", "frontend", "game"]["yüzyüze"]["zorunlu"]["6hafta"]

### ISSUE THREAD

**Issue by Ephrow** [VB10/staj_2024#454]
### Kişisel:

- **Ad Soyad:** BARAN ARMUTLU
- **Okul:** Ataşehir Adıgüzel MYO
- **Sınıf:** 2.sınıf
- **CV:** [[https://drive.google.com/file/d/1IUn_dBJ53NQPNbHZ2-hxCZwmWoqivDs1/view?usp=sharing](https://github.com/VB10/staj_2024/issues/453#)](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Net bir bilgiye sahip değilim.

**Comment by VB10** [comment]
Merhaba @Ephrow, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
