### ISSUE TITLE
Seymen Can Aydoğan [database,big-data,data-science,backend][uzaktan,yüzyüze][zorunlu][4hafta] 

### ISSUE THREAD

**Issue by seymencanaydogan** [VB10/staj_2024#455]
### Kişisel:

- **Ad Soyad:** Seymen Can Aydoğan 
- **Okul:** Sakarya Uygulamalı Bilimler Üniversitesi
- **Sınıf:** 3.Sınıf
- **CV:** https://github.com/seymencanaydogan/seymencanaydogan-CV/blob/main/seymencanaydogan_CV.pdf(#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendin Hakkında (kendini anlatmak istersen):

Ben Seymen Can. 20 yaşında, Sakarya Uygulamalı Bilimler Üniversitesi'nde 3. sınıf bilgisayar mühendisliği öğrencisiyim. Makine öğrenmesi, görüntü işleme gibi alanlarda kendimi geliştiriyorum. Python, C++, C#, SQL gibi dillerde iyi derecede yetenekliyim. Ayrıca web ve mobil mimarisinde de deneyimim var. Boş zamanlarımda kitap okumayı ve dizi izlemeyi seviyorum. Yapay Zeka Öğrenci Topluluklarına aktif olarak katılarak sektöre hazırlanıyorum. Ayrıca UDEMY, Cambridge gibi platformlardan kurslar alıyorum. Şu anda kendimi daha da geliştirebileceğim, sektörde değer kazanmamı sağlayacak ve alanı daha iyi anlamama yardımcı olacak staj teklifleri arıyorum. 

### Teknik (Örnek projeler, linkleri ve detayları):

Projelerime github üzerinden ulaşabilirsiniz.  [https://github.com/seymencanaydogan]

- **İlgilendiklerim (diller, frameworkler vs):** Python, C++, C#, SQL, Django, ASP.NET

**Comment by VB10** [comment]
Merhaba @seymencanaydogan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
