### ISSUE TITLE
ÖZGÜR OKAN-ÖZDAL["Back-end","Front-end"]["uzaktan", "yüzyüze"]["gönüllü"]["4hafta","6hafta"]

### ISSUE THREAD

**Issue by ozgurokan** [VB10/staj_2024#457]
### Kişisel:

- Özgür Okan Özdal
- Yıldız Teknik Üniversitesi Fizik Bölümü
- 3.Sınıf
- https://docs.google.com/document/d/14dZa4CSpp3PvWAJbhG01GUGaUX7xanaWNckCm5DOrBw/edit?usp=sharing
- Hayır

### Kendin Hakkında (kendini anlatmak istersen):

HTML,CSS,JavaScript öğrendikten sonra Java ve Spring boot kullanarak back-end geliştirmeye başladım. Şu an hala back-edn alanın spring boot ile kendi kendime projeler geliştirmeye devam ediyorum

### Teknik (Örnek projeler, linkleri ve detayları)

- Java 18+, Spring Boot 3+, MySQL, HTML, CSS,JavaScript ve React

**Comment by VB10** [comment]
Merhaba @ozgurokan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ozgurokan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ozgurokan, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @ozgurokan
