### ISSUE TITLE
BİLAL AÇIKGÖZ / [Artificial Intelligence] / [Uzaktan][Zorunlu][4 hafta]

### ISSUE THREAD

**Issue by BilalAcikgoz** [VB10/staj_2024#459]
### Kişisel:

- BİLAL AÇIKGÖZ
- Sakarya Üniversitesi 
- 4.Sınıf
- CV Link: https://drive.google.com/drive/u/0/mobile/folders/1-519saliv0ruDeMG0CwuqADcCWQL3Ke7/1-C78NL0KQH0B-ZGlbBMRExT_NhjViaMV?utm_source=tr&utm_medium=button&utm_campaign=web&utm_content=gotodrive&utm_term=carousel&usp=about_start&urp=https://www.google.com/&sort=13&direction=a

**Comment by VB10** [comment]
Merhaba @BilalAcikgoz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @BilalAcikgoz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @BilalAcikgoz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
