### ISSUE TITLE
Emre DOĞAN[cyber-security,backend,fronted][uzaktan][gönüllü][4hafta,6hafta]

### ISSUE THREAD

**Issue by emreefedogan** [VB10/staj_2024#46]
### Kişisel:

- **Ad Soyad:** Emre DOĞAN
- **Okul:** Karabük Üniversitesi
- **Sınıf:** 4.Sınıf
- **CV:** [https://drive.google.com/file/d/1ratsbbfnjgzaOllS6CFD3ZGXc2_lTRol/view?usp=sharing](#) 
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Hayır

### Kendin Hakkında (kendini anlatmak istersen):
Merhabalar ben Emre DOĞAN,  kendimi siber güvenlik ve web yazılımı alanlarında geliştiriyorum. (2019-2024) yıldır Siber Güvenlik alanında araştırmalar yapıyorum.  Jotform Yazılım AŞ, SecOps Engineer olarak staj yaptım. Kırıkkale Deneyap Atölyelerinde Siber Güvenlik Eğitimi verdim. Şu anda da Karabükte Siber Güvenlik eğitimleri vermeye devam ediyorum. Hızlı öğrenip, hızlı adapte olabiliyorum.  

### Teknik (Örnek projeler, linkleri ve detayları)
Geliştiriciler için zaafiyetli kodları öğrenmeleri ve test etmelerini amaçlayan bir web yazılımı projesi geliştirdim. (Jotform)
PHP Laravel, React.js, Docker teknolojilerini kullandım.

- **İlgilendiklerim (diller, frameworkler vs):**

- PHP Laravel,
- React.js,
- Node.js,
- C / C#

**Comment by VB10** [comment]
Merhaba @emreefedogan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emreefedogan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emreefedogan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emreefedogan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emreefedogan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emreefedogan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emreefedogan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emreefedogan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
