### ISSUE TITLE
İlyas Güner [backend,frontend,data-science][uzaktan][zorunlu][6hafta]

### ISSUE THREAD

**Issue by ilyasguner** [VB10/staj_2024#466]
### Kişisel:

- **Ad Soyad: İlyas Güner
- **Okul: Manisa Celal Bayar Üniversitesi Yazılım Mühendisliği Bölümü
- **Sınıf: 3. Sınıf
- **CV:** [https://drive.google.com/file/d/1R6cvTKpEWFJIp9FFNU0N_24yXdUTzHWR/view?usp=sharing](#)
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):

C# kullanarak Asp.Net ile backend geliştiryorum.Bunun yanı sıra html/css ve javascript ile frontend geliştirme yapıyorum.Python ile makine öğrenmesi ve derin öğrenme alanlarında projelerim var.

### Teknik (Örnek projeler, linkleri ve detayları)

Asp.Net Core ile Entity Framework kullanarak yaptığım çift admin panelli blog sitesi 
Link=>https://github.com/ilyasguner/Core__Proje

Asp.Net Core ile Entity Framework kullanarak yaptığım freelance iş sitesi
Link=>https://github.com/ilyasguner/Freelance_Asp.Net_Core_Project

Python İle trendyoldan çektiğim veriler ile eğittiğim makine öğrenmesi algoritması ve bu algoritmaları servislediğim telefon fiyat tahmin projesi
Link=>https://github.com/ilyasguner/Telephone-Price-Prediction

1. Sınıfta yaptığım C# ile işyeri personel takip form uygulaması
Linki=>https://github.com/ilyasguner/Company-Project

**Comment by VB10** [comment]
Merhaba @ilyasguner, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
