### ISSUE TITLE
BURAK-AKÇA [MOBİL, BACKEND][UZAKTAN/YAKINDAN][ZORUNLU][6 HAFTA]

### ISSUE THREAD

**Issue by lburakakca** [VB10/staj_2024#468]
### Kişisel:

- **Ad Soyad: Burak Akça**
- **Okul: Abdullah Gül Üniversitesi**
- **Sınıf: 3. Sınıf**
- **CV:** [[Google Drive Linki veya pdf linki](https://drive.google.com/file/d/1GynIQaxjVQDcS516dpvmbdFKpLYnhnrY/view?usp=sharing)](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Abdullag Gül Üniversitesi 3. sınıf Bilgisayar Mühendisliği öğrencisiyim. Ekip çalışmalarında iyiym bir çok projede startup da bulundum ve destek sağladım. Tubitak 2209-A kapsamında destek aldım bu sene TEKNOFEST sanayide dijital teknolojiler alanında takımımla yarışıyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

1)CardioWell: https://github.com/lburakakca/cardiowell
Tubitak 2209-A kapsamında destek alan projem
2) HR-Menagment System: https://github.com/lburakakca/hr-management-system
İnsan kaynakları yönetim sistemi. 2. sınıf dönem projemdi. Backend ve SQL bazlı projelerimden biri.

- **İlgilendiklerim (diller, frameworkler vs): java, javascript, typescript, C, C#, python, SQL, Flutter**

**Comment by VB10** [comment]
Merhaba @lburakakca, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @lburakakca, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @lburakakca, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @lburakakca, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @lburakakca, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @lburakakca
