### ISSUE TITLE
Mustafa Sürmeli [mobile, backend, data-science][uzaktan, yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by mustafasurmeli** [VB10/staj_2024#470]
**Kişisel:**
**Ad Soyad:** Mustafa SÜRMELİ
**Okul:** Kocaeli Üniversitesi 
**Sınıf:** 3. Sınıf
**CV:** [[Google Drive Linki veya pdf linki](https://drive.google.com/file/d/170ItkiQtPFRkxVLDHCUhNap2hG9j8Kac/view?usp=sharing)](#)
**Sigorta Okul Karşılıyor (Evet/Hayır):** Evet
**Kendin Hakkında (kendini anlatmak istersen):**
Kocaeli Üniversitesi B
ilgisayar Mühendisliği 3.sınıf öğrencisiyim. Takım çalışmasına yatkın, azimli ve hırslıyım. Backend alanında kendimi geliştirmeye gayret gösteriyorum, bu alanda geliştirdiğim bireysel projelerim var. Ayrıca makine öğrenmesi, CV alanlarında çalışmalarım var ve TEKNOFEST yarışmasında TİKA ve İnsanlık Yararına alanlarında yarışıyorum.

**Teknik (Örnek projeler, linkleri ve detayları):**
https://github.com/mustafasurmeli
İlgilendiklerim (diller, frameworkler vs): Java, Go, C,  Python, SQL, Kotlin

**Comment by VB10** [comment]
Merhaba @mustafasurmeli, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
