### ISSUE TITLE
Furkan Kuyumcu [game,data-science][uzaktan,yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by kazanuka** [VB10/staj_2024#473]
### Kişisel:

- Furkan Kuyumcu
- Tekirdağ Namık Kemal Üniversitesi
- 2.Sınıf
- https://drive.google.com/file/d/1jKShTJGDCRU-CA3vDg-NBXpvwO_pJIsO/view?usp=sharing
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
Küçüklüğümden beri bilgisayar programlamaya ve elektroniğe ilgi duyuyorum. Düzenli olarak ilk kod yazışım lisede robotik yarışmalarında Arduino kodlamamla başladı. Genel olarak veri bilimi ve görüntü işleme konularına karşı meraklıyım. Okulumdaki IEEE topluluğunda Computer Society başkanı olarak görev almaktayım. Ayrıca 42 İstanbul yazılım okulunun havuz elemesini geçerek ana eğitime katılmaya hak kazandım. Bireyin kendisini durmaksızın geliştirmesi gerektiğine inanıyor, kendimi de her geçen gün geliştirmeye çabalıyorum. 

### Teknik (Örnek projeler, linkleri ve detayları)

- Özellikle görüntü işleme alanında yoğunlaşmak için Python üzerinden OpenCV kütüphanesini öğrenme aşamasındayım. Bu bağlamda yüz algılama ve yüz tanıma projelerimi geliştirmeye çalışıyorum. (https://github.com/kazanuka/facedetection)
- Geçtiğimiz sene bir arkadaşımla beraber .net üzerinden Selenium kütüphanesi kullanarak Passolig üzerinden bilet alabilen bir otomasyon yazdık. Amacımız hem kendimizi test etmek, hem de gelecekteki potansiyel online satış yöntemlerini öğrenmekti. (https://github.com/kazanuka/Passo-Bot)
- Unity üzerinden demo denilebilecek oyun projelerinde bulundum. Oyunların büyüklüğü fazla olmamakla beraber Unity'nin temel dinamiklerini biliyorum.

**Comment by VB10** [comment]
Merhaba @kazanuka, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
