### ISSUE TITLE
Mahsun SAYAK ["mobile", "backend"]["uzaktan", "yüzyüze"]["zorunlu"]["6hafta"]

### ISSUE THREAD

**Issue by M-SYK** [VB10/staj_2024#48]
### Kişisel:

- **Ad Soyad: Mahsun SAYAK**
- **Okul: Atatürk Üniversitesi**
- **Sınıf: 4. Sınıf**
- **CV:** [Mahsun_SAYAK_CV (3).pdf](https://github.com/VB10/staj_2024/files/14087366/Mahsun_SAYAK_CV.3.pdf)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Atatürk Üniversitesi Bilgisayar Mühendisliği(İngilizce) bölümü 4. sınıf öğrencisiyim. Bir yıl İngilizce hazırlık bölümü ile birlikte 4 yıl boyunca okulda gördüğüm yazılım dilleri üzerine kendimi geliştirmeye çalıştım. Okuldan ayrı olarak BTK-Akademi, Udemy ve Patika Dev gibi platformlar üzerinden eğitimler ve sertifikalar aldım. Öğrenme ve kendini geliştirme konusunda istekli birisiyim.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**
- Kotlin
- C#
- SQL
- Python

**Comment by VB10** [comment]
Merhaba @M-SYK, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @M-SYK
