### ISSUE TITLE
YUSUF FURKAN AYYILDIZ[MOBİLE][YÜZ YÜZE][ZORUNLU][4 HAFTA]

### ISSUE THREAD

**Issue by yfurkanayyildiz** [VB10/staj_2024#496]
### Kişisel:

- **Ad Soyad:** Yusuf Furkan Ayyıldız
- **Okul:** Karabük Üniversitesi
- **Sınıf:** 4. Sınıf
- **CV:** [https://drive.google.com/file/d/1kMNFi-yqF2HlnmyZT0aimVDkgHYWO2N6/view?usp=share_link](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

**HAKKIMDA**

Merhaba, ben Yusuf Furkan Ayyıldız, Karabük Üniversitesi Bilgisayar Mühendisliği öğrencisiyim ve 2022 yaz aylarında Work and Travel programına katıldım ve ingilizce konuşma becerilerimi geliştirdim. Şu anda iOS geliştirici olmak için yoğun bir şekilde eğitim alıyorum. Son 2 aydır bu alanda projeler geliştiriyorum ve kendimi bu alanda geliştirmeye odaklıyım.

**PROJELER**

**Authentication uygulaması**

Swift ile authentication uygulaması geliştirdim.  Bu uygulamayı geliştirirken firebase veri tabanını kullandım.

**Yetkinilklerim**

Swifft
C & C#
Java
HTML - CSS - JS
Laravel
Adobe illustrator
Adobe Photoshop

**Comment by VB10** [comment]
Merhaba @yfurkanayyildiz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
