### ISSUE TITLE
Reyhan Türkkal [mobile][yüzyüze,uzaktan][zorunlu][6hafta]

### ISSUE THREAD

**Issue by reyhanturkkal** [VB10/staj_2024#499]
### Kişisel:

- **Ad Soyad:** Reyhan Türkkal
- **Okul:** Kırklareli Üniversitesi
- **Sınıf:** 3
- **CV:** [https://drive.google.com/file/d/1tMQJ5V0rdm-tuzH7bJ0_HuroV6V_kuXp/view?usp=drive_link](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Hakkımda:

Kotlin tabanlı Android geliştirmeyle ilgileniyorum. Çeşitli projeleri tamamlayarak becerilerimi güçlendirmeye odaklandım. Profesyonel bir alanda pratik deneyim kazanmaya ve aktif olarak katkıda bulunmaya istekliyim.

**İlgilendiklerim (diller, frameworkler vs):** Javascript, Kotlin, Java, Python, Firebase, MySQL, SQLite, React.js

Portfolyo link: [https://reyhanturkkal.github.io/my-portfolio/](#)

##### Weather App 

MVVM mimarisi kullanımı
Retrofit ve Gson ile RESTful API etkileşimi
OpenWeather API entegrasyonu
Link: [https://github.com/reyhanturkkal/Weather-App](#)
 
##### Recipes App 

Room kütüphanesi ile Local veritabanı yönetimi
Görüntü işleme ve yükleme için Glide kütüphanesi
Link: [https://github.com/reyhanturkkal/Recipes_App](#)

##### ChatGPT 

OpenAI API ile text prompt kullanımı
HTTP isteklerinin OKHttp kütüphanesiyle gerçekleştirilmesi
Link: [https://github.com/reyhanturkkal/chatgpt-app](#)

**Comment by VB10** [comment]
Merhaba @reyhanturkkal, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @reyhanturkkal, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
