### ISSUE TITLE
Mehmet Ali SALEP[Data Science, Data Analyst, API and API Test][STAJ YERİ][Uzaktan, Yüzyüze][20 iş günü]

### ISSUE THREAD

**Issue by malisalepp** [VB10/staj_2024#507]
### Kişisel:

- Ad Soyad: Mehmet Ali SALEP
- Okul: Sakarya Uygulamalı Bilimler Üniversitesi
- 3. Sınıf
- CV: https://drive.google.com/file/d/1lGLL9Nns59fznA1AyI2ARUgWRh_9-ouY/view?usp=sharing
- Sigorta Okul Karşılıyor : Evet
- linkedin : https://www.linkedin.com/in/mehmet-ali-salep/

Adım Mehmet Ali SALEP, Sakarya Uygulamalı Bilimler Üniversitesi Bilgisayar Mühendisliği 3. sınıf öğrencisiyim. Başlangıçta Sakarya Üniversitesi'nde Elektrik-Elektronik Mühendisliği okuyordum; hazırlık ve ilk iki sınıfımı tamamladıktan sonra 2023 yazında Sakarya Uygulamalı Bilimler Üniversitesi Bilgisayar Mühendisliği bölümüne geçiş yaptım. Elektrik elektronik mühendisliği sürecimde IEEE SAÜ çatısı altında 2022 Teknofest'te İnsansız Kara Aracı kategorisinde 4. olduk.

Şu anda kendimi Veri Bilimi alanında geliştirmek istiyorum ve bu yönde çeşitli dersler alıyorum. Python diline orta düzeyde hakimim. Veri Bilimi için yaygın olarak kullanılan Numpy ve Pandas kütüphaneleri hakkında da orta düzeyde bilgi sahibiyim. Şu anda devam etmekte olan Teknofest Sağlıkta Yapay Zeka kategorisinde bir ekibin parçası olarak çalışmaktayım. Bu proje kapsamında görüntü işleme alanında yaygın olarak kullanılan OpenCV, Tensorflow ve Keras kütüphaneleri üzerinde kendimi geliştirmeye odaklanıyorum.

İlgilendiklerim (diller, frameworkler vs): Python, C, C++, C#, Html, Css, JavaScript

**Comment by VB10** [comment]
Merhaba @malisalepp, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @malisalepp, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @malisalepp, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @malisalepp, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @malisalepp, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @malisalepp, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
