### ISSUE TITLE
Eren Torlak [data-science][yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by erentorlak** [VB10/staj_2024#508]
### Kişisel:

- **Ad Soyad:** Eren Torlak 
- **Okul:** Gebze Teknik Üniversitesi
- **Sınıf:** 3.sınıf
- **CV:** https://drive.google.com/file/d/1990XiuVelwgVOtX10DncKhjje_kKOLD_/view?usp=sharing
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Yapay zeka ve veri bilimi üzerine yaklaşık 2 senedir kendimi geliştiriyorum. Derin öğrenme ve makine öğrenmesi algoritmalarını derinlemesine araştırdım ve implemente ettim. 

### Teknik (Örnek projeler, linkleri ve detayları)

CineMatch : Film önerme ve benzer zevkte insanları eşleştirme platformu -> https://github.com/erentorlak/CineMatch

Diğer projeler için -> https://github.com/erentorlak

- **İlgilendiklerim (diller, frameworkler vs):**
- Python, C++, SQL
- Pytorch, Sklearn, Seaborn, Pandas
- Docker, Mongodb

**Comment by VB10** [comment]
Merhaba @erentorlak, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
