### ISSUE TITLE
İLKNUR-DONDURMA [Web Front-End , Mobil Front-End ][uzaktan,yüzyüze][zorunlu][4 hafta]

### ISSUE THREAD

**Issue by ilknurdondurma** [VB10/staj_2024#513]
### Kişisel:

- **Ad Soyad:**İlknur Dondurma
- **Okul:**Konya Teknik Üniversitesi
- **Sınıf:**4
- **CV:** [https://drive.google.com/file/d/1MVBT50eNPeZAqtVlWpEdIcZ_P6YCazMZ/view?usp=drive_link](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
1 yıl mobil 2 yıl web teknolojileri alanında kendimi geliştirdim. Çabuk adapte olur hızlı öğrenirim.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):** HTML, CSS, Javascript, ReactJS , Bootstrap ,TailwindCSS, , Flutter , C#, Asp.net Core(SignalR)
- 
- Projelerim:
- --> Elden Kiralama Uygulaması (backend ve front-end bana ait)(mobil+web)
- --> Okuma Geliştirme Projesi Web Tasarımı
- -->Yemek Sipariş Uygulaması Web Tasarımı

**Comment by VB10** [comment]
Merhaba @ilknurdondurma, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
