### ISSUE TITLE
Beyza Keçeci [mobile,frontend][uzaktan,yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by beyzakececi** [VB10/staj_2024#52]
### Kişisel:

- **Ad Soyad: Beyza Keçeci**
- **Okul: Kocaeli Üniversitesi**
- **Sınıf: 3.Sınıf**
- **CV:** [beyza_kececi_CV.pdf](https://github.com/VB10/staj_2024/files/14087706/beyza_kececi_CV.pdf)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Merhaba, ben Beyza Keçeci. Kocaeli Üniversitesi Yazılım Mühendisliği 3. sınıf öğrencisiyim. Okul takımımın yanında mobil alanında kendimi geliştirmekteyim. Kendimi daha fazla geliştirmek ,sektör tecrübesi kazanmak ve okulumun da zorunlu kılması nedeniyle staj yapmak istiyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

[Blabla Chat App](https://github.com/beyzakececi/BlaBlaChat) Java ve Firebase kullanılan bir sohbet uygulaması.Login, Register işlemlerinide token kullanılmıştır.

[Bilimsel Hesap Makinesi](https://github.com/beyzakececi/Scientific-Calculator)  Kotlin ve MathParser kütüphanesi kullanılmıştır.

[Catch The Darwin Oyunu](https://github.com/beyzakececi/CatchTheDarwin) Kotlin ile yazılmıştır

- **İlgilendiklerim (diller, frameworkler vs):**
Kotlin, Java, Flutter
Firebase, MySQL, MongoDB

**Comment by VB10** [comment]
Merhaba @beyzakececi, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @beyzakececi, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
