### ISSUE TITLE
Furkan Yildirim [uzaktan,yüzyüze][mobile][zorunlu][4hafta]

### ISSUE THREAD

**Issue by Furkan-Yildirim45** [VB10/staj_2024#525]
### Kişisel:

- **Ad Soyad:**Furkan Yıldırım
- **Okul:**Balıkesir Universitesi
- **Sınıf:**3.Sınıf
- **CV:** [Google Drive Linki veya pdf linki](#)
[furkan_yıldırım_cv.pdf](https://github.com/VB10/staj_2024/files/14590580/furkan_yildirim_cv.pdf)
[furkan_yildirim_english_cv.pdf](https://github.com/VB10/staj_2024/files/14590583/furkan_yildirim_english_cv.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Bilgisayar Mühendisliği 3. sınıf öğrencisiyim kendimi geliştirmeyi sürekli problem çözmeye yatkınım. kişisel projelerimi zaten yapmaktayım ama iş hayatına yönelik çalışmalara katılmak ve kendimi hayata yönelik projelerde de geliştirmek istiyorum. Aktif olarak Universitenin Bilgi işlem Daire Başkanlığında kendi yazılımlarımızı geliştiriyorum. Bir dönem okulumda Mobil programlama ekibinin takım liderliğini yapmışlığım ve bu sayede insanlara Flutter kodlamayı öğretme tecrübem oldu. Soru sormak isterseniz benimle iletişime girmekten çekinmeyin.

Github: https://github.com/Furkan-Yildirim45
Linkedln: https://www.linkedin.com/in/furkan-y%C4%B1ld%C4%B1r%C4%B1m-8b2aa625a/
Mail: yildirimfurkann45@gmail.com

### Teknik (Örnek projeler, linkleri ve detayları)
Kendime özel bir Todo App yaptım ve boş oldugumda ve aklıma fikirler geldiginde ara ara onu geliştirmekteyim. link :https://github.com/Furkan-Yildirim45/my-todo-app-TaskMuse

Arkadaşımla beraber ekip projesi hakkında tecrübe kazanmak için geliştirdiğimiz bir hava durumu uygulaması var. Oldukça geliştirdiğimiz bir proje. Link :https://github.com/WidgetWizard/WeatherApp

Okul final sınavı için geliştirmiş oldugum bir Web Scrapping projem var python dili ile yazdığım. Airbnb sitesinden belirli kategoriyi çekiyor. link :https://github.com/Furkan-Yildirim45/python_web_scrapping_airbnb

- **İlgilendiklerim (diller, frameworkler vs):** Dart,Flutter,Python,Sql,C#,Git,FireBase,Github

**Comment by VB10** [comment]
Merhaba @Furkan-Yildirim45, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Furkan-Yildirim45, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Furkan-Yildirim45, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Furkan-Yildirim45, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @Furkan-Yildirim45, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @Furkan-Yildirim45
