### ISSUE TITLE
Buğrahan Yünt [frontend][uzaktan][zorunlu][4hafta]

### ISSUE THREAD

**Issue by mryunt02** [VB10/staj_2024#527]
### Kişisel:

- **Ad Soyad:**Buğrahan Yünt
- **Okul:**Sivas Cumhuriyet Üniversitesi
- **Sınıf:** 3.sınıf
- **CV:** https://drive.google.com/file/d/1Gwku0TpFzDv9HWbNMGwhxynXOctGiIk1/view?usp=sharing
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
Bilgisayar Mühendisliği 3. sınıf öğrencisiyim, yeni şeyler öğrenmeyi ve bu sayede gelişmeyi seviyorum, React.js ile projeler geliştirmeyi çok seviyorum, pratik bilgimi tecrübeyle harmanlamak ve bu sayede daha fazla gelişmek istiyorum.

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):** React.js, TypeScript, JavaScript

**Comment by VB10** [comment]
Merhaba @mryunt02, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mryunt02, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mryunt02, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by mryunt02** [comment]
internship found
