### ISSUE TITLE
Mustafa Narin [mobile][uzaktan,yüzyüze][zorunlu][4hafta, 6hafta]

### ISSUE THREAD

**Issue by mustafanarin** [VB10/staj_2024#534]
### Kişisel:

- **Ad Soyad:** Mustafa Narin
- **Okul:** Süleyman Demirel Üniversitesi
- **Sınıf:** 3. Sınıf
- **CV:** [[MUSTAFA NARİN.pdf](https://github.com/VB10/staj_2024/files/14622462/MUSTAFA.NARIN.pdf)](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendin Hakkında (kendini anlatmak istersen):

Merhaba,

Son birkaç aydır Flutter ile uğraşıyorum ve öncesinde de Android üzerinde çalışıyordum. Mobil uygulama geliştirmeye olan tutkum her geçen gün artıyor. Kendimi ileride başarılı bir mobil geliştirici olarak görmek için çaba harcıyorum. Flutter'ı keşfetmek beni heyecanlandırıyor ve sürekli olarak yeni teknolojiler öğrenmeye açığım.
### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):** Flutter, Dart, Android, Kotlin,Firebase, Sql, Git, GitHub
#### Projeler:
- **[Persons App:](https://github.com/mustafanarin/Persons-App-Firebase)** Bloc patterne uygun olarak ve Firebase Firestore kullanarak geliştirdiğim bu uygulamada, kullanıcı listeleme, veri ekleme, güncelleme, arama ve silme işlemlerini yapabiliyor.
- **[Flag Quiz App:](https://github.com/mustafanarin/Flag-Quiz-App-SQLite)** SQLite veritabanını kullanarak bir bayrak adı bilme oyunu geliştirdim.
- **[Prime Video UI Clone:](https://github.com/mustafanarin/Prime-Video-UI-Clone)** Tasarım becerilerimi geliştirmek amacıyla Prime Video'nun UI tasarımını kopyaladım.

**Comment by VB10** [comment]
Merhaba @mustafanarin, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
