### ISSUE TITLE
BAŞAK-TEPE [frontend, data-science][uzaktan, yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by basaktepe** [VB10/staj_2024#546]
### Kişisel:

- Ad Soyad:  Başak Tepe
- Okul: Ege Üniversitesi Bilgisayar Mühendisliği
- Sınıf: 3
- CV: https://drive.google.com/file/d/1aJ5K1sRySdc5YQnj2o1lsFURrQFOvLdF/view?usp=sharing
- Sigorta Okul Karşılıyor (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
  Merhaba adım Başak Tepe. Ege Üniversitesi Bilgisayar Mühendisliği 3. sınıf öğrencisiyim. İkinci sınıfta, veri bilimi alanında çalışmalar yaptım Python Numpy,Pandas Seaborn kütüphanelerinde tecrübem var.
İkinci sınıftayken arkadaşlarım ile birlikte, gönüllü olarak ilkokul öğrencilerine üç ay süren bir kodlama kursu verdik.
 Şu anda, web geliştirme alanında kendimi geliştirmekteyim HTML CSS ve JavaScript dillerinde tecrübem var, Vue.js öğreniyorum. Yaklaşan yaz dönemi için, müfredatımın zorunlu bir parçası olan bir staj fırsatı arayışı içerisindeyim. 

### Teknik (Örnek projeler, linkleri ve detayları)
 HTML, CSS ve JavaScript ile Tic tac toe oyunu : https://github.com/basaktepe/tic-tac-toe
 Hi - kod veri bilimi atölyesi bitirme projesi Avrupadaki cinsiyete göre farklı alanlardaki maaş farkları : https://github.com/basaktepe/Gender-Pay-Gap-Europe
 HTML ve CSS ile responsive yemek websitesi : https://github.com/basaktepe/responsive-foodwebsite
 HTML ve CSS ile travel goals websitesi : https://github.com/basaktepe/travel-goals-website

- **İlgilendiklerim (diller, frameworkler vs):**
-HTML
-CSS
-JavaScript
-Vue.js
-Python

**Comment by VB10** [comment]
Merhaba @basaktepe, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @basaktepe, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
