### ISSUE TITLE
ATAKAN-YESIL [frontend,backend,mobil,ml][istanbul][zorunlu][kisa-uzun]

### ISSUE THREAD

**Issue by benevolentsocialplanner** [VB10/staj_2024#547]
### Kişisel:

- **Ad Soyad:**Atakan Yesilkayali
- **Okul:**bogazici universitesi
- **Sınıf:**4
- **CV:** profilimden ulasilabilir
- **Sigorta Okul Karşılıyor** (Evet/Hayır): evet

### Kendin Hakkında (kendini anlatmak istersen):

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**
profilimde mevcut

**Comment by VB10** [comment]
Merhaba @benevolentsocialplanner, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
