### ISSUE TITLE
Nermin KILIÇARSLAN [mobile][zorunlu][4 hafta,6 hafta]

### ISSUE THREAD

**Issue by nerminkilicarslan** [VB10/staj_2024#551]
### Kişisel:

- **Ad Soyad: Nermin Kılıçarslan**
- **Okul: Burdur Mehmet Akif Ersoy Üniversitesi**
- **Sınıf: 2.sınıf**
- **CV: https://drive.google.com/file/d/1f_17fxOTcbB3PO6GywP43Y5VXm-Xkfww/view?usp=drive_link** [Google Drive Linki veya pdf linki](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):Ben Nermin Kılıçarslan. Yazılım Mühendisliği 2.sınıf öğrencisiyim. Yeni şeyler öğrenmeye ve kendimi geliştirmeye açığım. Şu anda IEEE WIE Türkiye Kolunda Proje Sorumlusu olarak görev yapmaktayım aynı zamanda IEEE MAKU yönetim kurulu başkan yardımcısı ve iletişim komitesi üyesiyim. Kendimi bu tarz global topluluklarda aktif rol göstererek geliştirmeye çalışıyorum. Gittiğim okullarda Java ve Python öğretildiği için temel düzeyde bu dillerde bilgi sahibiyim. Aynı zamanda Mobil programlama ve yapay zeka alanında kendimi geliştiriyorum.

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)
Tübitak 2209-A Epilepsi Hastalarının Nöbet Durumunu Tespit Eden Akıllı
Mobil Uygulama
Teknofest İnsanlık Yararına Teknoloji 2023 Epilepsi Hastalarının Nöbet Durumunu Tespit Eden Akıllı
Mobil Uygulama

- **İlgilendiklerim (diller, frameworkler vs): Python,Java,React Native**

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
