### ISSUE TITLE
Nermin Kılıçarslan ["mobile", "backend"]["uzaktan", "yüzyüze"]["zorunlu", "gönüllü"]["4hafta", "6hafta"]

### ISSUE THREAD

**Issue by nerminkilicarslan** [VB10/staj_2024#552]
### Kişisel:

- **Ad Soyad:Nermin Kılıçarslan**
- **Okul:Burdur Mehmet Akif Ersoy Üniversitesi**
- **Sınıf:2.sınıf**
- **CV: https://drive.google.com/file/d/1f_17fxOTcbB3PO6GywP43Y5VXm-Xkfww/view?usp=sharing** [Google Drive Linki veya pdf linki](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):Ben Nermin Kılıçarslan. Yazılım Mühendisliği 2.sınıf öğrencisiyim.
Yeni şeyler öğrenmeye ve kendimi geliştirmeye açığım. Şu anda
IEEE WIE Türkiye Kolunda Proje Sorumlusu olarak görev
yapmaktayım aynı zamanda IEEE MAKU yönetim kurulu başkan
yardımcısı ve iletişim komitesi üyesiyim. Kodlama uğraşlarımın
yanında kendimi bu tarz global topluluklarda aktif rol göstererek
geliştirmeye çalışıyorum. Gittiğim okullarda Python ve Java
öğrendiğimiz için temel düzeyde bilgiye sahibim. Aynı zamanda
Mobil programlama ve yapay zeka alanında kendimi
geliştiriyorum.

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)
Tübitak 2209-A
Epilepsi Hastalarının Nöbet Durumunu Tespit Eden Akıllı
Mobil Uygulama
Teknofest İnsanlık Yararına Teknoloji 2023
Epilepsi Hastalarının Nöbet Durumunu Tespit Eden Akıllı
Mobil Uygulama

- **İlgilendiklerim (diller, frameworkler vs):Java,Python,React Native**

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @nerminkilicarslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by mehmettalhairmak** [comment]
Merhaba Nermin,

Eğer staj arayışın devam ediyorsa bana cv'ni iletir misin.

mirmak@eight.com.tr

**Comment by nerminkilicarslan** [comment]
Merhabalar, Tabii ki de iletirim

*Nermin KILIÇARSLAN*

*IEEE Türkiye Section Women in Engineering AG Responsible of Project *
*Burdur Mehmet Akif Ersoy Üniversitesi*
*Software Engineering #2*
*#99891056*
*M: ***@***.*** ***@***.***>*
*P: +90 551 174 50 66*




25 Nis 2024 Per, saat 09:12 tarihinde Mehmet Talha Irmak <
***@***.***> şunu yazdı:
