### ISSUE TITLE
GAMZE-ŞİRİN [frontend,backend][yüzyüze,uzaktan][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by gamzesirin** [VB10/staj_2024#556]
### Kişisel :
- **Ad Soyad:** Gamze Şirin
- **Okul:** Mehmet Akif Ersoy Üniversitesi
- **Sınıf:** 2. sınıf
- **CV:** [Buradan erişin](https://drive.google.com/file/d/1nAzS_kYOZBVbB-Ry6pNvlbgZNNlEOysu/view?usp=sharing)
- **Sigorta:** Okul tarafından karşılanmaktadır (Evet)

### Hakkımda:
Merhaba, ben Gamze Şirin, yazılım geliştirmeye yürekten bağlı biriyim. Lisede bilgisayar bölümünde veritabanı programlama okudum. Yazılım mühendisi olmaya karar verdim ve Mehmet Akif Ersoy Üniversitesi Yazılım Mühendisliğini kazandım. Üniversiteden önce de kendi çapımda yazılım projeleri geliştirmeye çalışırdım; bu durum üniversiteyi kazanmamla beraber daha da ciddileşti ve alanımı web geliştirme olarak belirledim. Üniversite eğitimim devam ederken hem teknik hem de bilimsel açıdan kendimi geliştirmeye ve projeler yapmaya çalışıyorum. Web alanında projeler geliştirip GitHub hesabımda paylaşıyorum. Gerçek hayat projelerinde yer almak ve kendimi daha da geliştirmek için heyecanlı ve hazırım. Zorunlu yaz dönemi stajımda sizinle en güncel teknolojiler ile güzel projelere imza atmak, katkıda bulunmak ve kariyerime güzel bir başlangıç yapmak istiyorum. Teşekkür ederim.

### Teknik Bilgiler (Örnek projeler, linkleri ve detayları):

- [Fullstack Chat App with Socket.io](https://github.com/gamzesirin/Fullstack-ChatApp-Socket.io): Bu proje, bir canlı etkileşimli konuşma, mesajlaşma projesidir ve Socket.io kullanılarak geliştirilmiştir.
- [Node.js Hotel API](https://github.com/gamzesirin/Nodejs-HotelApi): Bu proje, bir otel rezervasyon sisteminin backend kısmını oluşturmak için Node.js, Express.js ve MongoDB kullanılarak geliştirilmiştir. Sistem, kullanıcı kaydı, otel ve oda yönetimi gibi temel işlevleri gerçekleştirebilen RESTful API'lar sağlar.
- [React & TailwindCSS Getir Clone App](https://github.com/gamzesirin/react-tailwindcss-getir-clone-app): Bu proje, Getir uygulamasının klon halidir ve temel pek çok front-end gereksinimlerini karşılar.
- [Misfit App with Node.js ](https://github.com/gamzesirin/Nodejs-Misfit-Project): Bu proje, Node.js, MongoDB kullanılarak geliştirilen
veritabanına veri kaydetme, silme, güncelleme, verileri getirme gibi işlemleri yapabildiğimiz admin panelli bir FullStack Web projesidir.

### İlgi Alanlarım (Diller, Frameworkler vs.):
- React.js
- Express.js
- Next.js
- HTML
- CSS
- JavaScript
- TypeScript
- TailwindCSS
- Bootstrap
- SQL
- MySQL
- Node.js
- MongoDB
- Python
- Java

**Comment by VB10** [comment]
Merhaba @gamzesirin, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by gamzesirin** [comment]
staj yeri buldum çookk teşekkür ederim :) iyi ki varsınız

**Comment by VB10** [comment]
@gamzesirin süper başarıların daim olsun ✨
