### ISSUE TITLE
BERKAY-DERİN [frontend,backend][yüzyüze,uzaktan][zorunlu][6 hafta]

### ISSUE THREAD

**Issue by berkayderin** [VB10/staj_2024#557]
### Kişisel:

- **Ad Soyad:** Berkay Derin
- **Okul:** Mehmet Akif Ersoy Üniversitesi
- **Sınıf:** 3. sınıf
- **CV:** [CV'yi görüntüle](https://drive.google.com/file/d/1Qvf-u9iJEsuTh56yykw3d49XvrG_jR2N/view?usp=sharing)
- **Sigorta Okul Karşılıyor:** Evet

### Hakkımda:
Kendimi Node.js, React.js ve birçok modern web teknolojisi konusunda geliştirmekteyim. Yarı zamanlı olarak freelance projelerin frontend kısmında görev alıyorum. Ekip çalışmasına yatkın, yeni teknolojileri öğrenmeye hevesli ve problem çözme becerilerine sahibim. Bionluk’ta 20'den fazla müşterim oldu. Freelancer olarak Frontend ve Backend kodlamaları yapmaktayım. Staja girmek istediğim şirkette hem bildiğim teknolojilerde kendimi geliştirmek hem de yeni teknolojiler öğrenmek istiyorum.

### Teknik (Örnek projeler, linkleri ve detayları)
**Nodejs Duyuru Projesi**
- **Link:** [iwebduyuru.vercel.app](https://iwebduyuru.vercel.app)
- **Teknolojiler:** Node.js, Express, MongoDB, Mongoose, bcrypt, session-based authentication
- **Detaylar:** Kullanıcılar kayıt olabilir ve sisteme giriş yapabilir. E-posta adresi üzerinden benzersiz kullanıcı doğrulaması yapılır. Güvenli parola saklama için bcrypt kullanılmıştır. Yetkilendirilmiş kullanıcılar duyurular ekleyebilir ve silebilir. Duyuruların başlangıç ve bitiş tarihleri yönetilir. Proje, Model-View-Controller (MVC) mimari yapısına uygun olarak geliştirilmiştir, bu sayede uygulamanın bakımı ve genişletilmesi kolaylaştırılmıştır.

**Github Adresim:** [https://github.com/berkayderin](https://github.com/berkayderin)

### İlgilendiklerim (diller, frameworkler vs):
**FRONTEND:**
- HTML, CSS, Bootstrap 5, Tailwindcss, JavaScript, Typescript, Reactjs, Nextjs

**BACKEND:**
- Nodejs, Expressjs, C#, Asp.net Core Web Api, Python, Java

**DATABASE:**
- Mongodb, SQL

**Comment by VB10** [comment]
Merhaba @berkayderin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
