### ISSUE TITLE
Sıla-Pala [back and , kotlin, mobil, web ][Zorunlu yüzyüze, zorunlu uzaktan][4-6-8 hafta]

### ISSUE THREAD

**Issue by silapala** [VB10/staj_2024#565]
### Kişisel:

- **Ad Soyad:Sıla Pala**
- **Okul:Nevşehir Hacıbektasi veli üniversitesi**
- **Sınıf:3**
- **CV:** [Google Drive Linki veya pdf linki]
[inbound4673133705748516363.pdf](https://github.com/VB10/staj_2024/files/14729427/inbound4673133705748516363.pdf)
(#)
- **Sigorta Okul Karşılıyor** (Evet): 

### Teknik (Web sitesi basit şekilde yaptım kotlin eğitimi alıyorum uygulama geliştirme ve yapımı üzerinde çalışıyorum )

- **İlgilendiklerim (kotlin, PHP, python, HTML, CSS):**

**Comment by VB10** [comment]
Merhaba @silapala, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @silapala, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @silapala, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @silapala, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
