### ISSUE TITLE
Ahmet Can Aytekin [Backend, Frontend][uzaktan,yakından][zorunlu][4hafta]

### ISSUE THREAD

**Issue by ahmetcan-aytekin** [VB10/staj_2024#568]
### Kişisel:

Ahmet Can Aytekin
Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi
3.sınıf
https://drive.google.com/file/d/1mUyTWITC3QY1v0XnCvBJHogqhfLFBkYh/view?usp=drive_link
Evet

Java Spring Framework ve React ile 2 buçuk senedir full stack projeler üretmekteyim.

Java Spring&Boot React

**Comment by VB10** [comment]
Merhaba @ahmetcan-aytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
