### ISSUE TITLE
Ahmetcan Aytekin [Backend, Frontend][Yakından,Uzaktan][Zorunlu][4-6 Hafta]

### ISSUE THREAD

**Issue by ahmetcan-aytekin** [VB10/staj_2024#569]
### Kişisel:

- **Ad Soyad:Ahmet Can Aytekin**
- **Okul:Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi**
- **Sınıf:3. Sınıf**
- **CV:** [https://drive.google.com/file/d/1mUyTWITC3QY1v0XnCvBJHogqhfLFBkYh/view?usp=drive_link](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır):Evet 

### Kendin Hakkında (kendini anlatmak istersen):
Java Spring ve React frameworkleri ile 2 buçuk senedir full stack projeler üretmekteyim.

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):Java Spring&Boot React Python Fast API**

**Comment by VB10** [comment]
Merhaba @ahmetcan-aytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ahmetcan-aytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ahmetcan-aytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ahmetcan-aytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ahmetcan-aytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
