### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by ykorkmaz21** [VB10/staj_2024#57]
Kişisel:

- Yunus Emre Korkmaz
- Koç Üniversitesi
- 2.sınıf
- CV: https://docs.google.com/document/d/1UzaozIeqJcs32VTg15iK9znfObJx7624/edit?usp=share_link&ouid=111822002501283900276&rtpof=true&sd=true
- Sigorta Okul Karşılıyor:  Evet

**Comment by VB10** [comment]
Merhaba @ykorkmaz21, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ykorkmaz21, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
