### ISSUE TITLE
BEYZA-ASLAN [FRONTEND][YÜZYÜZE][ZORUNLU][8 HAFTA]

### ISSUE THREAD

**Issue by BEYZAASLAN** [VB10/staj_2024#571]
### Kişisel:

- Ad Soyad: BEYZA ASLAN
- Okul: KIRKLARELİ ÜNİVERSİTESİ
- Sınıf: 3. SINIF
- Sigorta Okul Karşılıyor: EVET
- **İlgilendiklerim (diller, frameworkler vs):**
- JAVASCRİPT ,REACT, TYPESCRİPT, FİGMA , BOOTSTRAP, SASS, TAİLWİND ,HTML ,CSS,

**Comment by VB10** [comment]
Merhaba @BEYZAASLAN, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by BEYZAASLAN** [comment]
created

**Comment by VB10** [comment]
Merhaba @BEYZAASLAN, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @BEYZAASLAN, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
