### ISSUE TITLE
Ahmetcan-Aytekin [backend][uzaktan,yakından][zorunlu,gönüllü][4-6hafta]

### ISSUE THREAD

**Issue by ahmetcan-aytekin** [VB10/staj_2024#572]
### Kişisel:

- **Ad Soyad: Ahmet Can Aytekin**
- **Okul:Alparslan Türkeş Bilim ve Teknoloji Üniversitesi**
- **Sınıf:3.Sınıf**
- **CV:** [https://drive.google.com/file/d/1mUyTWITC3QY1v0XnCvBJHogqhfLFBkYh/view?usp=drive_link](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

(Java Spring&Boot ve React ile full-stack projeler yaptım, şuan Microservice ile Spring kursuna başladım)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):Spring, Fast API, React**

**Comment by VB10** [comment]
Merhaba @ahmetcan-aytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
