### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by bugraalpaydin** [VB10/staj_2024#580]
### Kişisel:

-Buğra Alp Aydın
-Akdeniz Üniversitesi
-2. sınıf
- https://drive.google.com/file/d/1QkDQ5E-B31cMaK2CvabQsdk0Uj8J79-M/view?usp=drive_link
-Evet

İsmim Buğra Alp Aydın, Akdeniz Üniversitesi Elektrik Elektronik bölümü 2.sınıf öğrencisiyim kendimi gömülü sistemler üzerine geliştirmeye çalışıyorum. Şu ana kadar STM32F407-DISC1 ve STM32F103C8T6 mikrodenetleyicileri ile hem HAL kütüphanelerini hem de register seviyesinde çevrebirimlerini programladım.

Aktif olarak üniversitemde bulunan Tufan Elektromobil takımında yazılım bölümünde çalışıyorum. İlgilendiğim kısım aracın bazı verilerinin izleme istasyonuna aktarılması. LoRa RF modülünü kullanarak araçta bulunan bir STM32F103C8T6 mikrodenetleyici UART ile LoRa ile haberleşiyor ve bu LoRa modülü de izleme merkezindeki diğer LoRa modülü ile veri alışverişi yapıyor. Şu anda projenin github repo'su bazı sebeplerden doalyı gizli durumda gerekli olduğu halde paylaşım yapabilirim 

-İlgilendiğim Diller C/C++, python.

**Comment by VB10** [comment]
Merhaba @bugraalpaydin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
