### ISSUE TITLE
ZEKİYE-ÖZDEMİR [frontend,backend][yüzyüze,uzaktan][zorunlu][4hafta]

### ISSUE THREAD

**Issue by ZekiyeOzdemir** [VB10/staj_2024#583]
### Kişisel:

- **Ad Soyad: Zekiye Özdemir**
- **Okul: İstanbul Üniversitesi Cerrahpaşa**
- **Sınıf: 4. sınıf**
- **CV: 
[Zekiye__Ozdemir-CV.pdf](https://github.com/VB10/staj_2024/files/14754471/Zekiye__Ozdemir-CV.pdf)**
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):
Merhaba, ben Zekiye Özdemir. İstanbul Üniversitesi Cerrahpaşa Bilgisayar Mühendisliği son sınıf öğrencisiyim. Web alanında çeşitli takımlarla ve bireysel olarak projeler geliştirip Github hesabımda paylaşıyorum. Gerçek hayat projelerinde yer almak, kendimi daha da geliştirerek daha fazla deneyim kazanmak için zorunlu yaz dönemi stajı arıyorum. Sizinle güncel teknolojiler ile önemli projelere imza atmak, katkıda bulunmak ve kariyerime güzel bir başlangıç yapmak stajımdan beklediğim en öncelikli değerdir. Teşekkür ederim.

### Teknik (Örnek projeler, linkleri ve detayları)
Projelerim için github adresim: https://github.com/ZekiyeOzdemir

- **İlgilendiklerim (diller, frameworkler vs):**
React.js
Angular
SpringBoot
HTML
CSS
JavaScript
TypeScript
Bootstrap
SQL
MySQL
POSTGRESQL
MongoDB
Python
Java

**Comment by VB10** [comment]
Merhaba @ZekiyeOzdemir, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ZekiyeOzdemir, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ZekiyeOzdemir, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @ZekiyeOzdemir, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
