### ISSUE TITLE
Enver Tuna Sönmez [mobile][uzaktan, yüzyüze][zorunlu][4 hafta]

### ISSUE THREAD

**Issue by envertunasonmez** [VB10/staj_2024#585]
### Kişisel:

- **Ad Soyad: Enver Tuna Sönmezz
- **Okul: Zonguldak Bülent Ecevit Üniversitesi
- **Sınıf: 4. sınıf
- **CV: https://drive.google.com/file/d/1M8YP5m6k64UojWyPWGDl--NLbp9pIk3K/view?usp=sharing
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  EVET

### Kendin Hakkında (kendini anlatmak istersen): 

Ben Enver Tuna Sönmez. Zonguldak Bülent Ecevit Üniversitesi'nde Bilgisayar Mühendisliği bölümü 4. sınıf öğrencisiyim. 

Üniversite hayatıma başladığım andan beri mobil uygulama geliştirmek ile ilgileniyorum. Bu konuda kendimi geliştirme azmim ve arzum var. 
Diploma çalışmam da Flutter ile mobil uygulama geliştirme üzerinedir. 

Mezun olabilmek için bu yaz yapmam gereken zorunlu stajım bulunmaktadır. Zorunlu stajım süresince sigortam üniversitem tarafından karşılanmaktadır. Stajımı şirketinizde Flutter ile mobil uygulama geliştirmek üzerine yapmayı çok isterim. Mezuniyetim sonrası mevcut iş arayışım olacağından uygun görülürse de firmanızda çalışma hayatına başlamayı dilerim.

- **İlgilendiklerim (diller, frameworkler vs): Dart/Flutter

**Comment by VB10** [comment]
Merhaba @envertunasonmez, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by envertunasonmez** [comment]
Hocam başlık istenilen gibi AD SOYAD ALAN STAJ YERİ STAJ TİPİ VE STAJ SÜRESİ belirtildiği gibi

**Comment by VB10** [comment]
Merhaba @envertunasonmez, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
