### ISSUE TITLE
Vahdettin-AYDIN[Mobile][Yüz yüze][zorunlu][4 hafta]

### ISSUE THREAD

**Issue by vahdettinA** [VB10/staj_2024#593]
### Kişisel:

- Vahdettin AYDIN
- Atatürk Üniversitesi
- Bilgisayar müh. sınıf
- Cv : https://drive.google.com/file/d/1OwsXCo9BuVL8796IS493gxHqsDOs3AuO/view?usp=sharing
- **Sigorta Okul Karşılıyor** (Evet)

### Kendin Hakkında (kendini anlatmak istersen):

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)
Flutter gemini ai uygulaması :" https://github.com/vahdettinA/flutter_gemini_ai"
 Flutter localdeki ses dosyalarını çalan müzik app : "https://github.com/vahdettinA/flutter_music_app"
  Flutter ile kendi rest_api 'ımı kullanma:"  https://github.com/vahdettinA/flutter_my_restApi_example"
 Flutter flame ile flappy-bird oyunu :" https://github.com/vahdettinA/flutter-flame-bird-game"
  Githubımda paylaşmadığım görüntülü konuşma uygulaması,ve anlık mesaj uygulaması
- **İlgilendiklerim (diller, frameworkler vs):**
- Dart(Flutter)
- node.js
- sql
-C#

**Comment by VB10** [comment]
Merhaba @vahdettinA, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @vahdettinA, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by vahdettinA** [comment]
Düzenleme yapildi
