### ISSUE TITLE
Mehmet Ali Duran ["backend","data-science","embedded"]["uzaktan","yüzyüze"]["zorunlu","gönüllü"]["6hafta"]

### ISSUE THREAD

**Issue by mehmet-ali-duran** [VB10/staj_2024#595]
### Kişisel:

- **Ad-Soyad: Mehmet Ali Duran**
- **Okul: Yıldız Teknik Üniversitesi**
- **Sınıf: 2. Sınıf**
- **CV:  https://drive.google.com/file/d/1bsIdVO_5D0dnMRPXHQqWRUi8aWb_MOjN/view?usp=sharing ** 
- **Sigorta Okul Karşılıyor** Evet: 

### Teknik (Örnek projeler, linkleri ve detayları)

https://github.com/mehmet-ali-duran

**Comment by VB10** [comment]
Merhaba @mehmet-ali-duran, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
