### ISSUE TITLE
Yusuf-Duman[mobile][uzaktan ,yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by dumanYusuf** [VB10/staj_2024#605]
### Kişisel:

- **Ad Soyad:**Yusuf Duman
- **Okul:** Kırklareli Üniversitesi
- **Sınıf:** 3.sınıf
- **CV:** [Google Drive Linki veya pdf linki](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
Ben Yusuf Duman Kırklareli üniversitesinde Yazılım mühendisi öğrencisi olarak mobil uygulamaların geliştirilmesi
konusunda kendimi geliştiriyorum.özelikle  FLUTTER'ı iyi derece bilmekteyim

### Teknik (Örnek projeler, linkleri ve detayları)
 -Linkedin:
  https://www.linkedin.com/in/dumanyusuf/
  -Github:
  https://github.com/dumanYusuf

- **İlgilendiklerim (diller, frameworkler vs):**
### Kişisel:

Flutter ve Dart:
Firebase: Firebase platformunu kullanarak gerçek zamanlı veritabanı, kullanıcı kimlik doğrulama ve bulut depolama gibi özellikleri entegre etme konusunda deneyimim bulunmaktadır.
SQLite : Mobil uygulamalar için yerel veritabanı çözümleri olan SQLite ile çalışma deneyimim bulunmaktadır.
API ile Veri Çekme: Dio ve HTTP gibi kütüphaneleri kullanarak API'lerden veri çekme konusunda tecrübeliyim.
State Magament: Flutter uygulamalarında durum yönetimi için Provider ve Bloc-Cubit kullanabiliyorum.

### Teknik (Örnek projeler, linkleri ve detayları)
  - Linkedin:www.linkedin.com/in/dumanyusuf/)
  - Github: https://github.com/dumanYusuf
  
- *İlgilendiklerim (diller, frameworkler vs):*

  - Flutter ve Dart
  - Firebase :

**Comment by VB10** [comment]
Merhaba @dumanYusuf, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
