### ISSUE TITLE
Rıdvan-Bekleviç [mobile][uzaktan,yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by beklevicRidvan** [VB10/staj_2024#606]
### Kişisel:

- **Ad Soyad:** Rıdvan Bekleviç
- **Okul:** Kırklareli Üniversitesi
- **Sınıf:** 3. Sınıf
- **CV:** [Google Drive Linki veya pdf linki](#)
   - https://drive.google.com/file/d/1tk-RyMNOfdFGooJDgf5Km5pew9_yW8vj/view?usp=drive_link 
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendin Hakkında (kendini anlatmak istersen):

Merhaba, ben Rıdvan Bekleviç  Yazılım Mühendisliği öğrencisiyim. Flutter ile mobil uygulamalar geliştirmekteyim. Kendimi sürekli geliştirmeye, yeni teknolojileri öğrenmeye ve sürekli problem çözebilme yeteğine sahip biriyim. Sektördeki yenillikleri devamlı bir şekilde takip etmekteyim.Ekip içinde etkili bir iletişim kurarak fikir alışverişi yapmak, projelerin başarılı olması için çok önemlidir. Ayrıca, proje yönetimi ve problem çözme konularında esnek ve analitik bir yaklaşım sergileyerek her türlü zorluğun üstesinden gelebilecek yetenekte olduğumu düşünüyorum.Karşılaştığım her engel, beni daha da motive ediyor ve hedeflerime ulaşmak için daha fazla çaba göstermemi sağlıyor. Her proje ve her görev, benim için yeni bir öğrenme ve büyüme fırsatıdır. Kurslardan öğrendiğim teorik bilgileri projelerde kullanarak gerçek zamanlı deneyim elde etmek istiyorum.Benim için her proje, yeni bir öğrenme ve büyüme fırsatıdır ve bu tutkuyla her zorluğun üstesinden gelmeye kararlıyım.  

### Teknik (Örnek projeler, linkleri ve detayları)
  - Linkedin: www.linkedin.com/in/rıdvan-bekleviç
  - Github: https://github.com/beklevicRidvan
  
- **İlgilendiklerim (diller, frameworkler vs):**

  - Flutter ve Dart
  - Firebase :    Firebase platformunu kullanarak gerçek zamanlı veritabanı, kullanıcı kimlik doğrulama ve bulut depolama gibi özellikleri entegre etme konusunda deneyimim bulunmaktadır.
  - SQLite : Mobil uygulamalar için yerel veritabanı çözümleri olan SQLite local veritabanında çalışma deneyimim bulunmaktadır.
  - API ile Veri Çekme: Dio ve HTTP gibi kütüphaneleri kullanarak API'lerden veri çekme konusunda tecrübeliyim.
  - State Magament: Flutter uygulamalarında durum yönetimi için Provider ve Bloc-Cubit yöntemlerini kullanabiliyorum.

**Comment by VB10** [comment]
Merhaba @beklevicRidvan, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
