### ISSUE TITLE
Kerem İşlek [backend][uzaktan,yüzyüze][zorunlu][4hafta] 

### ISSUE THREAD

**Issue by keremislek** [VB10/staj_2024#607]
Kerem İşlek 
İstanbul Medeniyet Üniversitesi
4. Sınıf
CV: https://drive.google.com/file/d/1lHhFtmcfOwEnYrVCYQ9UPbr_KEw_C7Ks/view?usp=sharing
Sigorta Okul Karşılıyor: Evet

Merhabalar. Ben Kerem. Eğitim hayatım boyunca bir çok teknoloji ile ilgilendim. Benim için en uygun alanın backend olduğuna karar verdim. Şimdi Java, Springboot ağırlıklı çalışmalarımı sürdürüyorum. Kariyer hedefim backen developer olmak.

Bazı çalışmlarıma şuradan göz atabilirsiniz:
- Randevu Sistemi : https://github.com/keremislek/BarbersAppointment
- Araç Kiralama Sistemi : https://github.com/keremislek/rentCarDemo
- Mobil Test : https://github.com/keremislek/Appium_Test_BIL359

**Comment by VB10** [comment]
Merhaba @keremislek, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @keremislek, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @keremislek, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
