### ISSUE TITLE
Yunus Emre Korkmaz 2 [data-science, database][uzaktan, yüzyüze][zorunlu][4hafta, 6hafta]

### ISSUE THREAD

**Issue by ykorkmaz21** [VB10/staj_2024#61]
- Ad Soyad: Yunus Emre Korkmaz
- Okul: Koç Üniversitesi
- Sınıf: 2.sınıf
- CV: [https://docs.google.com/document/d/1UzaozIeqJcs32VTg15iK9znfObJx7624/edit?usp=share_link&ouid=111822002501283900276&rtpof=true&sd=true]
- Sigorta Okul Karşılıyor: Evet

**Comment by VB10** [comment]
Merhaba @ykorkmaz21, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
