### ISSUE TITLE
Ipek-Kochisarli[mobile][uzaktan, yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by Kochipek** [VB10/staj_2024#612]
### Kişisel:

- **Ad Soyad:** Ipek Kochisarli
- **Okul:** Manisa Celal Bayar Universitesi
- **Sınıf:** 3.Sinif
- **CV:** [[Google Drive Linki veya pdf linki](https://drive.google.com/file/d/17eFVW099q5uhD1o43W-Ef49PNkDTeUkd/view?usp=sharing)]  
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen): 
Ben Ipek, Yazilim Muhendisligi 3.sinif ogrencisiyim. Kariyerime Mobil Uygulama Gelistirme alaninda devam etmek istiyor ve guncel teknolojiler ile calismalar yapmaya calisiyorum.

### Teknik (Örnek projeler, linkleri ve detayları) 
Github : https://github.com/Kochipek
Medium : https://medium.com/@Kochipek
Linkedin : https://www.linkedin.com/in/ipek-kochisarli/

- **İlgilendiklerim (diller, frameworkler vs):**
- Kotlin
- Java
- XML
- Jetpack Compose
- SQLite
- RoomDb
- Firebase
- React Native
- JavaScript / TypeScript
- Flutter

**Comment by VB10** [comment]
Merhaba @Kochipek, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
