### ISSUE TITLE
Mert Ali Hanbay [mobile][uzaktan, yüzyüze][zorunlu][4hafta, 6hafta]

### ISSUE THREAD

**Issue by mrthnby** [VB10/staj_2024#614]
### Kişisel:

- **Ad Soyad:**  Mert Ali Hanbay
- **Okul:**  Türk Alman Üniversitesi
- **Sınıf:**  3
- **CV:** [Mert Ali Hanbay Cv](https://drive.google.com/file/d/1SuGUdDLE2GzFeOlZYLid8KA_A1dZLrGG/view?usp=sharing)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
Merhaba ben Mert Ali, Türk Alman Üniversitesi 3. Sınıf Bilgisayar Mühendisliği Öğrencisiyim. 2 yıldır mobil uygulama geliştiricisi olma yolunda ilerliyorum. Bu süreçte birçok uygulama geliştirdim ve hatta bir tanesini yayınladım (Şu an 27.000'den fazla indirmesi ve günlük 1.300-1.500 arası aktif kullanıcısı var). Bunun dışında freelance developer olarak çalıştım ve bir çok projenin geliştirilme sürecine katkı sağlama fırsatı yakaladım. Şu anda ise tamamlamam gereken 60 günlük bir mesleki alan stajım var.Stajımın tamamını ya da bir kısmını tamamlamak için bir staj yeri arıyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):** Flutter, SwiftUI, UIKit(iOS), Swift, Dart

#### Yazar Eser: YKS, AYT Edebiyat:
 - [Play Store](https://play.google.com/store/apps/details?id=com.yazareser.yks_yazar_eser&hl=tr&gl=TR)
 - [App Store](https://apps.apple.com/tr/app/yazar-eser-yks-ayt-edebiyat/id6479536386?l)

**Comment by VB10** [comment]
Merhaba @mrthnby, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mrthnby, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
