### ISSUE TITLE
Utku-Çolak[backend,frontend][yüzyüze,uzaktan][zorunlu][4 hafta]

### ISSUE THREAD

**Issue by utkucaa** [VB10/staj_2024#617]
### Kişisel:

- **Ad Soyad:** Utku Çolak
- **Okul:**Konya Teknik Üniversitesi
- **Sınıf:**3.Sınıf
- **CV:** [[bit.ly/4d3gHo8](https://bit.ly/4d3gHo8)](#)
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @utkucaa, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
