### ISSUE TITLE
Utku Çolak[backend,frontend][yüzyüze,uzaktan][zorunlu][4 hafta]

### ISSUE THREAD

**Issue by utkucaa** [VB10/staj_2024#618]
### Kişisel:

- **Ad Soyad:**utku çolak
- **Okul:**Konya Teknik üniversitesi
- **Sınıf:**3. sınıf
- **CV:** [bit.ly/4d3gHo8](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): evet 

### Kendin Hakkında (kendini anlatmak istersen):

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @utkucaa, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
