### ISSUE TITLE
Ahmet Furkan Gönel [backend,mobile][yüzyüze,uzaktan][zorunlu][4hafta]

### ISSUE THREAD

**Issue by furkangonel** [VB10/staj_2024#619]
### Kişisel:

- Ahmet Furkan Gönel
- Iskenderun Teknik Universitesi
- 3.sınıf 
- **CV:** [https://drive.google.com/file/d/1PNxZJXK6z7pXR9CHgLY9xTP7gNJsYAmr/view?usp=drivesdk](#)

##

 Çalışkan ve problem çözme odaklıyım. Staj benim için meslek hayatını daha yakından görmem ve sektör hakkında daha çok fikrim olması açısından önemli. Stajda hedefim hem kendime hem de bulunacağım şirkete fayda sağlayacak işler yapmak. 

### Teknik: (Shift Planning Program(Java), Interactive Education Program(JavaFX), Logistics Trading System(Java Spring, React))

- **İlgilendiklerim: Java, React, Swift, PHP, SpringFramework

**Comment by VB10** [comment]
Merhaba @furkangonel, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @furkangonel, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @furkangonel, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @furkangonel, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
