### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by BilalDurmus08** [VB10/staj_2024#620]
### Kişisel:

- **Ad Soyad:Bilal Durmuş**
- **Okul:Eskişehir Teknik Üniversitesi**
- **Sınıf:2. Sınıf**
- **CV:** [https://drive.google.com/file/d/1bA_JbOwLs8To3iBKxIk5S6IHubSFJ2Yj/view?usp=drive_link](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): evet

### Kendin Hakkında (kendini anlatmak istersen):

( Yaz aylarında kendimi yazılım alanında geliştirmek adına gönüllü staj, staj yapmak istemekteyim. Yakın zamanda Flutter ile mobil app geliştirmeye başladım. Lakin C# ve .Net konusunda da bilgi sahibiyim. Azimli ve hızlı öğrenen biri olduğumu da düşünüyorum ayrıca.)

### Teknik (Githubımda yapmış olduğum projeler bulunmakta. Görseller ile de projeleri daha kolay anlaşılabilir kıldım.)

- **İlgilendiklerim (.Net, Flutter, Java, C#, Dart, SQL,):**

**Comment by VB10** [comment]
Merhaba @BilalDurmus08, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @BilalDurmus08, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @BilalDurmus08, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @BilalDurmus08, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @BilalDurmus08, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @BilalDurmus08, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @BilalDurmus08, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
