### ISSUE TITLE
FURKAN-BULUT [data-science,backend,frontend,database][yüzyüze,uzaktan][zorunlu][4hafta]

### ISSUE THREAD

**Issue by Furk4nBulut** [VB10/staj_2024#626]
### Kişisel:

- **Ad Soyad: Furkan Bulut**
- **Okul: Manisa Celal Bayar Üniversitesi**
- **Sınıf: 2**
- **CV:** [https://drive.google.com/file/d/1vgMcAqSFGc-8VTojbpQVu74J4RtWluE5/view?usp=drive_link](#)
- **Sigorta Okul Karşılıyor** Evet 

### Kendin Hakkında (kendini anlatmak istersen):

Bilgisayar Mühendisliği 2.sınıf öğrencisidir. Java , Python ,C# programlama dilleri üzerinde belirli bir seviyede kendini geliştirmiştir. TÜBİTAK 4007 Manisa Bilim Şenliğinde Sorumlu Rehber olarak görev almıştır. Bir Teknofest takımında proje geliştirme deneyimine sahiptir. Meşe bilişim şirketinde takım çalışması (Git) üzerine staj görmüştür. MCBÜ Bilgisayar Araştırma ve Uygulama merkezinde kısmı zamanlı olarak görev almaktadır. Görevi sürecinde Full Stack Web geliştirme yapmıştır. Veri bilimi, Makine öğrenmesi, Görüntü işleme ile ilgilenmektedir. MCBU Veri Topluluğu Proje Koordinatörlüğü yapmakta olup Teknofest SolarVizyom Görüntü İşleme Takımı  Kaptanıdır. Topluluk bünyesinde 5 Tübitak projesinde 3 başarılı sonuç elde etmiştir. 

Yapay zeka ile kariyer hedeflemekte ve kendimi o yönde geliştirmekteyim.

### Teknik (Örnek projeler, linkleri ve detayları)

https://ebysdestek.mcbu.edu.tr/  Destek ticket sistemi

https://myoprojesergisi.mcbu.edu.tr/ Projelerin listelendiği bir sayfa

https://imeotomasyon.mcbu.edu.tr/ İşletmede mesleki eğitim öğrencilerinin ücret giriş otomasyonu

https://veri.mcbu.edu.tr/ Topluluk Web Sitesi

https://veri.mcbu.edu.tr/eski/ Topluluk eski web sitesi
 
https://veri.mcbu.edu.tr/datathon/ Datathon sitesi
 
https://metaportal.mcbu.edu.tr/ MetaCBU projesinin veri görüntüleme portalı sitesi

- **İlgilendiklerim (diller, frameworkler vs): Python, Django, Mssql, Tensorflow, Keras, Numpy, Pandas vb. machine learning kütüphaneleri**

**Comment by VB10** [comment]
Merhaba @Furk4nBulut, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Furk4nBulut, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by Furk4nBulut** [comment]
Teşekkür ederim. Zorda olsa staj bulabildim.
