### ISSUE TITLE
Esna Nur Yılmaz [mobile(İOS)][uzaktan,yüz yüze][zorunlu][4-6 hafta]

### ISSUE THREAD

**Issue by EsnaNurYlmz** [VB10/staj_2024#631]
### Kişisel:

- **Ad Soyad:Esna Nur Yılmaz
- **Okul:İstanbul Topkapı Üniversitesi (yazılım mühendisliği)
- **Sınıf:3.sınıf
- **CV: https://drive.google.com/drive/u/0/folders/0AN70D_UTWftZUk9PVA
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

(Bu bölümü doldurabilirsin)

Github:https://github.com/EsnaNurYlmz
Linkedin: https://www.linkedin.com/in/esna-nur-y%C4%B1lmaz-1a53b7237/

- **İlgilendiklerim (java , swift , css , html,javascript,c,c++, firebase,Git,API,Json,Alamofire,OOP,MVC):**

**Comment by VB10** [comment]
Merhaba @EsnaNurYlmz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @EsnaNurYlmz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @EsnaNurYlmz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @EsnaNurYlmz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @EsnaNurYlmz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
