### ISSUE TITLE
Okan-Kukul [mobile][yüzyüze,uzaktan][zorunlu][4hafta]

### ISSUE THREAD

**Issue by Slankss** [VB10/staj_2024#634]
### Kişisel:

- Ad Soyad: Okan Kukul
- Okul: İstanbul Ticaret Üniversitesi
- Sınıf: 4.Sınıf
- CV:  [OkanKukulCV](https://drive.google.com/file/d/10Mh1jNvR0PIrMRkpfp-NmZ7b61E-MHpG/view?usp=drive_link)
- Sigorta Okul Karşılıyor (Evet/Hayır):  Evet

### Kendin Hakkında (kendini anlatmak istersen):

Akademik hayatım boyunca Android Uygulamaları geliştirmeye olan ilgim sebebiyle bu alanda kendimi geliştirmeye devam ettim.
Çevrimiçi kurslar aracılığıyla sertifikalar edindim ve edindiğim bilgileri kullanarak projeler geliştirdim. Bu projeleri Linkedin ve GitHub hesaplarımda paylaşarak deneyimlerimi diğer insanlarla paylaştım. Hergün kendimi geliştirmeye ve yeni trendleri öğrenmeye özen gösteriyorum. Mobil uygulama geliştirmeyi büyük bir keyifle yapıyorum ve büyük kitlelere ulaşan, yenilikçi projelere katkıda bulunmaya hevesliyim.

### Teknik (Örnek projeler, linkleri ve detayları)

TheMovieApp
Popüler dizi ve film içeriklerini kullanıcılara sunan uygulama.

[Google Play](https://play.google.com/store/apps/details?id=com.okankkl.themovieapp)
[GitHub](https://github.com/Slankss/The-Movie-App)

Treasures of Words
İngilizce kelime ezberleme uygulaması

[Google Play](https://play.google.com/store/apps/details?id=com.okankkl.treasuresofwords)
[GitHub](https://github.com/Slankss/TreasuresOfWords)

İlgilendiklerim (Java, Kotlin ,XML, Jetpack Compose, SQLite, Firebase, Git, Github):

**Comment by VB10** [comment]
Merhaba @Slankss, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by Slankss** [comment]
Staj yeri buldum
