### ISSUE TITLE
Yunus Emre ERTEN [data-science ,frontend][uzaktan][zorunlu][4 hafta]

### ISSUE THREAD

**Issue by Yunusemreerten** [VB10/staj_2024#641]
### Kişisel:

- **Ad Soyad:** Yunus Emre ERTEN
- **Okul:** Çukurova Üniversitesi
- **Sınıf:** 2. Sınıf
- **CV:**  
[Yunus Emre ERTEN cv (2).pdf](https://github.com/VB10/staj_2024/files/15138480/Yunus.Emre.ERTEN.cv.2.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır): evet

### Kendin Hakkında (kendini anlatmak istersen):

Otonom araç takımında çalışmıştım , görüntü işleme bölümünde

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**
- C
- C++
- Python
- Veri Bilimi
- Siber Güvenlik

**Comment by VB10** [comment]
Merhaba @Yunusemreerten, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Yunusemreerten, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Yunusemreerten, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Yunusemreerten, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
