### ISSUE TITLE
İBRAHİM SEMİH BAKIR [mobile][yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by IbrahimSemih** [VB10/staj_2024#645]
### Kişisel:

- *Ad Soyad:* İbrahim Semih Bakır
- *Okul:*  Mehmet Akif Ersoy Üniversitesi
- *Sınıf:* 3.Sınıf
- *CV:* https://drive.google.com/file/d/1JKjcVlA81BAeLLL_oK18vpn89NFP3Sds/view
- *Sigorta Okul Karşılıyor* (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Merhaba adım İbrahim Semih. Bilgisayar mühendisliği 3.sınıf öğrencisiyim. Teknolojiyle tutkulu bir şekilde ilgilenen ve bu alanda kariyer yapmaya odaklanmış biriyim. Bir yıla yakın süredir mobil programlama geliştirme ile ilgileniyorum. Bu süreçte kendimi daha çok Flutter üzerine geliştirdim. Fakat yakın zamanda React Native ile de ilgilenmeye başladım. Kendimi iş deneyimi konusunda geliştirmek için staj arayışı içindeyim.
### Teknik (Örnek projeler, linkleri ve detayları)

- *İlgilendiklerim (diller, frameworkler vs):*  Flutter/Dart , React Native, C#, MSSQL, Firebase

**Comment by VB10** [comment]
Merhaba @IbrahimSemih, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @IbrahimSemih, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
