### ISSUE TITLE
HASAN BÜYÜKER [backend][yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by qk8** [VB10/staj_2024#646]
### Kişisel:

- **Ad Soyad:** Hasan Büyüker
- **Okul:** Ondokuz Mayıs Üniversitesi
- **Sınıf:** 4. Sınıf
- **CV:** [https://drive.google.com/file/d/15oNOCCrFCE14xHRisaeqjlgN9ihgvGx4/view?usp=sharing](https://drive.google.com/file/d/15oNOCCrFCE14xHRisaeqjlgN9ihgvGx4/view?usp=sharing)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Teknik (Örnek projeler, linkleri ve detayları)

***

#### Askit | *Java, Spring (Boot, Data, Cloud), Hibernate/JPA, PostgreSQL, Redis, Apache Kafka, Docker, Prometheus, Grafana*
- Spring Boot kullanılarak mikroservis mimarisinde bir soru-cevap platformu geliştirildi.
- Veri kalıcılığını sağlamak için Spring Data JPA ile PostgreSQL kullanıldı.
- Kullanıcı girdilerinin uygunluğunu doğrulamak amacıyla Jakarta Bean Validation kullanıldı.
- Verilerin kullanıcıya daha hızlı bir şekilde sunulabilmesi amacıyla Redis ile cache işlemi yapıldı.
- Spring Cloud Netflix Eureka ile servislerin birbirlerinden haberdar olmaları sağlandı.
- Gerektiğinde servisler arasındaki iletişimi sağlamak için Spring Cloud OpenFeign ve Apache Kafka kullanıldı.
- Spring Cloud Config yardımıyla servislerin yapılandırma bilgileri merkezi bir yere taşındı.
- Spring Cloud Gateway ile gelen istekler ilgili servise yönlendirildi.
- Spring Boot Actuator tarafından sağlanan metriklerin kaydedilip uygun şekilde gözlemlenebilmesi amacıyla Prometheus ve Grafana bağlantısı yapıldı.
- Oluşturulan servisler yazılan Dockerfile dosyaları ve Docker Compose ile birlikte konteyner haline getirildi.

**Proje Github Linki:** [https://github.com/qk8/askit](https://github.com/qk8/askit)

***

#### İlgilendiklerim (diller, frameworkler vs):
- Java & SQL
- Spring (Boot, Data, Cloud)
- Hibernate/JPA
- PostgreSQL
- Redis
- Apache Kafka
- Git
- Docker

(Şu ana kadar Java+Spring çalıştım ama onun yerine C#+ASP.NET vb. olsa da çok farketmez, benzer araçlar sonuçta.)

**Comment by VB10** [comment]
Merhaba @qk8, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @qk8, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @qk8, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @qk8, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @qk8, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @qk8, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @qk8, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
