### ISSUE TITLE
YUNUS EMRE AKINCI [backend,frontend,mobile][uzaktan,yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by emreaknci** [VB10/staj_2024#649]
### Kişisel:

- **Ad Soyad:** Yunus Emre Akıncı
- **Okul:** Sakarya Üniversitesi
- **Sınıf:** 4. Sınıf
- **CV:** https://drive.google.com/file/d/1pg4cHNkbs4dRxUul0egkF0jLSkOTPwUA/view?usp=sharing
- **Sigorta Okul Karşılıyor**: Evet

- **İlgilendiklerim (diller, frameworkler vs):** .NET Core, Java, NodeJs, React, Angular, React Native, Docker, PostgreSQL, MongoDB vs.

**Comment by VB10** [comment]
Merhaba @emreaknci, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
