### ISSUE TITLE
DİDAR YILMAZ [Mobil, Frontend][Uzaktan, yüzyüze][Zorunlu][4 Hafta]

### ISSUE THREAD

**Issue by didaryilmaz** [VB10/staj_2024#650]
Kişisel:

- **Ad Soyad:** Didar Yılmaz
- **Okul:** Fırat Üniversitesi
- **Sınıf:** 3. Sınıf
- **CV:** (https://drive.google.com/file/d/1zMBEyrjLidzuWJxvF_7_ogcOpZvn_HWf/view?usp=sharing)
- **Sigorta Okul Karşılıyor (Evet/Hayır):** Evet 

### **Kendin Hakkında** : 
Merhabalar, ben DİDAR YILMAZ. Fırat Üniversitesi Yazılım Mühendisliği öğrencisiyim. 2023 yılında Birtech Technology Şirketinde, bir ay stajyer olarak Angular Framework üzerinde çalıştım. Frontend alanında React Native ve Angular Framework üzerine bilgi sahibiyim. Şu anda Kotlin öğrenerek Mobil Programlama (Android) alanında çalışıyorum. Mühendislik becerilerimi ortaya koyarak Mobil alanında kendimi geliştirmek amacındayım.

### **Teknik (Örnek projeler, linkleri ve detayları)**

Şu zamanlarda üzerine yoğunlaştığım iki tane projem var.
 
- Birinci projem ; Seyahat Blog Uygulaması geliştirerek hem Android Mobil üzerinden hem de Web Site üzerinden kullanıcılara seyahatlerini planlayacağı, yeni yerler keşfedeceği ve deneyimlerini başka kullanıcılarla paylaşacağı bir Blog sayfası sunacağım. Çalışmalarımı bu link üzerinden inceleyebilirsiniz: (https://github.com/didaryilmaz/SeyahatBlogApp)

- İkinci projem ise Graf Tabanlı Hava Kalite Endeks Analizi oluşturup Dünya haritası üzerinde ülkelerin hava kalite endeksini sunan bir sunucu oluşturacağım. Çalışmalarımı bu link üzerinden inceleyebilirsiniz: (https://github.com/didaryilmaz/AirQuality)

**İlgilendiklerim (diller, frameworkler vs):**
- React Native
- Angular
- Javascript
- Python
- Kotlin
- Java
- C#
- Html
- Css

**Comment by VB10** [comment]
Merhaba @didaryilmaz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @didaryilmaz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @didaryilmaz
