### ISSUE TITLE
ERTUĞRUL SERT [data-science, database][yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by sertugrules** [VB10/staj_2024#653]
### Kişisel:

- **Ertuğrul Sert:**
- **Okul: Ankara Üniversitesi Bilgisayar Mühendisliği(İngilizce)**
- **Sınıf:3.sınıf**
- **CV:** [https://drive.google.com/file/d/1Cp-ETXGZIfaB_fFytdGOLmm1dXq2IqdK/view?usp=sharing](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır: Evet Karşılıyor 
- **Linkedin**:https://www.linkedin.com/in/sertugrules/

### Kendin Hakkında (kendini anlatmak istersen):
Bilgisayar Mühendisliği üçüncü sınıf öğrencisi olarak, Veri Bilimi ve Yapay Zeka ile
ilgileniyorum. Yaz için zorun stajım var ve sigortamı okulum karşılıyor. 
Yeni projeler geliştirme ve bilgi birikimimi genişletme konusunda motive
ve kararlıyım. Kendimi geliştirip ve bir şeyler katabileceğim bir staj yeri yeri arıyorum.

### Teknik 

- **İlgilendiklerim (diller, frameworkler vs): Python, Java, MySQL, OracleSQL, C, Java , Sckit-learn, PySpark, PyTorch, YOLOV8 **
-  **Yaptığım bazı projelere github hesabımdan ulaşabilirsiniz **

**Comment by VB10** [comment]
Merhaba @sertugrules, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @sertugrules, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @sertugrules, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @sertugrules, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @sertugrules, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @sertugrules, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
