### ISSUE TITLE
Talha Arslan [cyber-security][yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by T4L-4** [VB10/staj_2024#655]
### Kişisel:

- Ad Soyad : Talha Arslan
- Okul : Haliç Üniversitesi
- Sınıf : 3. Sınıf 
- CV : [Talha Arslan CV](https://drive.google.com/file/d/1qcqbooy5WXZXrp8GwK5wHxGxIkD-V1nU/view)
- Sigorta Okul Karşılıyor (Evet/Hayır) : Evet 

### Talha Arslan:

[Linkedin](https://www.linkedin.com/in/talharslan/)
[TryHackMe](https://tryhackme.com/p/t4l4)
[Medium](https://medium.com/@T4L-4)

### İlgilendiğim Alanlar:

- Web Security
- Mobile Security

### Teknik Alt Yapım:

- Programming Languages { Python, C/C++, Java }

- Tools { Netcat, Nmap, Metasploit, Burp Suite, Wireshark, Nslookup, Aircrack-ng, Hashcat, SQLmap, Dirb, Gobuster, Hydra, John the ripper... }

- Computer Networks
- Bash Scripting
- MySQL
- Git/Github

**Comment by VB10** [comment]
Merhaba @T4L-4, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @T4L-4, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @T4L-4, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
