### ISSUE TITLE
Alisahin Asya [backend,database,data-science][yüzyüze][zorunlu][6hafta]

### ISSUE THREAD

**Issue by alisahinasya00** [VB10/staj_2024#660]
### Kişisel:

- **Ad Soyad:** Alişahin Asya
- **Okul:** Konya Teknik Üniversitesi
- **Sınıf:** 3.Sınıf
- **CV:** [https://drive.google.com/file/d/1IzzedmX7zyRixQTxSxtIZZ7SlDByBwNF/view?usp=drive_link](#)
- **Sigorta Okul Karşılıyor** (Evet): 

### Kendin Hakkında (kendini anlatmak istersen):
Yazılım mühendisliği öğrencisiyim. Bilgisayar bilimleri ve yazılım geliştirme konularında tutkulu, öğrenmeye hevesli ve sürekli kendini geliştirmeyi amaçlayan biriyim. Java, C#, ve Python dillerinde deneyimliyim.

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)
Projelerimde C# ile uygulama geliştirme, veri tabanı yönetimi ve web tabanlı çözümler oluşturma konularında deneyim kazandım. Arkadaşlarımla beraber depo yönetim sistemi yazıyoruz.

- **İlgilendiklerim (diller, frameworkler vs):**
- C#,C,  .NET, ASP.NET, JAVA, SQLSERVER, MYSQL, PYTHON, HTML, CSS, JAVASCRİPT

**Comment by VB10** [comment]
Merhaba @alisahinasya00, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @alisahinasya00, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @alisahinasya00, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @alisahinasya00, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @alisahinasya00, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @alisahinasya00, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @alisahinasya00, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
