### ISSUE TITLE
Mehmet Yusuf Bircan [Data Science - Machine Learning][uzaktan,yüzyüze][zorunlu][6 hafta]

### ISSUE THREAD

**Issue by MehmetYB4** [VB10/staj_2024#673]
### Kişisel:

- **Mehmet Yusuf Bircan**
- **Karamanoğlu Mehmetbey Üniversitesi:**
- **3. Sınıf**
- **CV:** = https://drive.google.com/file/d/1kxoSevrj_h_arJ6Dvh1TqUIrUIV0p957/view
- **Linkedin** = linkedin.com/in/mehmet-yusuf-bircan-587a53236
- **Sigorta Okul Karşılıyor** Evet 

### Karamanoğlu Mehmetbey Üniversitesinde bilgisayar mühendisliği öğrencisiyim.
Veri biliminde kendimi geliştiriyorum

### Regresyon projesi, Classification projesi

- **Python, Sklearn, Tensorflow,
Numpy, Pandas, Matplotlib,
Seaborn, C, C++, C#, SQL**

**Comment by VB10** [comment]
Merhaba @MehmetYB4, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @MehmetYB4, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @MehmetYB4, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
