### ISSUE TITLE
Muhammet Türksoy [game,data-science][yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by mturksoy** [VB10/staj_2024#682]
### Kişisel:

- **Muhammet Türksoy:**
- **Gazi Üniversitesi:**
- **3. Sınıf:**
- **CV:** https://drive.google.com/file/d/1U5YVQRwzjxrAjk16Prl1k7KrlVAy4hu1/view?usp=drivesdk
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Öğrenmeye hevesli kendi oyun alanında veya başka uygun bi alanda kendimi geliştirmeye ve ilerlemeye hevesli bir bilgisayar mühendisi adayıyım. İngilizce seviyem C1.

### Teknik (Örnek projeler, linkleri ve detayları)
Hali hazırda geliştirdiğim oyun projeleri github adresimde bulunmakta. https://github.com/mturksoy

- **İlgilendiklerim (diller, frameworkler vs):** Unreal engine ve Cisco Packet Tracer uygulamalarını kullanmakta bilgi sahibiyim. C ve C++ dillerine hakimim. Ayrıca veri madenciliği alanına da ilgim var.

**Comment by VB10** [comment]
Merhaba @mturksoy, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mturksoy, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mturksoy, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mturksoy, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mturksoy, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
