### ISSUE TITLE
Emine GÜNEŞ [devops,system][uzaktan, yüzyüze][zorunlu][8hafta]

### ISSUE THREAD

**Issue by eminegunes** [VB10/staj_2024#689]
### Kişisel:

- **Ad Soyad: Emine Güneş**
- **Okul: Fırat Üniversitesi**
- **Sınıf: 3.sınıf**
- **CV: https://drive.google.com/file/d/1v8YyacnjgcW0rHRKtOkNFJa8b4YpzewR/view?usp=drive_link ** 
- **Sigorta Okul Karşılıyor**: Evet

### Kendin Hakkında (kendini anlatmak istersen):

Emine Güneş. Fırat Üniversitesi Teknoloji Fakültesi Yazılım Mühendisliği 3. sınıf öğrencisiyim. Zorunlu stajım için hazırlık yapıyorum ve yazılım endüstrisinde ekip çalışmasıyla profesyonel bir kariyer hedefliyorum. Yaz tatilinde staj yapamazsam eğer okulum uzayacak.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs): ArgoCD,Jenkins,Linux,Kubernetes,Ansible,Docker**

**Comment by VB10** [comment]
Merhaba @eminegunes, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
