### ISSUE TITLE
Tunahan Gediz [Frontend, Backend, QA][Yerinde,Uzaktan][Zorunluİ][6 Hafta]

### ISSUE THREAD

**Issue by tunahangediz** [VB10/staj_2024#69]
### Kişisel:

- **Ad Soyad:** TUNAHAN GEDIZ
- **Okul:** Pamukkale Üniversitesi
- **Sınıf:** 4
- **CV:** [TUNAHAN GEDIZ CV](https://drive.google.com/file/d/1KGwLwk6-i5VUYBT_WRhg08I6P6LswKlK/view?usp=sharing)
- **Sigorta Okul Karşılıyor** : Evet

### Teknik (Örnek projeler, linkleri ve detayları)
[tunahangediz.com](https://www.tunahangediz.com)
[metamax landing clone](https://metamax-landing-page-clone.vercel.app)

- **İlgilendiklerim (diller, frameworkler vs):**
- JavaScript, React, Nextjs, NodeJs, Java, SQL, tailwinds, chakraUI, selenium, testng, junit

**Comment by VB10** [comment]
Merhaba @tunahangediz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @tunahangediz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @tunahangediz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @tunahangediz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
