### ISSUE TITLE
EMİRHAN-ŞAHİN[YAZILIM][İSTANBUL][YAZILIM][30 İŞ GÜNÜ]

### ISSUE THREAD

**Issue by shnemrhn** [VB10/staj_2024#693]
### Kişisel:

- **Ad Soyad:** Emirhan Şahin
- **Okul:** Karabük Üniversitesi 
- **Sınıf:** 1. Sınıf
- **CV:** [https://docs.google.com/document/d/1DW9lzJfCGPBAPifWdQAc5JI3iFyEsZVf/edit?usp=drivesdk&ouid=114218439187426316856&rtpof=true&sd=true](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen): 

(İşimi severek yaparım. Takım çalışmasın iş hayatında önemli rol aldığını biliyorum. Hergün bireysel gelişimim için çalışmalar yaparım. Çalışacağım şirketin hedefleri doğrultusunda çalışmaya açığım.)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**
frontend kısmında gelişip hedeflerim arasında olan fullstack kısmına ulaşmak ve yeni ilgi alanı eklemeyi isterim.

**Comment by VB10** [comment]
Merhaba @shnemrhn, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
