### ISSUE TITLE
MELİKE ZEYNEP-ARSLAN [FRONTEND][Istanbul-Ankara][yüzyüze/ uzaktan ][4hafta/6hafta]]

### ISSUE THREAD

**Issue by Melikearslan959** [VB10/staj_2024#695]
### Kişisel:

- **Melike Zeynep Arslan:**
- **istanbul ticeret üniversitesi :**
- **1:**
- **CV:** [Google Drive Linki veya pdf linki](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): hayır 

### Kendin Hakkında (kendini anlatmak istersen): 1.sınıf öğrencisiyim html cas javascript biliyorum websitesi yapıyorum 

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @Melikearslan959, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Melikearslan959, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Melikearslan959, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @Melikearslan959, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
