### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by mkubilaytekin** [VB10/staj_2024#696]
### Kişisel:

- **Ad Soyad: Mehmet Kubilay Tekin**
- **Okul: Manisa Celal Bayer Üniversitesi**
- **Sınıf: 4**
- **CV: https://drive.google.com/file/d/1App11DNfCRjFGVoN39bPaVr2LtxIGVu5/view?usp=sharing ** 
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet 

### Kendin Hakkında (kendini anlatmak istersen): Merhaba ben Kubilay. Son sınıf yazılım mühendisliği öğrencisiyim. Takım çalışmalarında bulunmayı seviyorum. Kariyerime flutter geliştirici olarak başlamak istediğimden bu alanda staj arıyorum.

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları) : https://github.com/mkubilaytekin 

- **İlgilendiklerim (diller, frameworkler vs):** Flutter ve Dart

**Comment by VB10** [comment]
Merhaba @mkubilaytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mkubilaytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mkubilaytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
