### ISSUE TITLE
Mehmet Kubilay Tekin [Mobile][Uzaktan veya Yüzyüze][Zorunlu][12 Hafta]

### ISSUE THREAD

**Issue by mkubilaytekin** [VB10/staj_2024#697]
### Kişisel:

- **Ad Soyad: Mehmet Kubilay Tekin**
- **Okul: Manisa Celal Bayer Üniversitesi**
- **Sınıf: 4**
- **CV: [https://drive.google.com/file/d/1App11DNfCRjFGVoN39bPaVr2LtxIGVu5/view?usp=sharing](url) ** 
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet sigorta karşılanıyor

### Kendin Hakkında : Merhaba ben Kubilay. Flutter alanında çalışmalar yapıyorum. Google flutter ekibinin önerdiği iki yabancı kaynaklı flutter kursunun sertifikasını aldım. Bunun yanında Google Oyun ve Uygulama Akademisindeyim ve burada birçok takım çalışmasında ve appjam'de bulundum. Bir an önce gerçek hayat projeleri ile kendimi daha çok geliştirmek için heyecanlıyım.

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)
Github linkimde birçok flutter projesi bulucaksınız: https://github.com/mkubilaytekin
En güncel şekilde Gemini ile ufak bir chat app yaptım.

- **İlgilendiklerim (diller, frameworkler vs):** Flutter ve Dart

**Comment by VB10** [comment]
Merhaba @mkubilaytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mkubilaytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
