### ISSUE TITLE
Mehmet Kubilay Tekin [Mobile][Yüzyüze veya Uzaktan][Zorunlu][12 Hafta]

### ISSUE THREAD

**Issue by mkubilaytekin** [VB10/staj_2024#698]
Kişisel:
Mehmet Kubilay Tekin
Manisa Celal Bayer Üniversitesi
4. Sınıf
CV: https://drive.google.com/file/d/1App11DNfCRjFGVoN39bPaVr2LtxIGVu5/view?usp=sharing
Sigorta Okul Karşılıyor Evet
Kendin Hakkında (kendini anlatmak istersen):
Merhaba ben Kubilay. Flutter ile çalışıyorum. Google'ın flutter ekibinin önerdiği yabancı kaynaklı iki tane kursun sertifikasına sahibim. Aktif olarak Google Oyun ve Uygulama Akademisinde flutter ile mobil uygulama eğitimlerine katılıyorum. Birçok takım çalışmasına ve appjam'e katıldım. Flutter ile gerçek hayat projelerinde kendimi geliştirmek ve kariyerime bu alanda başlamak için çok heyecanlıyım.

Teknik (Örnek projeler, linkleri ve detayları)
Github linkimde birçok flutter projesi bulacaksınız: https://github.com/mkubilaytekin

İlgilendiklerim (diller, frameworkler vs):
Flutter, Dart Firebase, 3.parti kütüphaneler

**Comment by VB10** [comment]
Merhaba @mkubilaytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
