### ISSUE TITLE
Mehmet Kubilay Tekin[Mobile][Yüzyüze veya Uzaktan][Zorunlu][12 Hafta]

### ISSUE THREAD

**Issue by mkubilaytekin** [VB10/staj_2024#699]
### Kişisel:

- **Ad Soyad: Mehmet Kubilay Tekin
- **Okul:Manisa Celal Bayer Üniversitesi
- **Sınıf:4
- **CV:** [[Google Drive Linki veya pdf linki]](https://drive.google.com/file/d/1App11DNfCRjFGVoN39bPaVr2LtxIGVu5/view?usp=sharing)(#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen): Merhaba ben Kubilay son sınıf yazılım mühendisliği öğrencisiyim. Mobile geliştiricilik öğrenmeye kotlin ile başladım Flutter ve Dart ile devam ettim bir çok proje yaptım. Google Oyun ve Uygulama Akademisinde aynı zamanda bursiyerim ve burada flutter eğitimleri gördüm. Bir çok App Jam'e katıldım ve takım çalışmasında bulundum. Google Flutter ekibinin önerdiği 2 tane İngilizce kaynaklı flutter kursunun sertifikasını aldım. Teorik bilgilerimi gerçek hayat projeleri ile partiğe döküp gelişim sağlamak için çok heyecanlıyım

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)
https://github.com/mkubilaytekin github linkimde orta ve küçük ölçekte bir çok teknik proje geliştirdim.

- **İlgilendiklerim (diller, frameworkler vs): Flutter Dart Firebase ve üçüncü parti paketler

**Comment by VB10** [comment]
Merhaba @mkubilaytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mkubilaytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mkubilaytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mkubilaytekin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
