### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by Hamzatopcu49** [VB10/staj_2024#703]
### Kişisel:

- **Ad Soyad:Hamza Topçu
- **Okul:Fırat Üniversitesi Yazılım Mühendisliği 
- **Sınıf:3
- **CV:https://drive.google.com/file/d/1gc4jngHJFa__qL9q47ogTnzgOYwtD4nN/view?usp=drivesdk
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

**Comment by VB10** [comment]
Merhaba @Hamzatopcu49, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by Hamzatopcu49** [comment]
.
