### ISSUE TITLE
Koray YALÇIN [web][uzaktan,yüzyüze][gönüllü][4hafta,6hafta]

### ISSUE THREAD

**Issue by korayyalcin1903** [VB10/staj_2024#705]
### Kişisel:

- Ad Soyad: Koray Yalçın
- Okul: Mehmet Akif Ersoy Üniversitesi
- Sınıf: 3
- CV: https://drive.google.com/file/d/1r7pKYlqh4FEAVnORawgGWpAYu2wLiRf5/view?usp=sharing
- Sigorta Okul Karşılıyor (Evet/Hayır):  Hayır
- Gönüllü Stajyer
-  Edindiğim bilgileri pratikte uygulayabileceğim bir staj yeri arıyorum.

### Kendin Hakkında (kendini anlatmak istersen):

Kendin Hakkında (kendini anlatmak istersen): Merhaba, ben Koray Yalçın. Jr. Web Developer olarak kariyerimin başındayım. Bilişim Sistemleri ve Teknolojileri öğrencisiyim ve şu anda ASP.NET MVC öğreniyorum. Python, C#, HTML, CSS ve JavaScript bilgisine sahibim. Hırslı, öğrenmeye hevesli ve takım çalışmasına yatkınım. Yeni teknolojilere ve web uygulama geliştirmeye büyük bir ilgi duyuyorum. Staj süresince pratik deneyim kazanarak kendimi geliştirmeyi hedefliyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

- İlgilendiklerim (diller, frameworkler vs):
BlogApp, kullanıcıların blogları görüntülemesine, eklemesine, düzenlemesine ve yorum yapmasına olanak tanıyan kapsamlı bir web sitesidir. Ayrıca, kategori seçimi, admin girişi, resim ekleme, profil resmi ekleme, şifre değiştirme, kayıt olma, blog arama ve daha birçok özelliği içermektedir. 
https://github.com/korayyalcin1903/django-blogapp
- Daha fazla proje için [profilime](https://github.com/korayyalcin1903/) bakabilirsiniz...
- C# , Python, Asp.Net Mvc, HTML, Css, Bootstrap, Javascript

**Comment by VB10** [comment]
Merhaba @korayyalcin1903, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @korayyalcin1903, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @korayyalcin1903, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @korayyalcin1903, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @korayyalcin1903, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @korayyalcin1903, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
