### ISSUE TITLE
EMİR-SANSAR [mobile,back-end][yüzyüze,uzaktan][zorunlu][8hafta]

### ISSUE THREAD

**Issue by emirsansar** [VB10/staj_2024#707]
### Kişisel:

- **Ad Soyad:** Emir Sansar
- **Okul:** Yeditepe Üniversitesi
- **Sınıf:** 3. Sınıf
- **CV:** https://drive.google.com/file/d/1hY0vey_avA_5cG6wtid-CWAAf99evQg2/view?usp=drive_link
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Ben Emir Sansar, Yeditepe Üniversitesi, Bilişim Sistemleri ve Teknolojileri bölümünde tam burslu olarak üçüncü sınıf öğrencisiyim. Kendimden bahsetmek gerekirse, teknoloji ve yazılım alanına ilgiliyim. Eğitim hayatım dışında yazılım geliştirme alanında projeler geliştirerek, bilgi ve becerilerimi geliştirmeye devam ediyorum. 

Staj başvurum hakkında detaylı bilgi sunmak istiyorum. Okulum tarafından karşılanan 40 iş günü zorunlu yaz stajım bulunmaktadır. Bilgi teknolojileri departmanında staj deneyimi elde ederek hem teorik bilgilerimi pratikte uygulama fırsatı bulmayı hem de sektördeki gerçek iş deneyimini kazanmayı hedefliyorum. Bu staj deneyimi, kariyerimin başında sağlam bir temel oluşturacak ve kariyer hedefim için önemli bir adım olacaktır.

### Teknik (Örnek projeler, linkleri ve detayları)

Projelerimin tamamına [profilimden](https://github.com/emirsansar) ulaşabilirsiniz.  

_Subscription Tracker:_ [link](https://github.com/emirsansar/HesApp---Subscriptions-Tracker)
_Mobil Oyun:_ [link](https://github.com/emirsansar/Catch-The-Kotlin-Game)

- **İlgilendiklerim (diller, frameworkler vs):** 

**Mobil Programlama:**
- Kotlin - Android
- Swift - iOS

**Web Programlama:**
- Java - Spring Boot
- Python - Django
- PHP

Diğer bildiğim diller: C#, Javascript

**Database:** 
MySQL, MSSQL, Firebase

**Comment by VB10** [comment]
Merhaba @emirsansar, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emirsansar, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @emirsansar, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
