### ISSUE TITLE
Yılmaz Ersoy [frontend][uzaktan][zorunlu, gönüllü][4hafta,6hafta]

### ISSUE THREAD

**Issue by yilmazersoy** [VB10/staj_2024#712]
### Kişisel:

- **Ad Soyad:** Yılmaz Ersoy
- **Okul:** Kütahya Dumlupınar Üniversitesi
- **Sınıf:** Bilgisayar Mühendisliği / 3.Sınıf
- **CV:** [Yilmaz-Ersoy-CV](https://github.com/VB10/staj_2024/files/15475241/Yilmaz-Ersoy-CV-English.pdf)

- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):
Merhabalar, Kütahya Dumlupınar Üniversitesi Bilgisayar Mühendisliği 3.Sınıf öğrencisiyim. Frontend Developer olarak bir süredir kendimi bu alanda geliştirmekteyim. Bireysel olarak her ne kadar projeler geliştiriyor olsam da profesyonel bir ekiple çalışarak yeni deneyimler elde etmek istiyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

Projelerimin bir kısmına [GitHub ](https://github.com/yilmazersoy) adresimden ulaşabilirsiniz.

- **İlgilendiklerim (diller, frameworkler vs):**
* HTML 
* CSS
* SASS
* Bootstrap
* JavaScript
* jQuery
* React
* Git 
* GitHub

**Comment by VB10** [comment]
Merhaba @yilmazersoy, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @yilmazersoy, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
