### ISSUE TITLE
Tahsin Emre Telli [mobile,backend,database][uzaktan,yüzyüze][zorunlu][4hafta]

### ISSUE THREAD

**Issue by tahsin-emre** [VB10/staj_2024#716]
### Kişisel:

- **Tahsin Emre Telli**
- **Okul:** Altınbaş Üniversitesi, Yazılım Mühendisliği
- **Sınıf:** 3. Sınıf
- **CV:** https://tahsinemre.com/cv.pdf
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Lise yıllarında doküman okuyarak yazılım geliştirmeye başladım. Programcılığa başladıktan sonra proje geliştirme alanında da kendimi ilerletmek için yazılım mühendisliği alanında lisans eğitimi almaya karar verdim.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):** Flutter, Firebase, Google Cloud, RestAPI, Project Management

**Comment by VB10** [comment]
Merhaba @tahsin-emre, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by tahsin-emre** [comment]
Staja başladım.
