### ISSUE TITLE
tunahan turna [devops, backend][uzaktan][gönüllü][4ay]

### ISSUE THREAD

**Issue by Tunarwn** [VB10/staj_2024#719]
### Kişisel:

- Tunahan Turna
- Ecole 42, Anadolu Üniversitesi (YBS 2. sınıf)

- **CV:** [https://drive.google.com/file/d/14fjmVGpcmqEPI6lG1tbaCtJ6Jb0jQU2d/view?usp=sharing](#)
- **Sigorta Okul Karşılıyor** (Hayır): 

### Kendin Hakkında (kendini anlatmak istersen):

Ben Tunahan Turna. Uluslararası bir yazılım okulu olan Ecole 42 mezunuyum. Aynı zamanda Anadolu Üniversitesi Yönetim Bilişim Sistemleri 2. sınıf öğrencisiyim. Ecole 42 kapsamında 4 ay sürecek olan stajım için bir firma arayışındayım.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):** AWS, Cloud technologies, Web technologies (django, javascript)

**Comment by VB10** [comment]
Merhaba @Tunarwn, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
