### ISSUE TITLE
İmam Kılıçaslan [game][uzaktan][zorunlu][4hafta]

### ISSUE THREAD

**Issue by imamkilicaslan** [VB10/staj_2024#728]
### Kişisel:

- **Ad Soyad: İmam Kılıçaslan**
- **Okul: Doğuş Üniversitesi**
- **Sınıf: 3.Sınıf**
- **CV:** [[CV Linki](https://drive.google.com/file/d/17up14QL_9K1_wUHIP74IKJ4yJ-7L7j8n/view?usp=sharing)]
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendim Hakkında:

Eğlenceli ve yaratıcı düşünmeyi seven ve projelerimi bu düşünceyle geliştirmek isteyen bir Oyun geliştiricisiyim. 
Şu an Doğuş Üniversitesi Yönetim Bilişim Sistemleri 3.Sınıf öğrencisiyim, gelecek yıl mezun olacağımdan dolayı, staj sonrasında part time veya full time olarak çalışmayı deneyebilir ve sorumluluklarımın bilincinde olarak disiplinli bir şekilde çalışabileceğimi söylemek istiyorum.

### Teknik (Örnek projeler, linkleri ve detayları)
- **Play store'da yayınlanan DNA Jam oyunum:** [[DNA Jam](https://play.google.com/store/apps/details?id=com.SmyrnaGames.DNAJam&pcampaignid=web_share)]

**Comment by VB10** [comment]
Merhaba @imamkilicaslan, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @imamkilicaslan
