### ISSUE TITLE
Kürşat Hürkan Aydın [Back-End][Uzaktan][Gönüllü][rhafta]

### ISSUE THREAD

**Issue by kursathurkanaydin** [VB10/staj_2024#729]
### Kişisel:

- **Kürşat Hürkan Aydın:**
- **Hacettepe Üniversitesi Bilgisyar Mühendisliği:**
- **Hazırlık:**
- **[CV](https://www.linkedin.com/in/k%C3%BCr%C5%9Fat-h%C3%BCrkan-ayd%C4%B1n-37990b284/):** 
- **hayır** (Evet/Hayır): 

### Algoritma çözmeye bayılıyorum. Her gün bir adet leetcode sorusu çözüyorum. Bunun dışında java alanında kendimi geliştirmeye çalışıyorum. Güncel olarak spring boot üzerinde çalışıyorum.

(Bu bölümü doldurabilirsin)

### python ve javada algoritma çözebilecek bilgilerim var. Javada temel oop yapısına hakimim. Inheritance ve interface yapıları hakkında bilgi sahibiyim.

- **python, java, spring boot**

**Comment by VB10** [comment]
Merhaba @kursathurkanaydin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @kursathurkanaydin, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
