### ISSUE TITLE
Ömer Faruk Koramaz[Mobile,Frontend,Game,Embedded][Uzaktan,Yüzyüze][Zorunlu,Gönüllü][4Hafta,6Hafta]

### ISSUE THREAD

**Issue by koramazzz** [VB10/staj_2024#731]
Kişisel:

- Ad Soyad: Ömer Faruk Koramaz
- Okul: Boğaziçi Üniversitesi
- Sınıf: 3
- CV:   [Google Drive Linki](https://drive.google.com/file/d/1Jzw4M6FoZPDqltC6S_9-qY_-VpvBeIWO/view)
- Sigorta Okul Karşılıyor (Evet)

Kendin Hakkında (kendini anlatmak istersen):

(Heyecanlı azimli  ve eğlenceli biriyim. Ekip çalışmasına yatkın, çalışkan bir yapıya sahibim)

Teknik (Örnek projeler, linkleri ve detayları)

- İlgilendiklerim (diller, frameworkler vs):

      Java, Python, React Native

**Comment by VB10** [comment]
Merhaba @koramazzz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @koramazzz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @koramazzz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @koramazzz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @koramazzz, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
