### ISSUE TITLE
Ömer Faruk Koramaz [mobile,game,backend][uzaktan,yüzyüze][zorunlu,gönüllü][4hafta,6hafta]

### ISSUE THREAD

**Issue by koramazzz** [VB10/staj_2024#732]
### Kişisel:

- **Ad Soyad:**
- **Okul:**
- **Sınıf:**
- **CV:** [Google Drive Linki veya pdf linki](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): 

### Kendin Hakkında (kendini anlatmak istersen):

(Bu bölümü doldurabilirsin)

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @koramazzz, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
