### ISSUE TITLE
Yusuf Can Mercan [mobile, game, frontend][yüzyüze][zorunlu][4hafta, 6hafta]

### ISSUE THREAD

**Issue by cusufcan** [VB10/staj_2024#735]
### Kişisel:

- **Ad Soyad:** Yusuf Can Mercan
- **Okul:** Tokat Gaziosmanpaşa Üniversitesi
- **Sınıf:** Bilgisayar Mühendisliği 3. Sınıf
- **CV:** [Google Drive](https://drive.google.com/file/d/102NZpebWCqjIgmM8h4x6eM_YoYL-F5et/view?usp=sharing)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet 

### Kendim Hakkında:

Ben Yusuf Can Mercan, Tokat Gaziosmanpaşa Üniversitesi Bilgisayar Mühendisliği 3. sınıf öğrencisiyim. Liseden beri yazılıma olan ilgim dolayısıyla bu bölümü seçtim. Oyun Geliştirme ile başlayıp tüm ilgimi android sektörüne yönelttim. Amacım hem cross platform hem native android geliştirici olmak. Her zaman yolun başındayım ve sürekli üstüne katarak ilerlemeyi planlamaktayım.

### Teknik:

Örnek Flutter projelerim GitHub'da mevcuttur. Android Studio'yu aktif olarak öğrenmekteyim.

- **İlgilendiklerim:** Flutter, Android Studio, Dart, Java, Kotlin, HTML, CSS, Bootstrap.

**Comment by VB10** [comment]
Merhaba @cusufcan, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @cusufcan
