### ISSUE TITLE
Serhat Şimşek [mobile][uzaktan,yüzyüze][zorunlu][4hafta,6hafta]

### ISSUE THREAD

**Issue by srhtsimsek** [VB10/staj_2024#739]
### Kişisel:

- **Ad Soyad: Serhat Şimşek**
- **Okul: Fırat Üniversitesi**
- **Sınıf: 3. Sınıf**
- **CV:** [https://drive.google.com/file/d/1hYTcPJo-BYf1iu6dUdp2dGZOzPlsssdk/view?usp=share_link](#)
- **Sigortamı üniversitem karşılıyor.** 

### Hakkımda:

Merhabalar.
 Yaklaşık bir buçuk yıldır swift ile ilgileniyorum.
Zorunlu 40 günlük yaz stajım için iOS development alanında staj yapmak istiyorum.  Sigortam üniversitem tarafından karşılanıyor.
 
Staj tarihim: 22 Temmuz-13 Eylül

Daha sonrasında uzun dönem zorunlu işyeri eğitimim de bulunmakta olup takdirinize bağlı olarak devam edebilirim.
Saygılarımla, 
Serhat.

### Teknik

- **İlgilendiklerim: Swift, UIKit, MVVM, MVC, Protocol Oriented Programming**

**Comment by VB10** [comment]
Merhaba @srhtsimsek, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
