### ISSUE TITLE
Mert Coşkuner [ "backend","data-science","database"]["yüzyüze"]["zorunlu"]["6hafta"]

### ISSUE THREAD

**Issue by mertcoskuner** [VB10/staj_2024#74]
### Kişisel:

- **Ad Soyad: Mert Coşkuner**
- **Okul: Sabancı Üniversitesi**
- **Sınıf: 4**
- **CV:** -
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

Sabancı Üniversitesi'nde son sınıf Bilgisayar Bilimi ve Mühendisliği öğrencisiyim aynı zamanda iş analitiği üzerine yandal yapmaktayım ve zorunlu yaz stajı aramaktayım, teknolojiyi karmaşık sorunları çözmek için kullanmaktan büyük bir tutkuya sahibim. Şu anda hedefim makine öğrenimi, finans ve yazılım mühendisliği üzerine odaklanarak, veri odaklı yaklaşımları incelemek bu yüzden aradığım staj genellikle makine öğrenmesi ve veri bilimi üzerine. Daha önce çeşitli derslerde asistanlığım (matematik ve bilgisayar bilimi dersleri) mevcut aynı zamanda bir tanesi Intertech diğeri TÜBİTAK Bilgem'de olmak üzere 2 adet gönüllü yazılım stajım mevcut. Son olarak bir önceki sonbahar dönemini aktif olarak makine öğrenmesi üzerine Sabancı Üniversitesi'nin PURE (Program for Undergraduate Research) programı altında araştırma projesi yaparak geçirdim.

Linkedin: https://www.linkedin.com/in/mertcoskuner/
E-mail: mertcoskuner@gmail.com
Not: 
-CV paylaşımını herkese açık alanlarda doğru bulmuyorum ilgilenilmesi durumunda daha önceden aldığım ve önümüzdeki dönem alacağım derslerle birlikte mail adresim üzerinden iletebilirim. 
-Planlanan mezuniyet tarihim 2025 Ocak ayı olduğundan dolayı yaz stajı sonrası part-time ve full-time çalışma opsiyonlarına açığım. 
-Okulumun zorunlu staj süresi 2 aydır fakat burada maksimum olarak 6 hafta gösterbiliyorum.

### Teknik (Örnek projeler, linkleri ve detayları)
Kullandığım teknolojiler, yazılım dilleri ve detayları için profilime bakabilirsiniz.( Yaptığım projeler her dönem sonu güncellenmektedir.)

**Comment by VB10** [comment]
Merhaba @mertcoskuner, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mertcoskuner, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @mertcoskuner, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba arkadaşlar 
Sizler için yaklaşık 6 aydır çalıştım paylaştım elimden gelen tüm insanlara gelin bu repodan arkadaşlar var hazır bulun.
Hepinize erişemedim ama elimden gelenin çok daha fazlasına ulaştım staj sorununa yardım etmeye çalıştım.


İsterdim ki sektörde bu kadar yazılım şirketi var bu sorunu yaşamayın ama toz pembe sektör bir çok yayında anlattığım gibi.
Bir stajı yapmak ne bir işin başlangıcı yapamamak ise ne sonu. Önemli olan daima sizlersiniz

Hayat akıp giderken çok çalışıp başarılı olmaya emek vererek alın terinizle gitmeye devam edin.
Ben var olduğum sürece emek veren çalışkan arkadaşların yanında olmaya çalışacağım.
Bakarsınız bir gün daha büyürüm daha çok arkadaşa yardımcı olurum.


İşin özü hepinize gelecek dönemde başarılar diliyorum.
Umarım istediğiniz işi çalışma ortamını bulur ve mutlu güzel günler yaşarsınız.

Sevgirimle
vb10 (Repoyu akşam itibariyle sileceğim sizin bilgilerinizin elden geldiğince güvenliği için)
 @mertcoskuner
