### ISSUE TITLE
HASAN ULU [MOBİL][OFİSTEN][ZORUNLU][20]

### ISSUE THREAD

**Issue by wascodedbyhasan** [VB10/staj_2024#740]
HASAN ULU
GAZİ ÜNİVERSİTESİ
4. SINIF
https://www.linkedin.com/in/hasanulu/overlay/1718306421124/single-media-viewer/?profileId=ACoAADFNFrABHAv2nP73WFiD_zjcrTu0hEMnkSU
SİGORTAMI OKUL KARŞILIYOR

-----------------------------------

Merhaba,

Mobil uygulama geliştirme alanında kariyerime yön vermek ve gerçek dünya deneyimlerini kazanmak amacıyla, şirketinizdeki staj programınıza başvurmak istiyorum. Şirketinizin sektördeki yenilikçi yaklaşımı ve üstün teknolojik çözümleriyle tanınması, beni bu değerli deneyimi yaşamak için heyecanlandırmaktadır. Staj sürecinde şirketin dinamik ekibinde yer almak, profesyonel becerilerimi geliştirmek ve yeni teknolojilere dair bilgi birikimimi artırmak için önemli bir fırsat olacaktır. Özellikle; mobil uygulama geliştirme, yapay zekâ ve mühendislik süreçleri konularında deneyim kazanmak istiyorum. Şirketinizde staj yaparak, bilgisayar mühendisliği alanında kariyerime güçlü bir başlangıç yapmayı umuyorum. Ekibinizle birlikte çalışmak ve sizinle birlikte başarıya ulaşmak için sabırsızlanıyorum.

Saygılarımla,

-----------------------------------

Öğrencilik serüvenimde yapmış olduğum projelerin tamamını GitHub hesabımda paylaştım. İnceyebilirsiniz.

-----------------------------------

Java, JavaScript, TypeScript, Dart, Flutter ve Android Studio.

**Comment by VB10** [comment]
Merhaba @wascodedbyhasan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @wascodedbyhasan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
