### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by Ahmetakaslan** [VB10/staj_2024#743]
### Kişisel:

- **Ad Soyad:** Ahmet Akaslan
- **Okul:** Fırat Üniversitesi
- **Sınıf:** 3.Sınıf
- **CV:** [https://tls.tc/04nll](#) 
- **Sigorta Okul Karşılıyor** Evet 22 Temmuz 13 Eylül: 

### Kendin Hakkında (kendini anlatmak istersen):
Flutter **firebase** ,**sqflite**,**statemangment** (provider,riverpod ,bloc "cubit"),**widget**,**ui**,**Design pattern**.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):** **Flutter&Dart** -  **NodeJs** **java&kotlin**

**Comment by VB10** [comment]
Merhaba @Ahmetakaslan, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
