### ISSUE TITLE
Ertuğrul-KARTAL [frontend,mobile][Eskişehir][zorunlu][4 hafta,6 hafta]

### ISSUE THREAD

**Issue by Erto5555** [VB10/staj_2024#748]
### Kişisel:

- **Ad Soyad: Ertuğrul Kartal**
- **Okul: Tokat Gaziosmanpaşa Üniversitesi**
- **Sınıf: 3. sınıf**
- **CV:** [https://docs.google.com/document/d/1ZauncjFxm6oHh_poE3Lg19ZxkuYS9v3RLTywfRxkRuU/edit?usp=sharing](#)
- **Sigorta Okul Karşılıyor** (Hayır)

### Kendin Hakkında (kendini anlatmak istersen):

Stajı sadece zorunlu diye değil bir şeyler öğrenmek ve başarılı olursam orada işe devam etmek için yapıyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

- **İlgilendiklerim (diller, frameworkler vs):**
Web kısmında ilgiliyim,tasarım kısmında ilgiliyim, temel düzeyde HTML,CSS bilgim var, 3 boyutlu tasarımlar yapıyorum(blender programı)

**Comment by VB10** [comment]
Merhaba @Erto5555, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
