### ISSUE TITLE
AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]

### ISSUE THREAD

**Issue by senaksu** [VB10/staj_2024#753]
### Kişisel:

- **Ad Soyad:** Sena Aksu
- **Okul:** Sakarya Üniversitesi
- **Sınıf:** 4. Sınıf
- **CV:** ["https://drive.google.com/file/d/1CIUGNcFkGL4wTw-mvVnomoqTDuVMIMSc/view?usp=sharing"](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### 

Merhaba ben Sena Sakarya Üniversitesi bilgisayar mühendisliği 4. sınıf öğrencisiyim, veri bilimi ve yapay zeka alanlarına tutkuluyum. Yeni projelere dahil olmaktan ve kendimi geliştirmekten heyecan duyuyorum.

**Comment by VB10** [comment]
Merhaba @senaksu, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
