### ISSUE TITLE
İpek Ünlü [data-science][uzaktan, yüzyüze][zorunlu, gönüllü][4hafta, 6hafta]

### ISSUE THREAD

**Issue by iberceste** [VB10/staj_2024#78]
### Kişisel:

- **Ad Soyad: İpek Ünlü**
- **Okul: İstanbul Yeni Yüzyıl Üniversitesi**
- **Sınıf: 3. sınıf**
- **CV:** [CV](https://drive.google.com/file/d/1ycBrjKV2XZ6VCiSIeegbcaJuAq-3-unk/view)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Hakkımda:

Ben İpek Ünlü, İstanbul Yeni Yüzyıl Üniversitesi 3. sınıf öğrencisiyim. Bireysel projelerim sırasında Python, Makine Öğrenimi ve Veri bilimi konularında beceriler edindim. Veri bilimi ve makine öğrenimi üzerine projeler geliştiriyorum. Ayrıca en son yapay zeka teknolojileri hakkında güncel kalmaya ve bunları aktif olarak projelerime entegre etmeye de özen gösteriyorum. Projelerimde Scikit-Learn, Tensorflow, Pandas, Matplotlib, Seaborn gibi önemli Python kütüphanelerini kullanarak modeller kurup değerlendiriyorum. Sürekli olarak kendimi geliştirme yolculuğundayım ve her zaman becerilerimi ve bilgilerimi geliştirmeyi hedefliyorum. Zorunlu stajlarım dışında çalışmakta çok isterim.

### Teknik :
Örnek projeleri profilimden ve linkedin profilimden ulaşabilirsiniz.

**LİNKEDİN:** [Linkedin profilim](https://www.linkedin.com/in/ipek-%C3%BCnl%C3%BC-3106b7295/)

- **İlgilendiklerim:**
Python
Veri Bilimi
Machine Learning
Deep Learning
Scikit-learn
Tensorflow
Pandas
Seaborn

**Comment by VB10** [comment]
Merhaba @iberceste, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @iberceste, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.

**Comment by VB10** [comment]
Merhaba @iberceste, staj başvurun başarı ile taglendi..
  Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
  Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
