### ISSUE TITLE
Sabir Halil [["mobile", "backend"]["uzaktan", "yüzyüze"]["zorunlu", "gönüllü"][["4hafta","6hafta"]

### ISSUE THREAD

**Issue by SabirHalil** [VB10/staj_2024#81]
### Kişisel:

- **Ad Soyad: Sabir Halil**
- **Okul: Erciyes Üniversitesi**
- **Sınıf: 3**
- **CV:** [[Google Drive Linki veya pdf linki](https://drive.google.com/file/d/1oBb3on3N1I_HTOWjGsiQqH18eHOGeaHh/view?usp=sharing)](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet

### Kendin Hakkında (kendini anlatmak istersen):

(Yaklaşık iki yıldır mobil uygulama geliştirme alanında deneyime sahibim. Android uygulama geliştirmeye Kotlin ile başladım ve birçok uygulama play store yükledim. Son bir aydır Flutter'a geçiş yaptım. Aynı zamanda .NET Core kullanarak birkaç proje geliştirdim.)

### Teknik (Örnek projeler, Sahte Arama. Kotlin ile yazıldi. https://play.google.com/store/apps/details?id=com.devhard.calljoke
Fırın Takibi. Flutter ile yazıldı. https://github.com/SabirHalil/bakery_mobile_app
)

- **İlgilendiklerim (Kotlin, Java, Flutter, C#):**

**Comment by VB10** [comment]
Merhaba @SabirHalil, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @SabirHalil, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @SabirHalil, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @SabirHalil, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
