### ISSUE TITLE
Elif Beyza-Sağlam ["Mobil"]["uzaktan", "yüz yüze"]["zorunlu"]["4 hafta"]

### ISSUE THREAD

**Issue by elifbeyzasaglam** [VB10/staj_2024#85]
### Kişisel:

- **Ad Soyad: Elif Beyza Sağlam**
- **Okul: Fırat Üniversitesi**
- **Sınıf:3.Sınıf**
- **CV:** [[Google Drive Linki veya pdf linki](https://drive.google.com/drive/folders/13jTH_1Ddz56DXhW7O_Yl-EwyI2E6C32i?usp=sharing)](#)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Evet 

### Kendin Hakkında (kendini anlatmak istersen):

Swift Developer olarak kendimi geliştirmeye, bu alanda yeni bilgiler öğrenmeye ve Fırat Üniversitesi Yazılım Mühendisliği 3. sınıf öğrencisi olarak okumaya devam ediyorum.

**Comment by VB10** [comment]
Merhaba @elifbeyzasaglam, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @elifbeyzasaglam, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @elifbeyzasaglam, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @elifbeyzasaglam, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @elifbeyzasaglam, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
