### ISSUE TITLE
Seyyid Hamza Zahid [mobile][uzaktan-yüz yüze][gönüllü][4 Hafta-6 Hafta]

### ISSUE THREAD

**Issue by zahidseyyid** [VB10/staj_2024#90]
### Kişisel:

- **Ad Soyad:** Seyyid Hamza Zahid
- **Okul:** İstanbul Üniversitesi - Bilgisayar Programcılığı
- **Sınıf:** 1
- **CV:** [Google Drive Linki veya pdf linki](#) [https://drive.google.com/file/d/1NBDXGee8JJAjdJtEpicXfnE1FARvy959/view?usp=sharing](url)
- **Sigorta Okul Karşılıyor** (Evet/Hayır): Hayır

### Kendin Hakkında (kendini anlatmak istersen):

3 yıldır girişim ekosisteminde aktif olarak rol alıyorum. Girişimciliğin yanı sıra HTML, CSS ve JavaScript ile başladığım yolculuğumu bir kurumdan aldığım Java eğitimi ile mobil tarafına yönlendirdim. Veli hocam ve Google Oyun ve Uygulama Akademisi sayesinde Flutter alanında güzel bir ilerleme kaydettim. Gerçek hayat projelerinde edindiğim deneyimlerle öğrendiğim bilgileri pekiştireceğim bir staj yapmak istiyorum.

### Teknik (Örnek projeler, linkleri ve detayları)

- İlgilendiklerim(Flutter, dart, javascript, node.js)

**Comment by VB10** [comment]
Merhaba @zahidseyyid, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @zahidseyyid, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @zahidseyyid, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
