### ISSUE TITLE
MERT ALP [mobile ][yüzyüze,uzaktan][zorunlu,gönüllüİ][4hafta,6hafta]

### ISSUE THREAD

**Issue by mertalp0** [VB10/staj_2024#98]
### Kişisel:

- **Ad Soyad: Mert ALP
- **Okul: Balıkesir Üniversitesi
- **Sınıf: 4.Sınıf
- **CV: https://my-portfolio-eight-bice-67.vercel.app
- **Sigorta Okul Karşılıyor** (Evet/Hayır):  Evet

### Kendin Hakkında (kendini anlatmak istersen): 

Merhaba, Ben Bilgisayar Mühendisliği 4. sınıf öğrencisiyim ve mobil geliştirme konusunda yoğun bir ilgiye sahibim. Flutter teknolojisi ve Swift ile birçok proje geliştirdim. Ayrıca, Java kullanarak mobil uygulama geliştirdim ve bu projeleri YouTube üzerinden paylaştım. Github hesabımdan ve portfolio sitemden projelerime ve çalışmalarıma göz atabilirsiniz.Projelerim ve çalışmalarımla ilgili daha fazla bilgi almak isterseniz, Github hesabım ve portfolio sitem üzerinden inceleyebilirsiniz.

Okulumun zorunlu kıldığı 40 iş günü stajımı yapmayı planlıyorum ve bu stajı yaz aylarında yüzyüze gerçekleştirmek istiyorum. İkinci dönem içerisinde gönüllü olarak staj yapmak istiyorum, bu staj hem yüzyüze hem de uzaktan gerçekleştirilebilir. İlginiz için şimdiden teşekkür ederim. 

### Teknik (Örnek projeler, linkleri ve detayları)
portfolio : https://my-portfolio-eight-bice-67.vercel.app

- **İlgilendiklerim (diller, frameworkler vs):**

**Comment by VB10** [comment]
Merhaba @mertalp0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by VB10** [comment]
Merhaba @mertalp0, bu issue'nun başlığı belirlenen formata uymuyor.
  Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
  Örnekler için:
  https://github.com/VB10/staj_2024/issues/1
  Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.

**Comment by mertalp0** [comment]
teşekkürler düzeltme yaptım.
